KissKissBankBank/kitten

CHANGELOG.md
assets/javascripts/kitten/components/box/doc-link-box.test.js
assets/javascripts/kitten/components/box/link-box.test.js

Ajoute des tests pour les 2 composants `LinkBox` et `DocLinkBox`.

LinkBox and DocLinkBox testing

---

assets/stylesheets/kitten/molecules/testimonies/_testimony.scss

PR qui permet de centrer le titre des témoignages.
Avant : 
Après :

Title testimony alignment

---

CHANGELOG.md
assets/stylesheets/kitten/molecules/grid/_row.scss

Permet d'ajouter une bordure grise en haut d'une `row`.

Add modifier k-Row--lightTopBorder on k-Row

---

CHANGELOG.md
assets/stylesheets/kitten/molecules/footer/_footer.scss

Fix image width in footer

---

CHANGELOG.md
assets/javascripts/kitten/components/simulators/loan-simulator.js
assets/javascripts/kitten/karl/organisms/loan-simulator.js

Permets d'exprimer les règles d'attribution de commission sous forme d'un hash plutôt que d'une fonction.
Avant :
```js
commissionRate: function(duration) {
if (duration <= 9)
return 0.03
else if (duration <= 18)
return 0.04
else if (duration <= 24)
return 0.05
else
return 0.06
},
```
Après :
```js
commissionRules: [
{ durationMax: 9, rate: 0.03 },
{ durationMax: 18, rate: 0.04 },
{ durationMax: 24, rate: 0.05 },
{ rate: 0.06 },
],
```
Ça permets de passer ces valeurs plus facilement via des props que renverrait une application Rails.

Add commissionRules prop to LoanSimulator

---

CHANGELOG.md
spec/dummy/config/initializers/react_on_rails.rb

Disable React on Rails development trace for style guide

---

CHANGELOG.md
assets/stylesheets/kitten/components/simulators/_loan-simulator.scss

The label size must be 14px (instead of 16px).
Screenshots:
Before: 
After:
TODO:

Change commission label size in loan simulator

---

CHANGELOG.md
assets/stylesheets/kitten/components/testimonies/_testimony-list.scss

Testimony row is larger on xxs

---

CHANGELOG.md
assets/stylesheets/kitten/components/press/_press-quotes.scss
assets/stylesheets/kitten/components/titles/title-with-actions.scss

Ajoute des marges par défaut pour ne pas dépendre du fait qu'on utilise des `h2` dans notre exemple de home.
Si on utilise `div` à la place de `h2` ça fait ça :
Avant :
Après :

Add default margins to homepage titles

---

CHANGELOG.md
README.md
app/helpers/kitten/webpack_helper.rb
spec/dummy/Procfile
spec/dummy/client/bin/webpack-dev-server.js
spec/dummy/client/webpack.client.dev.babel.js

Pour qu'on puisse bosser sur les différentes applications en même temps, le port par défaut passe de 3000 à 3003.
Après cette PR il faudra utiliser http://localhost:3003 pour tester nos composants.

Change default dev port for styleguide from 3000 to 3003

---

CHANGELOG.md
assets/javascripts/kitten/components/form/checkbox.js
assets/javascripts/kitten/components/form/checkbox.test.js
assets/javascripts/kitten/components/form/radio-button.js
assets/javascripts/kitten/components/form/radio-button.test.js

PR qui permet d'ajouter des classes sur les `input` des composants `RadioButton` et `Checkbox`.
TODO:

Add inputClassName on RadioButton and Checkbox components

---

config/routes.rb

Je propose ce petit changement vu que par défaut on se sert plutôt de la page components plutôt que de la page branding. Qu'en pensez-vous ? #débat

Redirect to components instead of branding by default

---

CHANGELOG.md
assets/stylesheets/kitten/components/headers/_header.scss

PR qui annule le click sur toute la partie `k-Header__item--centered` qui passait au dessus du logo et du bouton, empêchant le click sur ceux-ci.
TODO:

Remove pointer-events on `k-Header__item--centered`

---

CHANGELOG.md
assets/stylesheets/kitten/components/form/_label.scss

PR qui augmente le `line-height` du `Label` sur la version `tiny`.
Avant : 
Après : 
TODO:

Increase line-height on tiny `Label`

---

CHANGELOG.md
assets/stylesheets/kitten/components/form/_search-input.scss

Closes https://github.com/KissKissBankBank/kisskissbankbank/issues/1030.
Screenshot:
TODO:

Prevent newline in mobile view for `SearchInput` component

---

CHANGELOG.md
assets/stylesheets/kitten/components/form/_search-input.scss

Fix: Remove unneeded padding on `SearchInput`

---

CHANGELOG.md
assets/javascripts/kitten/components/form/text-input-with-limit.js
assets/javascripts/kitten/components/form/text-input-with-limit.test.js
package.json

Le composant `TextInputWithLimit` gère lui-même un comportement sur l'événement `onChange`. Actuellement, lorsqu'on passe au composant une prop `onChange`, celle-ci écrase le comportement par défaut.
Cette PR ajoute le fait de prendre la prop `onChange` en compte, en plus du comportement de base pour cet événement.

Fix `TextInputWithLimit` onChange prop

---

CHANGELOG.md
assets/javascripts/kitten/components/typography/title.js
assets/javascripts/kitten/components/typography/title.test.js
assets/stylesheets/kitten/components/typography/_title.scss

PR qui permet d'annuler les marges verticales par défaut sur le composant `Title`.
TODO:

Add margin prop to Title component

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/grid.js
assets/javascripts/kitten/components/grid/grid.test.js

PR qui permet de propager la prop `className` sur les composants `Grid` et `GridCol`.
TODO:

Propagate className prop to Grid and GridCol

---

CHANGELOG.md
assets/javascripts/kitten/components/typography/paragraph.js
assets/javascripts/kitten/components/typography/paragraph.test.js
assets/stylesheets/kitten/components/typography/_paragraph.scss

PR qui permet d'avoir une option/classe pour mettre le `line-height` par défaut dans le composant `Paragraph`.
TODO:

Add normalLineHeight prop to Paragraph component

---

CHANGELOG.md
assets/stylesheets/kitten/components/form/_checkbox.scss
assets/stylesheets/kitten/components/form/_radio-button.scss
assets/stylesheets/kitten/components/form/_switch.scss

Change le `line-height` des composants `RadioButton/Checkbox/Switch`.
Avant / Après : 
TODO:

Update line-height on RadioButton/Checkbox/Switch

---

CHANGELOG.md
assets/javascripts/kitten/components/form/text-input-and-select.js
assets/javascripts/kitten/components/form/text-input-and-select.test.js

Pour gérer les cas d'erreur et la soumission des valeurs du composant `FormAmountAndCurrency`, j'ai ajouté dans cette PR : 
- une prop `errorOnSelect` pour gérer l'état d'erreur sur `SelectWithState`,
- un handler pour la prop `onInputChange` de `SelectWithState`.
J'ai laissé un test en stand-by (n'ayant pas trouvé d'idée de comment le tester) et j'ai également ajouté des TODO dans le composant lui-même pour retirer tout couplage entre ce composant et des possibles composants parents.
TODO:

Add onSelectChange and errorOnSelect props to TextInputAndSelect

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/container.js
assets/javascripts/kitten/components/grid/container.test.js
assets/stylesheets/kitten/_components.scss
assets/stylesheets/kitten/components/grid/_container.scss
spec/dummy/client/entries/app-kitten.js
spec/dummy/client/stylesheets/kitten/_components.scss

PR qui permet d'avoir un composant pour créer un container. Souvent nos composants de `grid` embarque un container mais en terme de composition nous sommes assez limités. Avec ce nouveau composant on peut gérer entièrement une grille en mode composition : 
```js
<Container>
<Grid>
<Grid col="12"/>
…
</Grid>
</Grid>
</Container>
```
TODO:

Add Container component

---

CHANGELOG.md
app/assets/stylesheets/kitten/karl/_card.scss
assets/javascripts/kitten/components/grid/lego-grid.js
assets/javascripts/kitten/components/grid/lego-grid.test.js
assets/javascripts/kitten/karl/grid/lego-grid.js
assets/stylesheets/kitten/components/grid/_lego-grid.scss

PR qui permet d'ajouter des marges à l'intérieur des items. Pour éviter de l'ajouter du côté de l'élément à l'intérieur d'un item.
TODO:

Add grid in `LegoGrid.Item` component

---

CHANGELOG.md
assets/stylesheets/kitten/components/grid/_lego-grid.scss

PR qui fixe un scroll horizontale visible sur mobile, dû à une mauvaise gestion des gouttières sur cette media-query.
TODO:

Fix `LegoGrid` grid

---

README.md

L'équipe produit a plutôt tendance à utiliser `Kitten` que `kitten`. Cette PR est une proposition pour qu'on fasse de même ici.
Je trouve que ça ressemble plus à `Kiss`, donc ça me paraît logique également dans ce sens.

Rename kitten to Kitten

---

KARL_CHANGELOG.md
assets/javascripts/kitten/karl/buttons/payment-button.js

Voir #647 
Finalement on a décidé avec les hautes autorités que l'on retire les composants `<Line> et <Line.Item>

Remove `Line` and `Line.Item` on `KarlPaymentButtons` example

---

spec/dummy/package.json

La commande `npm run build:dev` dépends de l'executable `webpack` pour fonctionner. J'ai donc l'impression qu'il faut installer webpack pour s'en servir. Je propose donc de l'ajouter comme dépendence via `kitten-launcher`.

Add webpack dependency

---

CHANGELOG.md
package.json

Parce que sinon ça requiert `yarn` sur les apps.

Prefer npm to yarn for postinstall script

---

spec/dummy/client/package.json

Permets d'avoir un dossier où se trouve `kitten` qui soit nommé différemment (pour installer l'app dans Docker par exemple #663).

Better kitten path in example package

---

assets/stylesheets/kitten/components/lists/_bullet-list.scss

Sur la version `big` du composant `BulletList`, les marges verticales passent de `5px` à `10px`.

Update vertical margins on big bullet list

---

CHANGELOG.md
assets/stylesheets/kitten/components/buttons/_tag-button.scss

Closes #https://github.com/KissKissBankBank/kisskissbankbank/issues/1156.
Screenshot:
TODO:

Fix: Change `TagButton` background color

---

assets/stylesheets/kitten/components/cards/_project-creator-card.scss

Fix: Le texte dans la partie `link` était pas centré verticalement.

Fix `align-items: center` ProjectCreatorCard

---

CHANGELOG.md
assets/javascripts/kitten/components/form/rich-text-input.js

While merging object with `Object.assign`, react on rails raise an error because `Object` has no method `assign`.
Merge object with spread properties (es6 way) to prevent this error.

Fix react on rails error

---

app/views/layouts/kitten/application.html.erb

Peut peut-être éviter que Chrome nous propose de traduire la page en latin.

Add language attribute to html tag

---

Rakefile

Since `yarn publish` tries to change the version number.

Revert back to npm publish

---

Rakefile

Annote les tags de versions.
> A lightweight tag is very much like a branch that doesn’t change – it’s just a pointer to a specific commit.
>
> Annotated tags, however, are stored as full objects in the Git database. They’re checksummed; contain the tagger name, email, and date; have a tagging message; and can be signed and verified with GNU Privacy Guard (GPG). It’s generally recommended that you create annotated tags so you can have all this information; but if you want a temporary tag or for some reason don’t want to keep the other information, lightweight tags are available too.
> — https://git-scm.com/book/en/v2/Git-Basics-Tagging

Release Kitten with annotated tags

---

CHANGELOG.md
assets/stylesheets/kitten/components/uploaders/_simple-uploader.scss

PR qui fixe le rendu responsive du composant `SimpleUploader`.

Fix `SimpleUploader` responsive

---

CHANGELOG.md
assets/javascripts/kitten/components/form/label.js
assets/javascripts/kitten/components/form/label.test.js
assets/stylesheets/kitten/components/form/_label.scss

PR qui permet de retirer le `hover`, `focus`, etc. sur un `Label`.
TODO:

Add `withoutPointerEvents` prop to `Label` component

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/similar-projects-card.js

La prop `onRefreshClick` n'était pas passée correctement au composant `SimilarProjectCard`.

Pass onRefreshClick prop to SimilarProjectCard

---

CHANGELOG.md
assets/stylesheets/kitten/components/box/_link-box.scss

Linked to https://github.com/KissKissBankBank/kisskissbankbank/issues/1704
Screenshot:
TODO:

Fix `LinkBox` paragraph container size

---

CHANGELOG.md
assets/stylesheets/kitten/components/form/_text-input.scss

Closes #870.
Refer to : https://github.com/KissKissBankBank/kisskissbankbank/issues/1768
Screenshot:
TODO:

Fix `TextInput` length for Firefox

---

bin/install

Cette PR fixe un problème de version de Ruby quand on lance `bundle exec rake kitten_release`.

Remove ruby's verification in installation script

---

CHANGELOG.md
assets/javascripts/kitten/components/images/image-cropper.js

PR qui lance la prop `onChange` dans le traitement du reset. Ca permet ensuite d'avoir l'information qu'il faut supprimer l'image.

Handle `onChange` prop in reset event in `ImageCropper` component

---

CHANGELOG.md
assets/javascripts/kitten/components/form/select-with-state.js
assets/javascripts/kitten/components/form/select-with-state.test.js

Suite à la nouvelle version, le composant retourne `null` quand on supprime la sélection. Pour l'instant je retourne le même genre d'objet à l'app. À voir si null peut suffire !
TODO:

Fix null value on `SelectWithState`

---

CHANGELOG.md
assets/javascripts/kitten/components/form/text-input-with-unit.js
assets/stylesheets/kitten/components/form/_location-input.scss
assets/stylesheets/kitten/components/form/_select.scss
assets/stylesheets/kitten/components/form/_text-input-with-unit.scss

A vérifier si l'état `: focus` du `Select` se retire quand `is-open` est a `true`.
Je sais pas si c'est son état normal.
TODO:

Fix `:focus` `border-color` on `TextInputWithUnit`, `Select` et `LocationInput` component

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/horizontal-nav.js
assets/javascripts/kitten/components/navigation/horizontal-nav.test.js

Corrige une erreur sur `HorizontalNav`. Le `href` était mis sur le `<li>` à la place d'être sur le `<a>`.
TODO:

Move `href` prop on link items

---

CHANGELOG.md
KARL_CHANGELOG.md
assets/javascripts/kitten/karl/navigation/horizontal-nav.js
assets/stylesheets/kitten/components/grid/_row.scss

Comme le `Header` et l'`HorizontalNav` sont collés sur la maquette, je voyais un `borderTop` mais en fait non c'était `borderBottom` du `Header`.
TODO:

Remove border-top in HorizontalNav

---

CHANGELOG.md
KARL_CHANGELOG.md
assets/javascripts/kitten/components/images/image-with-caption.js
assets/javascripts/kitten/karl/images/image-with-caption.js

Fix `captionProps` prop warning to `ImageWithCaption`

---

CHANGELOG.md
assets/javascripts/kitten/components/form/text-input-with-button.js
assets/javascripts/kitten/components/form/text-input-with-button.test.js

PR qui fixe la possibilité d'écraser le type du bouton.

[Footer] Enable button type attribute override on TextInputWithButton

---

Gemfile
Gemfile.lock

Petit fix qui évite de devoir désinstaller `method_source` sur KissKissBankBank à chaque fois qu'on veut utiliser `zeus`.

Force version of `method_source` for example app

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card.js

Il y avait un problème de rendu au niveau du truncate qui affichait 3 lignes à la place de 2 souhaitées. C'est dû à la font qui se charge bien après le calcul de la place dispo.

[Browsing] Fix title truncate to CrowdfundingCard

---

Gemfile
Gemfile.lock
README.md
bin/start

Ajoute une commande `bin/start` à la racine du projet pour lancer l'app via `overmind`, sans avoir à rentrer dans le dossier `spec/dummy` puis faire `foreman start`.

Add bin/start command

---

CHANGELOG.md
assets/javascripts/kitten/components/form/checkbox.js
assets/javascripts/kitten/components/form/checkbox.test.js

PR qui permet de gérer les styles du texte présent dans une `Checkbox`.

[Browsing] Add textProps to Checkbox

---

CHANGELOG.md
assets/javascripts/kitten/components/form/checkbox.js

Corrige le warning indiquant que l'input du composant `CheckBox` ne reconnait pas la prop `textProps`.
Screenshot:
TODO:

Remove `textProps` props from `inputProps`

---

.storybook/stylesheets/app-kitten.scss

Pour que la grille colle bien l'iFrame de Storybook, il faut supprimer les marges par défaut sur le body.

[Tools] Remove Storybook iFrame margin

---

.storybook/preview-head.html
CHANGELOG.md
assets/javascripts/kitten/hoc/__snapshots__/media-queries.test.js.snap
assets/javascripts/kitten/hoc/media-queries.js

- Ajoute le `viewport` `S`. Permet de gérer l'état entre le mobile et la tablette.
TODO:

Create viewport `SOrLess`

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/horizontal-nav.js
assets/javascripts/kitten/components/navigation/horizontal-nav.test.js
assets/stylesheets/kitten/components/navigation/_horizontal-nav.scss

Actuellement, l'alignement vertical des items n'est pas centré quand on utilise la version avec `Markdown` et qu'on fixe une hauteur spécifique. Cette PR corrige l'alignement pour tous les cas et offre une option pour désactiver le rendu en markdown si on en a pas besoin.
Screenshot:

[ProjectPage] Fix `HorizontalNav` vertical alignment

---

CHANGELOG.md
assets/javascripts/kitten/components/form/text-input.js
assets/javascripts/kitten/components/form/text-input.test.js

Un bug a été introduit sur la PR suivante => https://github.com/KissKissBankBank/kitten/pull/1112/files#diff-d696025ce0725d2a8c40c18f5875074e
Pour la version `textarea` du `TextInput` le name n'était plus propagé :/

[AgricultureLanding] Fix `name` attribute on `TextInput` textarea version

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/backer-card.js

PR qui fixe un problème d'écrasement des styles de `BackerCard` quand la prop `style` est présente.

[ProjectPage] Don't erase styles in BackerCard component

---

CHANGELOG.md
assets/javascripts/kitten/helpers/utils/parser.js

Dans certain cas, on se retrouve à faire du `parseHtml` sur une valeur `null` voir `undefined`.
Ces valeurs sont ensuite transformées en string et `parseHtml` renvoi `"null"` ou `"undefined"`.
Si aucune valeur n'est passée en paramètre de `parseHtml`, celui-ci ne doit rien renvoyer.

Fix `parseHtml` helper when no value is passed as parameter

---

CHANGELOG.md
assets/javascripts/kitten/hoc/media-queries.js
assets/javascripts/kitten/hoc/media-queries.test.js

J'ai rajouté un `hoc` qu'on peut utiliser pour faire de la composition : `withMediaQueries`. L'autre est toujours utilisable mais il faudrait le déprécier à terme.
J'ai rajouté la possibilité de mettre un *viewport custom* du style : 
```javascript
export default compose(
connect(mapStateToProps),
withMediaQueries({
viewportIsMobile: true,
viewportIsTabletOrLess: true,
viewPortCustom: '(min-width: 1440px)',
}),
)(Navigation)
```
ça enverra la *prop* `viewPortCustom` dans le `Component` pour gérer ce *breakpoint*.

[MediaQueries] add withMediaQueries hoc and custom view port

---

README.md

On a une commande dans notre `package.json` pour déployer storybook sur [https://kisskissbankbank.github.io/kitten](https://kisskissbankbank.github.io/kitten)
On utilise la lib `storybook-to-ghpages` [comme ceci](https://github.com/KissKissBankBank/kitten/blob/e942a73b998f5799aa5fb1a3c9fd643e699b8fca/package.json#L108) 
Il suffit donc de lancer la commande `yarn deploy-storybook` sur `master`.
J'ai rajouté une section `Storybook` dans le `README.md` pour l'expliquer.

[Storybook] Add storybook section on README for release guide

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/carousel.js

Fix re-render `ButtonIcon` state on `Carousel`.

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/__snapshots__/carousel.test.js.snap
assets/javascripts/kitten/components/carousel/carousel-inner.js

Il est maintenant possible de changer de page en cliquant sur le container de la page d'avant/après visible sur tablette et mobile.

[Carousel] Add onClick method on prev/next page container

---

CHANGELOG.md
KARL_CHANGELOG.md
app/views/kitten/components/carousel/carousel.html.erb
assets/javascripts/kitten/components/carousel/carousel-inner.js
assets/javascripts/kitten/karl/carousel/carousel.js

Actuellement les cards dans les carrousels ne fonctionnent plus à cause d'un `preventDefault` qui s'applique à toutes les pages à la place d'être sur les pages avant/après.

[Carousel] Fix click on current page

---

CHANGELOG.md
assets/javascripts/kitten/components/modals/modal.js
package.json
yarn.lock

Mise à jour de la version de `ReactModal` qui corrige un problème de `unmount` quand c'est dans un `ReactPortal` \o/

[Modal] Update ReactModal

---

Gemfile
Gemfile.lock
KARL_CHANGELOG.md
kitten.gemspec
spec/dummy/client/package.json
spec/dummy/client/yarn.lock
spec/dummy/config/initializers/react_on_rails.rb
spec/dummy/yarn.lock
yarn.lock

Cette PR : 
- met à jour la gem `react_on_rails` sur la version `11.1.6`
- met à jour Rubocop
- met à jour l'initializer de `react_on_rails` (j'ai repris celui de KissKiss)
- met à jour le module npm `react_on_rails` sur la version `11.1.6`
- ajoute les clés d'intégrité sur tous les `yarn.lock`
En développement, tout a l'air de fonctionner en utilisant : `yarn build:dev && rails s`. Je pense que ça devrait être ok pour le déploiement du styleguide (s'il est réparé).

[KARL] Update React on Rails to 11.1.6

---

kitten.gemspec
spec/dummy/client/package.json

Les dépendances à la gem React on Rails et au module npm doivent se suivre. J'ai donc fixé la version dans le `kitten.gemspec` (comme ce qui est déjà le cas dans le `package.json`). J'en ai profité pour mettre la version qu'ils ont sorti hier.

[Stability] Update React on Rails

---

assets/javascripts/kitten/components/cards/reward-card.js

Cette PR permet de pouvoir passer des attributs de DOM à la balise racine du composant `RewardCard`. Entre-autre, cela permet sur KissKiss de pouvoir passer l'attribut `data-test-id`.
De manière générale, j'ai l'impression qu'on devrait pouvoir autoriser le spread operator sur les props restantes après assignation des props spécifiques sur les composants dont la "balise parent" est un élément de DOM (et non un composant React).
Je ne mets pas le `CHANGELOG` à jour car cela correspond toujours à la modification de l'intégration de la `RewardCard` mentionnée dans #1374.

[RewardCard] Enable props to spread on root tag

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/reward-card/action.js

Corrige une erreur JS quand il y a plusieurs enfants dans le `children` du composant `Deprecated`.
Closes https://github.com/KissKissBankBank/kitten/issues/1382

[Fix] <Deprecated /> needs only one children

---

CHANGELOG.md
assets/javascripts/kitten/components/expandable/__snapshots__/expand-board.test.js.snap
assets/javascripts/kitten/components/expandable/expand-board.js

Related to https://github.com/KissKissBankBank/kisskissbankbank/issues/5317.
Cette PR fixe : 
- **la distance entre le texte du bouton et la flèche**  
Avant : 
Après : 
- **le fait que la flèche rétrécisse lorsque l'espace disponible diminue**
Avant : 
Après :

[ProjectPage] Update ExpandBoard button styles

---

assets/stylesheets/kitten/components/form/_location-input.scss

La couleur du disabled location input était incorrecte. 
Avant
Après

Fix color values for disabled location input

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/marger.js
assets/javascripts/kitten/components/layout/marger.test.js

Related to #1419.
Avec #1419, la gestion de la valeur par défaut (pour `default` ou `fromXxs`) se gérait de la manière suivante avec Radium : 
```js
<Marger top={ {
default: 6,
fromS: 10,
} } />
```
Je n'ai pas pris en compte la manière dont Radium gère les styles. Cela rendait donc un DOM avec la structure suivante : 
L'attribut `style` étant inline, il a la précédence sur le style par rapport à la classe déclarée pour le noeud DOM. **On ne rentre donc jamais dans les media-queries ಠ_ಠ**. C'est bête, hein.
La PR propose du coup un petit trick en utilisant une media-query `min-width: 0` pour pallier ce souci de précédence.

[Performance] Use media-query for default value on `Marger`

---

bin/publish

Après le clean des tags (qui est en cours en ce moment même)

No need to add suffix -next for our releases anymore

---

CHANGELOG.md
assets/javascripts/kitten/components/icons/burger-icon/__snapshots__/burger-icon.test.js.snap
assets/javascripts/kitten/components/icons/burger-icon/index.js

Le `hover` s'appliquait aux éléments intérieurs au SVG, maintenant il s'applique au SVG en entier.

Fix `BurgerIcon` : new `hover` behaviour

---

CHANGELOG.md
assets/javascripts/kitten/components/meters/counter-block.js

Suite de la `PR`(https://github.com/KissKissBankBank/kkbb-lendopolis-clients/pull/704), qui supprime le `title` du composant `CounterBlock` sur Lendo. 
Sur le composant `CounterBlock` de kitten, une marge s'affichait même si le `title` était vide.
J'ai donc ajouté une condition sur la marge associée à cette props, pour éviter que la marge s'affiche quand le `title` n'est pas spécifié.
Screenshot:
TODO:

Remove margin when `title` prop is empty on `CounterBlock` component.

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button-question-mark-icon.js
assets/javascripts/kitten/components/buttons/button-question-mark-icon.test.js
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
src/components/buttons/button-question-mark-icon.js

Si on ne spécifie ps le type d'un bouton dans un formulaire, certains navigateurs (chrome) mettent la valeur `type` à `submit` par défaut. Ce qui est dommage. Sur shipping-address quand on clique sur l'icône on submit le formulaire !

Specify type button for button-question-mark-icon

---

CHANGELOG.md
assets/javascripts/kitten/components/form/select-with-state.js
assets/javascripts/kitten/components/form/select-with-state.test.js
assets/javascripts/kitten/karl/pages/contribute/payment-choices/components/payment-choices.js
package-lock.json

PR qui va permettre de gérer l'autofill des champs month et year de la carte de crédit.
j'ai besoin d'un input pour avoir les valeurs par le navigateur. Input que je dois pour l'instant cacher à l'utilisateur... sans utiliser `display: none` ( ce serait trop facile). Du coup j'ai fait un petit tour de passe-passe qui semble fonctionner... Dites moi si vous avez mieux !

[Feature] Add autoFill prop to Select

---

README.md

Suite au stand-by du styleguide, cette PR supprime les occurrences de `KARL_CHANGELOG` dans le README.

[Tech] Remove KARL_CHANGELOG notifications in README

---

CHANGELOG.md
assets/javascripts/kitten/components/form/select-with-state.js
assets/javascripts/kitten/components/form/select-with-state.test.js

[Fix] Remove test warnings on `SelectWithState` for `htmlFor` and `autoComplete` props

---

CHANGELOG.md
assets/javascripts/kitten/components/steppers/vertical-stepper/components/step.js
src/components/steppers/vertical-stepper/components/step.js

Le `href` n'est plus requis sur `VerticalStepper.Step`.

[VerticalStepper] Fix Step warning

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/nav-tab-carousel/__snapshots__/nav-tab-carousel.test.js.snap
assets/javascripts/kitten/components/carousel/nav-tab-carousel/components/styled-components.js
assets/javascripts/kitten/components/carousel/nav-tab-carousel/index.js
assets/javascripts/kitten/components/carousel/nav-tab-carousel/stories.js
package-lock.json

Dans le cas ou le composant n'a que 2 liens, au lieu de 3, on a besoin de masquer soit le lien précédent. Pour conserver le centrage des puces de navigation, il faut donc créer un container vide.
Cas avec aucun lien précédent :
Cas avec aucun lien suivant :

[NavTabCarousel] Add empty `Prev` and `Next` container to `NavTabCarousel` when   `NavTabCarousel.Prev` or `NavTabCarousel.Next` are empty

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button/stories.js
assets/javascripts/kitten/components/icons/cart.js
assets/javascripts/kitten/components/notifications/__snapshots__/badge.test.js.snap
assets/javascripts/kitten/components/notifications/badge.js
assets/javascripts/kitten/components/notifications/badge.test.js

Permet de pouvoir ajouter un icon au badge pour pouvoir faire un truc du genre :

Feature Add badge with icon

---

CHANGELOG.md
assets/javascripts/kitten/components/details/__snapshots__/test.js.snap
assets/javascripts/kitten/components/details/index.js
assets/javascripts/kitten/components/details/stories.js
package-lock.json
src/components/details/index.js

La prop `open` n'était pas attachée à la balise `details`… ce qui rendait la prop … inutile.

[Details] Fix `open` prop propagation

---

CHANGELOG.md
assets/javascripts/kitten/components/lists/list/components/button-item.js

Une erreur HTML apparait quand le `role={ false }`, ce n'est pas valide.

[List] Remove a HTML warning on `List.ButtonItem`

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button-group/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button/button.js
assets/javascripts/kitten/components/cards/reward-edition/__snapshots__/test.js.snap

[Fix] IE11 Button height compatibility fix

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/simple-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/simple-card/components/image.js
assets/javascripts/kitten/components/cards/simple-card/index.js
assets/javascripts/kitten/components/cards/simple-card/stories.js

Cette PR permettra de spécifier un ratio aux images des `SimpleCard`, pour améliorer le rendu du LazyLoad.
Closes #.
Screenshot:
TODO:

[SimpleCard] Add `imageContainerBackground` and `imageContainerRatio` to image container

---

CHANGELOG.md
assets/javascripts/kitten/components/comments/comment/__snapshots__/test.js.snap
assets/javascripts/kitten/components/comments/comment/index.js
assets/javascripts/kitten/components/comments/comment/stories.js

PR qui supprime ce genre de warnings.

[Comment] Remove HTML warning to `Comment`

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/components/error.js

[Field] Provide props to `Error` subcomponent

---

CHANGELOG.md
assets/javascripts/kitten/components/comments/comment/__snapshots__/test.js.snap
assets/javascripts/kitten/components/comments/comment/components/like-button.js

Ajoute les styles des pseudo-classes `hover/focus/…` seulement si c'est un lien ou qu'il y a un `onClick` sur le bouton.

[Comments] Add like button event styles only when an event is attached

---

assets/javascripts/kitten/components/icons/export-icon/index.js

Fix `title` defaultProps on `ExportIcon` component

---

CHANGELOG.md
assets/javascripts/kitten/components/text-copy/__snapshots__/test.js.snap
assets/javascripts/kitten/components/text-copy/index.js
assets/javascripts/kitten/components/text-copy/stories.js
assets/javascripts/kitten/components/text-copy/test.js

Permet de forcer le texte à ne s'affiche que sur une seule ligne comme ceci :

Add forceOneLine prop to TextCopy component.

---

CHANGELOG.md
assets/javascripts/kitten/components/form/text-input-with-unit/index.js
assets/javascripts/kitten/components/form/text-input/index.js
src/components/form/text-input-with-unit/index.js
src/components/form/text-input/index.js

Corrige le bug sur Lendo qui ne retrouvait plus les refs des input..

Add old input refs on text-input

---

CHANGELOG.md
assets/javascripts/kitten/components/text-copy/__snapshots__/test.js.snap
assets/javascripts/kitten/components/text-copy/index.js
src/components/text-copy/index.js

Petite update du comportement de composant `Textcopy` pour ne sélectionner que le texte quand on clique dessus. Le clique sur l'icon copie le texte directement dans le clipboard.

Clicking on TextCopy input just select the text (no copy)

---

CHANGELOG.md
assets/javascripts/kitten/components/modals/modal/index.js

[Modal] Remove `PropType`-related warning in tests

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/adaptable-grid/__snapshots__/test.js.snap
assets/javascripts/kitten/components/grid/adaptable-grid/index.js
assets/javascripts/kitten/components/grid/adaptable-grid/test.js

Afin de pouvoir ajouter des styles sur `AdaptableGrid` et `AdaptableGridCol` avec `styled-components`, j'ajoute la propagation de la prop `className`. Ne sachant pas comment le composant a été pensé à l'origine, je préfère scoper le passage de cette prop uniquement et pas de tout le `...others`.
Pour pouvoir faire ça correctement par exemple (car aujourd'hui, ça ne pourrait pas fonctionner) : 
```js
const StyledGrid = styled(AdaptableGrid)`
color: red;
`
```

[AdaptableGrid] Pass className prop to enable styling

---

CHANGELOG.md
assets/javascripts/kitten/components/comments/comment-form/__snapshots__/test.js.snap
assets/javascripts/kitten/components/comments/comment-form/index.js
assets/javascripts/kitten/components/comments/comment-form/stories.js
assets/javascripts/kitten/components/comments/comment-form/test.js
src/components/comments/comment-form/index.js

Possibilité d'ajouter un ID sur le `textarea` pour permettre de le sélectionner en JS.
Ce qui a déclenché le dev : permettre l'auto-focus du formulaire d'ajout d'un commentaire.
J'en ai profité pour virer du code mort lié au focus qu'il restait suite à la migration Radium > styled-components.

[CommentForm] Add `textareaId` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/icons/icons.stories.js
assets/javascripts/kitten/components/icons/stroke-icon/index.js

[Icon] Create `StrokeIcon` component.

---

CHANGELOG.md
assets/javascripts/kitten/components/form/autocomplete/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/autocomplete/index.js
assets/javascripts/kitten/components/form/autocomplete/stories.js
assets/javascripts/kitten/components/form/autocomplete/test.js

Ajout de la prop `isLoading` au composant `<Autocomplete />` pour un résultat comme ceci :

Add isLoading prop to <Autocomplete/>

---

CHANGELOG.md
assets/javascripts/kitten/components/form/autocomplete/index.js
assets/javascripts/kitten/components/form/autocomplete/stories.js

Donne les outils pour gérer un message s'il n'y a aucun résultat avec les props  `noResultMessage` et `shouldShowNoResultMessage`

Error message on  <Autocomplete />

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/field/components/autocomplete.js
assets/javascripts/kitten/components/form/field/components/input.js
assets/javascripts/kitten/components/form/field/components/label.js
assets/javascripts/kitten/components/form/field/components/password.js
assets/javascripts/kitten/components/form/field/components/radio-button-set.js
assets/javascripts/kitten/components/form/field/components/select.js
assets/javascripts/kitten/components/form/field/field.examples.js
assets/javascripts/kitten/components/form/field/field.stories.js
assets/javascripts/kitten/components/form/field/field.test.js

- Passe `micro` comme taille par défaut sur le `label`
- Réduit les marges entre le label et l'input
- Ajoute la props `tiny` sur les examples, stories et tests de `field`
Closes #https://app.clickup.com/t/ve5y5
TODO:

[Field] Cleanup Input styles

---

CHANGELOG.md
assets/javascripts/kitten/components/popovers/simple-popover/__snapshots__/test.js.snap
assets/javascripts/kitten/components/popovers/simple-popover/index.js
assets/javascripts/kitten/components/popovers/simple-popover/stories.js
assets/javascripts/kitten/components/popovers/simple-popover/test.js
assets/javascripts/kitten/components/tours/highlight-halo/stories.js
assets/javascripts/kitten/index.js
src/components/cards/crowdfunding-card/components/title.js

Closes #.
All the open/close mechanics are left for the parent component.
Most of the styling code has been done by @camilledel, thanks 🎉
Screenshot:
TODO:

[Popover] Add `SimplePopover` component

---

CHANGELOG.md
assets/javascripts/kitten/components/meters/progress/index.js

[Progress] Allow `value` to be a `string`

---

CHANGELOG.md
assets/javascripts/kitten/components/comments/comment/index.js

Propage la prop `id` passée au composant `Comment` jusqu'au DOM. Lié à https://github.com/KissKissBankBank/kisskissbankbank/pull/8276

[Comments] Add id prop to comments

---

CHANGELOG.md
assets/javascripts/kitten/components/modals/modal/index.js
assets/stylesheets/kitten/components/modals/modal.scss

[Modal] Remove Margin on `Modal__close` button

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/carousel/carousel.js

- Expose la méthode `goToPage` qui permet de se rendre sur n'importe quelle page en dehors du composant

[Carousel] Expose `goToPage` method

---

CHANGELOG.md
assets/javascripts/kitten/components/notifications/alert.js

- Ajout des propTypes
- Ajout d'une valeur par défaut pour `onAfterClose`

[Alert] Fix onAfterClose error

---

CHANGELOG.md
assets/javascripts/kitten/components/icons/icons.stories.js
assets/javascripts/kitten/components/icons/paragraph-icon/index.js

- Ajout du composant `ParagraphIcon`

[Editor] Add `ParagraphIcon` component

---

.storybook/decorators/grid.js
.storybook/main.js
.storybook/webpack.config.js
CHANGELOG.md
assets/javascripts/kitten/components/modals/next/Modal.stories.js
assets/javascripts/kitten/components/modals/next/index.js
assets/javascripts/kitten/components/modals/next/stories.js
assets/javascripts/kitten/next/index.js
package-lock.json
package.json

Création d'une "nouvelle" Popin répondant aux standards de la maquette 
https://app.abstract.com/projects/67e5bf40-6a62-11e9-ab92-01fc018ad3a7/branches/5dadd0c8-ffc2-4ba4-8a1c-a56ed3337c66/commits/e4842c2996f717c579575515361299fc489f335d/files/D681D1DD-7F19-4397-954C-78509DA47F6A/layers/DDABE5C6-17A7-4EF0-80F8-04BA9088FAC6
Avec une API restreinte qui laisse deux choix dans la gestion de celle-ci : 
Via un trigger.
Via la prop `isOpen`
J'ai l'impression que ça couvre tous les cas qu'on a.
J'ai mis la gestion du Portal directement dans la Modal. Du coup je ne peux pas faire de test facilement : https://github.com/facebook/react/issues/11565
La gestion du responsive est gérée en `grid`. Ça donne des calculs un peu exotiques. @joachimesque va se pencher sur des helpers.
J'ai fait un peu de …

Next Modal

---

CHANGELOG.md
assets/javascripts/kitten/components/form/toggle-switch/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/toggle-switch/index.js
assets/javascripts/kitten/components/form/toggle-switch/stories.js
assets/javascripts/kitten/components/form/toggle-switch/test.js

- Ajout de la prop `locked` qui permet de disabled le switch en ajoutant un petit cadenas
- Utilisation de la dernières syntaxe pour la story
- Update des tests/story

[ToggleSwitch] Add locked prop

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/reward-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/reward-card/components/title.js
assets/javascripts/kitten/components/cards/reward-card/styles.js

[RewardCardTitle] Replace `Title` component by `TitleWithStroke` 

---

CHANGELOG.md
assets/javascripts/kitten/helpers/utils/parser.js
assets/javascripts/kitten/helpers/utils/parser.test.js
src/helpers/utils/parser.js

Permet de fixer le crash lorsqu'un `string` contient un `<3` (genre `Merci <3 !`)

Making `parseHtml` to work with `<3`

---

CHANGELOG.md
assets/javascripts/kitten/components/modals/next/Modal.stories.js
assets/javascripts/kitten/components/modals/next/index.js

Gestion `fullSize` de la modale `next` en se basant sur l'exemple ici : https://app.abstract.com/projects/6e9b6c3e-f67d-4831-b5ba-66caa5a524fe/branches/1a560145-95e1-4812-8ff3-364c87d4caed/commits/76563444fc3d308816441767681c07cb33aa498c/files/60B214CA-457A-4EF6-A64E-D419824C4C66/layers/39CAA2E4-15D3-4C5E-91F2-C0374450F6BC?mode=build&selected=root-FC0F05B2-E0D2-421D-92B9-E4A9BE18A71E
closes #2098

Create modal full size

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/header-nav/components/centered.js

[Header] Remove console error from `Centered` component

---

CHANGELOG.md
assets/javascripts/kitten/helpers/utils/parser.js

Cette portion du code `value.replace('<3', '&lt;3')` casse la fonction `parseHtml` lorsque `value` n'est pas une `string`.

[parseHtml] Fix parseHtml error

---

assets/javascripts/kitten/components/images/image-cropper/index.js

Firefox et Chrome utilisent des éléments différents pour le `EventTarget` du crop…

Fix cropper

---

CHANGELOG.md
assets/javascripts/kitten/components/notifications/__snapshots__/alert.test.js.snap
assets/javascripts/kitten/components/notifications/alert.js

Je ne sais pas exactement pourquoi mais mettre le `flex-basis` à `auto` ne faisait pas revenir à la ligne les longs textes. En mettant `0` c'est bon !

[Alert] Set flex-basis to 0

---

.storybook/main.js

Pour la version buildée de Storybook, le fichier des styles `scss` n'était pas pris en compte. Il devait y avoir conflit entre tous les Kitten (src/esm/es6…).

[Storybook] Use sideEffect option

---

CHANGELOG.md
assets/javascripts/kitten/components/form/dropdown-phone-select/dropdown-phone-select.stories.js
assets/javascripts/kitten/components/form/dropdown-phone-select/index.js

Quand il n'y avait pas de `value` définie sur le composant, le `getInputNumber` était `null` et faisait planter le premier passage dans le `handleInput`.

Fix dropdown undefined value

---

CHANGELOG.md
assets/javascripts/kitten/components/steppers/vertical-stepper/__snapshots__/test.js.snap
assets/javascripts/kitten/components/steppers/vertical-stepper/components/status.js
assets/javascripts/kitten/components/steppers/vertical-stepper/components/step.js
assets/javascripts/kitten/components/steppers/vertical-stepper/stories.js

- Mise à jour de la props `error` quand on utilise `variant="orion".
Screenshot:
TODO:

[VerticalStepper] Update `error` props

---

CHANGELOG.md
assets/javascripts/kitten/components/form/credit-card-form/components/number.js
assets/javascripts/kitten/components/form/credit-card-form/index.js

- Remonte le type de la carte de crédit dans les valeurs du `onChange`

[CreditCardForm] Add type to values

---

CHANGELOG.md
assets/javascripts/kitten/components/steppers/vertical-stepper/__snapshots__/test.js.snap
assets/javascripts/kitten/components/steppers/vertical-stepper/components/step.js
assets/javascripts/kitten/components/steppers/vertical-stepper/stories.js

- Supprime l'animation quand le state est `disabled`.
- Réduit le `padding` de l'élément de transition (entre l'étape 2 et 3)
Screenshot:
TODO:

[VerticalStepper] Fix styles

---

CHANGELOG.md
assets/javascripts/kitten/components/form/dropdown-select/combobox.js
assets/javascripts/kitten/components/form/dropdown-select/dropdown-select.stories.js
assets/javascripts/kitten/components/form/dropdown-select/index.js

Ajout d'une prop qui permet de forcer l'affichage unique de chaque label.
Ça servirait pour les pays, on a deux fois la France dans la liste mais quand on fait la recherche on aimerait ne l'afficher qu'une seule fois.

[DropDown] Add `uniqLabelOnSearch` prop on `Dropdown`

---

CHANGELOG.md
assets/javascripts/kitten/components/form/text-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input/index.js
assets/javascripts/kitten/components/form/text-input/test.js

Quand on est en mode `tag="textarea"` le `name` n'était pas propagé dans le DOM. Sans conséquence car Formik n'en a pas forcement besoin mais en terme de validité HTML, on est pas bon.

[TextInput] Propagate `name` argument when `TextInput` is a textarea

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/horizontal-stroke/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/horizontal-stroke/index.js
assets/javascripts/kitten/components/layout/horizontal-stroke/test.js

[HorizontalStroke] Allow `string` prop types on customSize

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/reward-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/reward-card/index.js
assets/javascripts/kitten/components/cards/reward-card/legacy/reward-card-container.js
assets/javascripts/kitten/components/cards/reward-card/test.js

[RewardCard] Return `className` prop transmission to `RewardCard`

---

CHANGELOG.md
assets/javascripts/kitten/components/form/dropdown-phone-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select-with-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select-with-input/dropdown-select.stories.js
assets/javascripts/kitten/components/form/dropdown-select-with-input/index.js

Closes #.
Vercel link:
- https://kitten-git-dropdown-select-with-input-fix-modal-styles.kisskissbankbank.vercel.app/?path=/story/form-dropdownselectwithinput--default
- https://kitten-git-dropdown-select-with-input-fix-modal-styles.kisskissbankbank.vercel.app/?path=/story/form-dropdownselectwithinput--deactivated-dropdown
Screenshot:
TODO:

[DropdownSelectWithInput] mobile style fixes

---

CHANGELOG.md
assets/javascripts/kitten/components/steppers/vertical-stepper/components/step.js

On ne propage la prop `onClick` si la step est `disabled`. Ça évite d'appliquer des styles non voulu.

[VerticalStepper] No onClick handler when disabled

---

CHANGELOG.md
assets/javascripts/kitten/components/form/dropdown-select/combobox.js
assets/javascripts/kitten/components/form/dropdown-select/dropdown-select.stories.js

Je change le système de filtrage pour qu'on prenne en compte le `label` (visible par l'user) et non la `value` (utile pour l'API).
Ça provoquait un bug côté KissKiss pour les pays qui sont du format `{ value : 'FR', label: 'France'}`.
A partir du moment où l'on tapait 'Fra', on n'avait plus rien en résultat car `'FR'.startsWith('Fra')`renvoie `false`.
Je pense que c'est juste une petite erreur lors de la création du composant, sur les *stories* ça ne posait pas de problèmes car nos `values` === `label`.
Je ne vois pas dans quels cas d'usage on voudrait filtrer par les `values` mais je me trompe peut-être de diagnostique. @joachimesque, @LanF3usT vous en pensez quoi ?

[Combobox] Filter on label instead of value

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
assets/javascripts/kitten/components/carousel/carousel/components/carousel-inner.js
assets/javascripts/kitten/components/carousel/carousel/index.js
assets/javascripts/kitten/components/carousel/carousel/project-carousel.stories.js
assets/javascripts/kitten/components/carousel/carousel/styles.js

Lors de l'ajout d'un `outline` et d'un `outline-offset` à valeur positive sur les cards, il a fallu compenser au niveau des pages (padding positif) et du conteneur intérieur (margins négatifs). Tous les calculs n'avaient pas été bien faits sur les gouttières, ce qui faisait une mauvaise dimension calculée par le JS, et un bug dans Safari Mobile dans certains cas.
Closes #.
Vercel link:
- https://kitten-git-carousel-fix-margin-calculations.kisskissbankbank.vercel.app/?path=/story/carousels-carousel-projectcarousel--default
Screenshot:
TODO:

[Carousel] Fix spacing calculations

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/backing-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/backing-card/stories.js
assets/javascripts/kitten/components/cards/backing-card/styles.js
assets/javascripts/kitten/components/cards/backing-card/test.js
assets/javascripts/kitten/constants/colors-config.js
doc/design/colors.js

Closes #.
Vercel link:
- https://kitten-git-backing-card-add-hover-styles.kisskissbankbank.vercel.app/?path=/story/cards-backingcard--in-a-carousel-component
Screenshot:
TODO:

[BackingCard] Add `hover` styles

---

CHANGELOG.md
assets/javascripts/kitten/components/atoms/tag/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/backing-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/tooltips/toggletip/__snapshots__/test.js.snap
assets/javascripts/kitten/components/tooltips/toggletip/index.js
assets/javascripts/kitten/components/tooltips/toggletip/stories.js
assets/javascripts/kitten/components/tooltips/toggletip/test.js
assets/javascripts/kitten/components/tooltips/tooltip/tooltip.stories.js
assets/javascripts/kitten/constants/colors-config.js
assets/javascripts/kitten/index.js

Closes #.
- Création du composant `Toggletip`
- prop `modifier` acceptant les valeurs **'info'**, 'warning', 'error', 'success', 'disabled'
Vercel link:
- https://kitten-git-tooltips-tooltip-next.kisskissbankbank.vercel.app/?path=/story/tooltips-toggletip--default
- https://kitten-git-tooltips-tooltip-next.kisskissbankbank.vercel.app/?path=/story/tooltips-toggletip--multiple-toggletips
Basé sur : https://inclusive-components.design/tooltips-toggletips/
TODO:

[Toggletip] New component

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/checkable-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/checkable-button/index.js

Closes #.
Vercel link:
- https://kitten-git-a11y-fix-checkable-button-focus-style-e7956b.vercel.app/?path=/story/buttons-checkable-button--is-checkable
Screenshot:
TODO:

[CheckableButton] Fix focus styles

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/header-nav/index.js
assets/stylesheets/kitten/components/navigation/_header-nav.scss

Closes #.
Vercel link:
Screenshot:
TODO:

[HeaderNav] Fix StickyContainer width

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/header-nav/index.js
assets/javascripts/kitten/components/navigation/header-nav/stories.js
assets/javascripts/kitten/components/navigation/header-nav/stories/lendopolis.js

Closes #.
Vercel link:
- https://kitten-git-fix-header-nav-kisskissbankbank.vercel.app/?path=/story/navigation-headernav--lendopolis
Screenshot:
TODO:

[HeaderNav] Allow for null value on stickyProps

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/carousel/components/carousel-inner.js
src/components/carousel/carousel/components/carousel-inner.js
src/esm/components/carousel/carousel/components/carousel-inner.js

L'utilisation du state sur le `isTouched` causait une cascade de rerender qui faisait freeze le navigateur.
Le bug n'était reproductible que sur des devices mobiles (prise en compte des `onTouchStart
` et `onTouchEnd
`
Comme le `isTouched` n'était pas nécessaire pour le render, j'ai juste créé une variable pour sauvegarder la valeur utilisée par le callback `handleInnerScroll`

Fix carousel perf issue

---

CHANGELOG.md
assets/javascripts/kitten/helpers/utils/lazy-hook.js
src/esm/helpers/utils/lazy-hook.js
src/helpers/utils/lazy-hook.js

- S'assure de récupérer la ref avec l'élément dans le `useEffect`

Fix ref element

---

CHANGELOG.md
assets/javascripts/kitten/components/tables/double-entry-table/__snapshots__/test.js.snap
assets/javascripts/kitten/components/tables/double-entry-table/index.js
assets/javascripts/kitten/components/tables/double-entry-table/test.js
assets/javascripts/kitten/components/tables/single-entry-table/__snapshots__/test.js.snap
assets/javascripts/kitten/components/tables/single-entry-table/index.js
assets/javascripts/kitten/components/tables/single-entry-table/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Tables] Fix classNames on SingleEntryTable and DoubleEntryTable 

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/header-nav/styles.js

Closes #.
Vercel link:
- Ouvrir dans Chrome : https://kitten-git-v3-header-navfix-user-menu-button-ali-2effe9.vercel.app/iframe.html?id=navigation-headernav--kiss-kiss-bank-bank&knob-Is%20logged=true&viewMode=story
Screenshot:
TODO:

[HeaderNav] Fix `UserMenuButton` alignment on Chrome

---

assets/javascripts/kitten/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[KittenV3] Fix `getScssPaths` import

---

package.json

Je remets l'étape `npm install` pour éviter des surprises

set back npm install before I run storybook

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/carousel/components/carousel-inner.js
assets/javascripts/kitten/components/carousel/carousel/project-carousel.stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[KittenV3] fix Carousel resize observer

---

CHANGELOG.md
package.json

La version `2.1.6` corrigeait le bug sur Storybook mais pas sur KissKiss… En testant avec la version `2.1.1` le bug est corrigé sur KissKiss. Aucune idée de pourquoi 🤷‍♂️

rollback-cropper

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/flow/index.js
assets/javascripts/kitten/components/layout/dashboard-layout/stories.js

Closes #.
Vercel link:
- https://kitten-git-dashboard-layout-full-size-flow-nav-b-896edc.vercel.app/?path=/story/layout-dashboardlayout--default
- https://kitten-git-dashboard-layout-full-size-flow-nav-b-896edc.vercel.app/?path=/story/layout-dashboardlayout--flow
Screenshot:
TODO:

[DashboardLayout] Set lone `Flow.Nav` button full size

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/components/input.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Field.Input] Recover missing props on Field.Input

---

CHANGELOG.md
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/combobox.test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/combobox.js
assets/javascripts/kitten/components/form/dropdown-select/index.js
assets/javascripts/kitten/components/form/dropdown-select/styles.js

Closes #.
Vercel link:
- https://kitten-git-dropdown-select-add-full-options-on-o-1520bf.vercel.app/?path=/story/form-dropdownselect--default
Screenshot:
TODO:

[DropdownSelect] Add full options list on menu open

---

CHANGELOG.md
assets/javascripts/kitten/components/form/text-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input/index.js
assets/javascripts/kitten/components/form/text-input/test.js

Corrige l'erreur de style sur la variant `orion` quand on a `type="textarea"`
Vercel link:
Screenshot:
TODO:

[TextInput] Update style type="textarea" with Orion variant

---

CHANGELOG.md
assets/javascripts/kitten/components/modals/modal/stories.js
assets/javascripts/kitten/components/modals/next/Modal.stories.js
assets/javascripts/kitten/components/modals/next/index.js

Closes #.
Vercel link:
- https://kitten-git-modal-next-add-orion-variant-kisskissbankbank.vercel.app/?path=/story/modals-modal-next--complex-with-orion
Screenshot:
TODO:

[Modal/Next] Add Orion variant and subcomponents

---

CHANGELOG.md
assets/javascripts/kitten/components/modals/next/Modal.stories.js
assets/javascripts/kitten/components/modals/next/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ModalNext] Add `contentCols` prop.

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/index.js

Closes #.
Vercel link:
- https://kitten-git-dashboard-layout-use-margin-custom-pr-579e89.vercel.app/?path=/story/layout-dashboardlayout--default
- 
Screenshot:
TODO:

[DashboardLayout] Use common CSS property for content margin

---

CHANGELOG.md
assets/javascripts/kitten/components/modals/next/Modal.stories.js
assets/javascripts/kitten/components/modals/next/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Modal/Next] Fix negative margin for Modal.Block at XL

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DashboardLayout] Add background color to `DashboardLayout`

---

CHANGELOG.md
assets/javascripts/kitten/components/form/dropdown-phone-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select-with-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select-with-input/index.js
assets/javascripts/kitten/components/form/text-input/text-input.stories.mdx

Closes #.
Vercel link:
Screenshot:
TODO:

[DropdownSelectWithInput] Fix input padding

---

CHANGELOG.md
assets/javascripts/kitten/components/menus/header-menu/__snapshots__/test.js.snap
assets/javascripts/kitten/components/menus/header-menu/components/item.js
assets/javascripts/kitten/components/menus/header-menu/stories.js
assets/javascripts/kitten/components/menus/header-menu/styles.js
assets/javascripts/kitten/components/menus/header-menu/test.js

Closes #.
Vercel link:
- https://kitten-git-header-menu-item-add-as-prop-kisskissbankbank.vercel.app/?path=/story/menus-headermenu--default
Screenshot:
TODO:

[HeaderNav] Add `as` prop to `HeaderNav.Item`

---

CHANGELOG.md
assets/javascripts/kitten/components/modals/next/Modal.stories.js
assets/javascripts/kitten/components/modals/next/index.js

Closes #.
Vercel link:
- https://kitten-git-modal-next-add-sticky-mobile-action-kisskissbankbank.vercel.app/?path=/story/modals-modal-next--default
Screenshot:
TODO:

[Modal/Next] Add `sticky` and `fullSize` props on Actions

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button/button.stories.js
assets/javascripts/kitten/components/buttons/button/button.stories.mdx
assets/javascripts/kitten/components/buttons/button/helpers/modifier-styles.js
assets/javascripts/kitten/components/buttons/button/index.js
assets/javascripts/kitten/components/cards/vertical-card-with-action/vertical-card-with-action.stories.js
assets/javascripts/kitten/components/menus/header-menu/components/item.js

Closes #.
Vercel link:
- https://kitten-git-feature-button-neon-kisskissbankbank.vercel.app/?path=/story/buttons-button--with-text
Screenshot:
TODO:

[Button] Add neon modifier

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/index.js
assets/javascripts/kitten/components/layout/dashboard-layout/stories.js
assets/javascripts/kitten/components/layout/dashboard-layout/test.js

Closes #.
Vercel link:
- https://kitten-git-dashboard-layout-add-alerts-kisskissbankbank.vercel.app/?path=/story/layout-dashboardlayout--default < Knob "Display Alert"
Screenshot:
TODO:

[DashboardLayout] Add Alert subcomponent

---

CHANGELOG.md
assets/javascripts/kitten/components/menus/dashboard-menu/__snapshots__/test.js.snap
assets/javascripts/kitten/components/menus/dashboard-menu/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DashboardMenu] Fix list items spacing

---

CHANGELOG.md
assets/javascripts/kitten/components/date-picker/__snapshots__/date-picker.test.js.snap
assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/field/field.stories.js
assets/javascripts/kitten/components/form/password-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-limit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-limit/text-input-with-limit.stories.js
assets/javascripts/kitten/components/form/text-input-with-unit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input/index.js

Closes #.
Vercel link:
- https://kitten-git-text-input-fix-textarea-padding-kisskissbankbank.vercel.app/?path=/story/form-creditcardform--with-custom-components
- https://kitten-git-text-input-fix-textarea-padding-kisskissbankbank.vercel.app/?path=/story/form-field--with-input
- https://kitten-git-text-input-fix-textarea-padding-kisskissbankbank.vercel.app/?path=/story/form-passwordinput--default
- https://kitten-git-text-input-fix-textarea-padding-kisskissbankbank.vercel.app/?path=/story/form-textinputwithbutton--default
- https://kitten-git-text-input-fix-textarea-padding-kisskissbankbank.vercel.app/?path=/story/form-textinputwithicon--default
- https://kitten-git-text-input-fix-textarea-padding-kisskissbankbank.vercel.app/?path=/story/form-textinputwithlimit--default
- …

[TextInput] Fix textarea padding

---

CHANGELOG.md
assets/javascripts/kitten/components/menus/dashboard-menu/__snapshots__/test.js.snap
assets/javascripts/kitten/components/menus/dashboard-menu/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DashboardMenu] Fix expandable list padding

---

CHANGELOG.md
assets/javascripts/kitten/components/images/image-cropper/__snapshots__/test.js.snap
assets/javascripts/kitten/components/images/image-cropper/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ImageCropper] Use default Label size

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/field.examples.js
assets/javascripts/kitten/components/form/field/field.stories.js
assets/javascripts/kitten/components/form/text-input-with-unit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-unit/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[TextInputWithUnit] Fix `variant` propagation

---

assets/javascripts/kitten/components/date-picker/__snapshots__/date-picker.test.js.snap
assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/field/field.stories.js
assets/javascripts/kitten/components/form/password-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-limit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-unit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input/index.js

Cette PR complète la dernière PR unreleased (https://github.com/KissKissBankBank/kitten/commit/292a50a090be217b0f268cd1ccf307368237b84f)
Closes #.
Vercel link:
Screenshot:
TODO:

[TextInputWithUnit] Fix `variant` propagation (leftovers)

---

CHANGELOG.md
assets/javascripts/kitten/components/text-copy/__snapshots__/test.js.snap
assets/javascripts/kitten/components/text-copy/index.js
assets/javascripts/kitten/components/text-copy/stories.js
assets/javascripts/kitten/components/text-copy/test.js

Closes #.
Vercel link:
- https://kitten-git-text-copy-refactor-and-variant-kisskissbankbank.vercel.app/iframe.html?id=textcopy-textcopy--default&args=&knob-alertMessage=Copied%20link%20!&knob-buttonText=Je%20suis%20button%20!&knob-variant=orion&knob-Text=My%20text%20to%20copy%20on%20click&viewMode=story
Screenshot:
TODO:

[TextCopy] Add `variant` prop, defaults to 'andromeda'

---

CHANGELOG.md
assets/javascripts/kitten/components/images/image-cropper/__snapshots__/test.js.snap
assets/javascripts/kitten/components/images/image-cropper/index.js

Correctifs sur Cropper : 
* suppression d'une boucle infinie générée par un `useEffect`
* `.reset()` de la `cropperInstance` à chaque nouvel upload
* ajout de la prop `onUpload`

[ImageCropper] Several fixes on Cropper + add onUpload prop

---

CHANGELOG.md
assets/javascripts/kitten/components/date-picker/__snapshots__/date-picker.test.js.snap
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/text-input-with-unit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-unit/index.js

Closes #.
Vercel link:
- https://kitten-git-text-input-with-unit-fix-reg-8eafca-kisskissbankbank.vercel.app/?path=/story/form-textinputwithunit--default
Screenshot:
TODO:

[TextInputWithUnit] Fix disabled state and unitWord styles

---

doc/introduction/introduction.stories.mdx

Closes #.
Vercel link:
Screenshot:
TODO:

[Doc] Add current package version on Intro text

---

.storybook/main.js
package-lock.json
package.json

Add storybook addon measure, for debug css
https://user-images.githubusercontent.com/11648042/122576397-f10cac00-d051-11eb-84e1-c7f297987a4d.mov
TODO:

[Storybook] Add addon measure

---

CHANGELOG.md
assets/javascripts/kitten/components/modals/next/index.js

ಠ_ಠ @bjlaa 
Closes #.
Vercel link:
- https://kitten-git-modal-next-fix-content-heigh-ddb640-kisskissbankbank.vercel.app/?path=/story/modals-modal-next--complex-with-orion
-  **OLD**: https://kitten.vercel.app/?path=/story/modals-modal-next--complex-with-orion
Screenshot:
TODO:

[ModalNext] Fix modal content height for decrepit versions of Safari

---

CHANGELOG.md
assets/javascripts/kitten/helpers/utils/parser.js
assets/javascripts/kitten/helpers/utils/parser.test.js
package-lock.json
package.json

On sanitize le `parsehtml`par défaut pour éviter les attaques XSS,
je mets quand même la possibilité de ne pas sanitize dans le cas de nos trads (qu'on maitrise, ça serait balo qu'on s'auto xss) pour gagner un poil en perfs

Sanitize html by default

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/stories.js
assets/javascripts/kitten/components/molecules/cards/contribution-card/contribution-card.stories.js
assets/javascripts/kitten/components/molecules/text-copy/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/text-copy/index.js

Closes #.
Vercel link:
- https://kitten-git-text-copy-fix-webkit-sizing-bug-kisskissbankbank.vercel.app/?path=/story/layout-dashboardlayout--default
Screenshot:
TODO:

[TextCopy] Fix WebKit sizing bug

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/upload/documents-drop-uploader/index.js
assets/javascripts/kitten/components/molecules/upload/documents-drop-uploader/stories.js

Actuellement l'event onChange est déclenché même en cas d'erreur, j'ai ajouté un flag pour ne pas le déclencher.
Le onError était aussi déclenché systématiquement, je vérifie maintenant si le tableau d'erreur contient au moins une erreur
TODO:

[DocumentDropUploader]improve onChange and onError events

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/upload/documents-drop-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/upload/documents-drop-uploader/index.js
assets/javascripts/kitten/components/molecules/upload/documents-drop-uploader/stories.js

Closes #.
Vercel link:
- https://kitten-git-documents-drop-uploader-hide-e71861-kisskissbankbank.vercel.app/?path=/story/molecules-upload-documentsdropuploader--default
Screenshot:
TODO:

[DocumentsDropUploader] Hide files with errors

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/modal-next/Modal.stories.js
assets/javascripts/kitten/components/molecules/modal-next/index.js

Closes #.
Vercel link:
- [https://kitten-git-modal-next-add-header-message-prop-kisskissbankbank.vercel.app/iframe.html?id=molecules-modal-next--complex-with-orion&args=&knob-headerMessage=This%20is%20a%20new%20message&knob-Size=giant&knob-content=…?&viewMode=story](https://kitten-git-modal-next-add-header-message-prop-kisskissbankbank.vercel.app/iframe.html?id=molecules-modal-next--complex-with-orion&args=&knob-headerMessage=This%20is%20a%20new%20message&knob-Size=giant&knob-content=%20%20Sed%20ut%20perspiciatis%20unde%20omnis%20iste%20natus%20error%20sit%20voluptatem%20%20accusantium%20doloremque%20laudantium,%20totam%20rem%20aperiam,%20eaque%20ipsa%20%20quae%20ab%20illo%20inventore%20veritatis%20et%20quasi%20architecto%20beatae%20vitae%20%20dicta%20sunt%20explicabo.%20Nemo%20enim%20ipsa …

[Modal/Next] Add `headerMessage` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/flow/index.js
assets/javascripts/kitten/components/layout/dashboard-layout/stories.js
assets/javascripts/kitten/components/molecules/upload/documents-status-box/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DashboardLayout] Fix `Flow.Nav` single button mobile width with new

---

CHANGELOG.md
assets/javascripts/kitten/components/form/range-slider/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/range-slider/index.js
assets/javascripts/kitten/components/form/range-slider/stories.js
assets/javascripts/kitten/components/form/range-slider/test.js

Ça permet de gérer (entre autre) les cas où on veut mettre une `value` qui sort du `min`/`max`.
Car faire `nativeInputValueSetter.call(inputEl.current, 40)` quand le `max=20` ne fonctionne pas.

[Range] When value is present the range is controlled

---

CHANGELOG.md
assets/javascripts/kitten/components/organisms/header-nav/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HeaderNav] Add `cursor` to `onClick`

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/styles.js

Closes #.
Vercel link:
- https://kitten-git-dashboard-layout-fix-header-6faa69-kisskissbankbank.vercel.app/iframe.html?id=layout-dashboardlayout--default&args=&globals=backgrounds.grid:false&viewMode=story (voir en mobile)
Screenshot:
TODO:

[DashboardLayout] Fix header elements dimensions

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/cards/reward-summary-card/hooks/use-resize-observer.js

Closes #.
Vercel link:
Screenshot:
TODO:

[useResizeObserver] Fix use condition for older browsers

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/stories/menu.js
assets/javascripts/kitten/components/layout/dashboard-layout/styles.js
assets/javascripts/kitten/components/organisms/dashboard-menu/__snapshots__/test.js.snap
assets/javascripts/kitten/components/organisms/dashboard-menu/index.js
assets/javascripts/kitten/components/organisms/dashboard-menu/stories.js

Closes #.
Vercel link:
- https://kitten-git-dashboard-menu-fix-expandable-size-kisskissbankbank.vercel.app/?path=/story/layout-dashboardlayout--default&args=multiMenu:true
Screenshot:
TODO:

[DashboardMenu] Add size prop to Expandable

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/upload/documents-drop-uploader/index.js
src/components/molecules/upload/documents-drop-uploader/index.js
src/esm/components/molecules/upload/documents-drop-uploader/index.js

Je remplace la destruction `[...e]` par un `Array.from` pour passer d'un `FileList` à un `[File]`
La régression fait très certainement suite à la mise à jour de babel qui change le comportement

Fix upload files

---

CHANGELOG.md
assets/javascripts/kitten/components/atoms/avatar-with-text-and-badge/__snapshots__/test.js.snap
assets/javascripts/kitten/components/atoms/avatar-with-text-and-badge/index.js

Closes #.
Vercel link:
https://kitten-git-fix-avatar-img-kisskissbankbank.vercel.app/?path=/story/atoms-avatarwithtextandbadge--default
Screenshot:
TODO:

[AvatarWithTextAndBadge] Add `border` on the avatar image.

---

.storybook/decorators/dev-grid.js
.storybook/preview.js
CHANGELOG.md
assets/javascripts/kitten/components/structure/carousels/carousel/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/carousels/carousel/components/carousel-inner.js
assets/javascripts/kitten/components/structure/carousels/carousel/components/carousel-page.js
assets/javascripts/kitten/components/structure/carousels/carousel/styles.js

Closes #.
Vercel link:
- https://kitten-git-carousel-fix-a11y-error-kisskissbankbank.vercel.app/?path=/story/structure-carousels-carousel--engagements-carousel
Screenshot:
TODO:

[Carousel] More accessible handling of prev/next click

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/dashboard-menu/__snapshots__/test.js.snap
assets/javascripts/kitten/components/navigation/dashboard-menu/index.js
assets/javascripts/kitten/components/navigation/dashboard-menu/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DashboardMenu] Fix Expandable open state by removing useless code

---

CHANGELOG.md
assets/javascripts/kitten/components/form/input/location-input/index.js
assets/javascripts/kitten/components/form/input/location-input/stories.js

Permet de gérer, côté KissKiss, ce qu'on veut afficher dans l'input une fois une adresse sélectionnée.
Par exemple, seulement numéro et libellé de voie
Vercel link:
Screenshot:
TODO:

[Location] Add new prop to display custom value

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/summary-card/components/title-bar.js
assets/javascripts/kitten/components/structure/cards/summary-card/hooks/use-resize-observer.js
assets/javascripts/kitten/components/structure/cards/summary-card/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[SummaryCard] Replace `xlarge` by `huge` prop size value

---

CHANGELOG.md
assets/javascripts/kitten/components/layer/modal/index.js
assets/javascripts/kitten/components/layer/modal/stories.js
assets/javascripts/kitten/components/layer/modal/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Modal] Add `as` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/hero-layout/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HeroLayout] Fix automated assignment of hasTopMenu

---

CHANGELOG.md
assets/javascripts/kitten/components/action/tag-button/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[V11/TagButton] Remove old deprecated props 

---

CHANGELOG.md
assets/javascripts/kitten/components/information/avatar-with-text-and-badge/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[V11/AvatarWithTextAndBadge] Remove `textClassName` prop.

---

CHANGELOG.md
assets/javascripts/kitten/components/interaction/discussion/__snapshots__/test.js.snap
assets/javascripts/kitten/components/interaction/discussion/index.js
assets/javascripts/kitten/components/navigation/messages-menu/__snapshots__/test.js.snap
assets/javascripts/kitten/components/navigation/messages-menu/index.js
assets/javascripts/kitten/components/navigation/messages-menu/stories.js
assets/javascripts/kitten/components/navigation/messages-menu/test.js

Closes #.
Vercel link:
- https://kitten-git-messages-menu-add-close-button-kisskissbankbank.vercel.app/?path=/story/navigation-messagesmenu--default
Screenshot:
TODO:

[MessagesMenu] Add close button

---

CHANGELOG.md
assets/javascripts/kitten/components/form/input/text-input/index.js

Sans les parenthèses le `.length` n'est forcément pris en compte que par le `''`………

[TextInput] Fix length limit init

---

CHANGELOG.md
assets/javascripts/kitten/components/layer/modal/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layer/modal/index.js
assets/javascripts/kitten/components/layer/modal/stories.js
assets/javascripts/kitten/components/layer/modal/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Modal] Better typing of `as` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/index.js
assets/javascripts/kitten/components/layout/dashboard-layout/stories.js
assets/javascripts/kitten/components/layout/dashboard-layout/stories/with-flow.js
assets/javascripts/kitten/components/layout/dashboard-layout/stories/with-reward.js
assets/javascripts/kitten/components/layout/dashboard-layout/styles.js

Closes #.
Vercel link:
- https://kitten-git-dashboard-layout-add-backgro-479e2d-kisskissbankbank.vercel.app/?path=/story/layout-dashboardlayout--with-reward-content&args=toasterIsOpen:true
Screenshot:
TODO:

[DashboardLayout] Add `background` and `fullSize` props to `Toaster` subcomponent
