KissKissBankBank/kitten

app/views/kitten/pages/home.html.erb

Pitite PR pour pouvoir continuer à tester la page `/kitten/pages/home`.

Fix padding on homepage example

---

CHANGELOG.md
app/views/kitten/components/atoms/buttons/button-icon.html.erb
assets/stylesheets/kitten/atoms/buttons/_button-icon.scss

k-buttonIcon--micro

---

CHANGELOG.md
assets/javascripts/kitten/components/simulators/loan-simulator.js

Le décalage est moche mais demande plus de temps pour déplacer la logique.

Add initial installment on Loan Simulator

---

CHANGELOG.md
assets/stylesheets/_kitten.scss
assets/stylesheets/kitten/utilities/spacing/_margin.scss
assets/stylesheets/kitten/utilities/spacing/_spacing.scss

Spacing utility

---

CHANGELOG.md
app/views/kitten/components/atoms/lists/bullet-list.html.erb
app/views/kitten/components/atoms/typography/paragraph.html.erb
assets/stylesheets/kitten/atoms/lists/_bullet-list.scss
assets/stylesheets/kitten/atoms/typography/_paragraph.scss

Links in bullet lists and paragraphs

---

CHANGELOG.md
assets/javascripts/kitten/components/box/link-box.js
assets/javascripts/kitten/components/box/link-box.test.js
assets/stylesheets/kitten/organisms/box/_link-box.scss

PR qui ajoute une option pour avoir un `target="_blank"` sur le lien ainsi que quelques modifications de styles.
TODO:

Add isExternal on LinkBox

---

CHANGELOG.md
assets/stylesheets/kitten/atoms/lists/_bullet-list.scss
assets/stylesheets/kitten/atoms/typography/_paragraph.scss

Fix links text decoration in bullet list and paragraphs

---

CHANGELOG.md
app/views/kitten/components/molecules/form/form-actions.html.erb
app/views/kitten/groups/components/molecules/_form.html.erb
assets/stylesheets/_kitten.scss
assets/stylesheets/kitten/molecules/form/_form-actions.scss
spec/dummy/client/stylesheets/kitten/_molecules.scss

Permet d'espacer correctement les enfants dans chaque coin. Punition !
Screenshot:
TODO:

k-FormActions component

---

CHANGELOG.md
app/assets/stylesheets/kitten/karl/_layout.scss
app/views/kitten/components/molecules/grid/vertical-grid.html.erb
app/views/kitten/groups/components/molecules/_grid.html.erb
assets/stylesheets/_kitten.scss
assets/stylesheets/kitten/molecules/grid/_vertical-grid.scss
spec/dummy/client/stylesheets/kitten/_molecules.scss

Composant pour gérer une grille verticale et permettre à un élément d'être fluide dans la page.
Screenshot:
TODO:

k-VerticalGrid component

---

app/views/kitten/components/molecules/grid/grid.html.erb

Screenshot:
Changement trop petit pour être dans le CHANGELOG.

Add subgrid example in Karl

---

CHANGELOG.md
app/views/kitten/components/form/select.html.erb
assets/javascripts/kitten/components/form/select-with-state.js
assets/stylesheets/kitten/components/form/_select.scss

Need a stylized label for select component.
Screenshot:

Add a label in k-Select

---

CHANGELOG.md
assets/stylesheets/kitten/components/box/_link-box.scss

PR qui gère l'alignement vertical du paragraphe dans le `LinkBox`.
Closes #341.
TODO:

Vertical align on k-LinkBox__paragraph

---

CHANGELOG.md
app/views/kitten/pages/home.html.erb
assets/stylesheets/kitten/components/teaser/_teaser.scss

Fix ordering of cols on teaser

---

CHANGELOG.md
assets/stylesheets/kitten/components/grid/_row.scss
spec/dummy/client/stylesheets/kitten/_components.scss

Add default colors to k-Row

---

CHANGELOG.md
assets/stylesheets/kitten/_default-config.scss
assets/stylesheets/kitten/components/grid/_row.scss
spec/dummy/client/stylesheets/kitten/_components.scss
spec/dummy/client/stylesheets/kitten/_theme-hellomerci.scss
spec/dummy/client/stylesheets/kitten/_theme-kisskissbankbank.scss
spec/dummy/client/stylesheets/kitten/_theme-lendopolis.scss

Couleur venant de  https://app.zeplin.io/project.html#pid=57a45b56f0c3427e3c985a7d&sid=5849422a189000245543758a

Primary 6 color

---

README.md
bin/test
package.json

PR qui permet de tester un fichier unique.

Launch single file tests

---

CHANGELOG.md
app/views/kitten/components/grid/grid.html.erb
assets/javascripts/kitten/components/grid/grid.js
assets/javascripts/kitten/components/grid/grid.test.js
assets/javascripts/kitten/karl/grid/grid.js
spec/dummy/client/entries/app-kitten.js

Création du composant `Grid` et `GridCol`.
Closes https://github.com/KissKissBankBank/kitten/issues/367.
TODO:

`Grid` React component

---

CHANGELOG.md
app/views/kitten/components/form/checkbox.html.erb
assets/javascripts/kitten/components/form/checkbox.js
assets/javascripts/kitten/components/form/checkbox.test.js
spec/dummy/client/entries/app-kitten.js

Add `Checkbox` React component

---

CHANGELOG.md
app/views/kitten/components/form/form-actions.html.erb
assets/javascripts/kitten/components/form/form-actions.js
assets/javascripts/kitten/components/form/form-actions.test.js
assets/javascripts/kitten/karl/form/form-actions.js
spec/dummy/client/entries/app-kitten.js

Closes https://github.com/KissKissBankBank/kitten/issues/371.
TODO:

`FormActions` React component

---

CHANGELOG.md
assets/stylesheets/kitten/components/press/_press-quotes.scss
assets/stylesheets/kitten/components/testimonies/_testimony.scss

Override boostrap on blockquotes

---

CHANGELOG.md
assets/javascripts/kitten/components/headers/header-logo.js
assets/javascripts/kitten/components/headers/header-logo.test.js
assets/javascripts/kitten/karl/headers/header.js

Closes https://github.com/KissKissBankBank/kitten/issues/384.
TODO:

`HeaderLogo` React component

---

CHANGELOG.md
app/views/kitten/components/form/checkbox.html.erb
assets/javascripts/kitten/components/form/checkbox.js
assets/javascripts/kitten/components/form/checkbox.test.js

Remplace props text to children for `Checkbox`component

---

CHANGELOG.md
app/views/kitten/pages/maker-who-am-i.html.erb
assets/javascripts/kitten/components/form/checkbox.js
assets/javascripts/kitten/components/form/radio-button.js
package.json
spec/dummy/client/javascripts/app/maker/who-am-i/components/container.js

PR qui permet d'afficher des warnings en console quand on utilise une propriété dépréciée.
Screenshot:
TODO:

Add deprecated function

---

CHANGELOG.md
assets/stylesheets/kitten/components/form/_select.scss

Update disabled color for Select

---

CHANGELOG.md
assets/stylesheets/kitten/components/box/_link-box.scss

Update hover background-color for `LinkBox`

---

CHANGELOG.md
assets/stylesheets/kitten/components/grid/_side-grid.scss
assets/stylesheets/kitten/components/grid/_vertical-grid.scss
spec/dummy/client/javascripts/app/maker/who-am-i/components/container.js

PR qui corrige un problème de `flexbox` sur le composant `SideGrid` et `VerticalGrid`.
TODO:

Fix flexbox on SideGrid

---

CHANGELOG.md
assets/stylesheets/kitten/utilities/spacing/_margin.scss

Toujours plus d'espace avec cette PR !
TODO:

Add `quintuple` utilities

---

CHANGELOG.md
assets/javascripts/kitten/components/headers/header-titles.js
assets/javascripts/kitten/components/headers/header-titles.test.js

Add new props on HeaderTitles

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/side-grid.js
assets/javascripts/kitten/components/grid/side-grid.test.js

Add rowClassName on SideGrid

---

CHANGELOG.md
app/views/kitten/pages/auto-trigger-popover.html.erb
assets/javascripts/kitten/components/popovers/popover.js
assets/javascripts/kitten/hoc/auto-trigger-enhancer.js
spec/dummy/client/entries/app-kitten.js
spec/dummy/client/javascripts/karl/components/popovers/auto-trigger-popover.js
spec/dummy/client/stylesheets/app-dummy.scss

Create an enhancer to automatically display a component

---

CHANGELOG.md
assets/javascripts/kitten/components/popovers/call-to-action-popover.js
assets/javascripts/kitten/components/popovers/call-to-action-popover.test.js

Fix CallToActionPopover

---

CHANGELOG.md
assets/stylesheets/kitten/components/form/_text-input.scss

Set #b8b8b8 as placeholder color.

Set placeholder color in `k-TextInput`

---

CHANGELOG.md
assets/stylesheets/kitten/components/titles/title-with-actions.scss

New Modifier to remove margin when no action

---

CHANGELOG.md
app/views/kitten/components/form/select.html.erb
assets/javascripts/kitten/components/form/select-with-state.js
assets/stylesheets/kitten/components/form/_select.scss

Big Select with state label

---

CHANGELOG.md
app/views/kitten/components/layout/line.html.erb
app/views/kitten/groups/components/_layout.html.erb
app/views/layouts/kitten/components.html.erb
assets/stylesheets/kitten/_components.scss
assets/stylesheets/kitten/components/layout/_line.scss
spec/dummy/client/stylesheets/kitten/_components.scss

Closes https://github.com/KissKissBankBank/kitten/issues/446.
Screenshot:
TODO:

Add new `Line` component

---

CHANGELOG.md
assets/stylesheets/kitten/components/form/_select.scss
assets/stylesheets/kitten/components/heroes/_hero.scss

Fix font size and margin bottom under media s on homepage

---

CHANGELOG.md
app/views/kitten/components/form/text-input-with-unit.html.erb
assets/javascripts/kitten/components/form/text-input-with-unit.js
assets/javascripts/kitten/components/form/text-input-with-unit.test.js
assets/stylesheets/kitten/components/form/_text-input-with-unit.scss
spec/dummy/client/entries/app-kitten.js

Closes https://github.com/KissKissBankBank/kitten/issues/448.
Screenshot:
TODO:

Add new `TextInputWithUnit` React component

---

CHANGELOG.md
assets/stylesheets/kitten/components/form/_checkbox.scss
assets/stylesheets/kitten/components/form/_radio-button.scss

Cf. http://stackoverflow.com/a/23794791
Closes #434.
Screenshot:
TODO:

Use flex instead of width to fix responsive width problem.

---

CHANGELOG.md
app/views/kitten/components/form/text-input-with-limit.html.erb
assets/javascripts/kitten/components/form/text-input-with-limit.js
assets/javascripts/kitten/components/form/text-input-with-unit.js
assets/javascripts/kitten/components/form/text-input.js
assets/javascripts/kitten/components/form/text-input.test.js
assets/javascripts/kitten/components/simulators/loan-simulator.js
assets/stylesheets/kitten/_components.scss
assets/stylesheets/kitten/components/form/_text-area-wrapper.scss
assets/stylesheets/kitten/components/form/_text-input-with-limit.scss
assets/stylesheets/kitten/components/form/_text-input.scss
spec/dummy/client/stylesheets/kitten/_components.scss

Closes #473, #482.
Screenshot:
TODO:

Update text input with limit

---

CHANGELOG.md
assets/stylesheets/kitten/components/box/_information-box.scss

Fix wrong padding for `InformationBox` component

---

CHANGELOG.md
assets/javascripts/kitten/components/form/select-with-state.js

SelectWithState defaults to false deleteRemoves

---

CHANGELOG.md
assets/javascripts/kitten/components/notifications/alert.js
assets/javascripts/kitten/components/notifications/alert.test.js
assets/stylesheets/kitten/components/notifications/_alert.scss

Modification de l'animation de fermeture d'une alerte.
TODO:

Animation change when alert closes

---

CHANGELOG.md
assets/javascripts/kitten/karl/tooltips/static-tooltip.js
assets/stylesheets/kitten/components/tooltips/_static-tooltip.scss

Add grid on StaticTooltip

---

bin/install

Ajout de l'installation de Ruby directement dans `bin/install` pour que `kitten-pull` vérifie lui-même qu'il a la bonne version de ruby installée ou l'installe le cas échéant.

Add ruby install in bin/install

---

assets/stylesheets/kitten/components/form/_search-input.scss

Fix search input bug on Safari

---

CHANGELOG.md
app/views/kitten/components/buttons/button-with-badge.html.erb
assets/javascripts/kitten/karl/tooltips/static-tooltip.js
assets/stylesheets/kitten/utilities/text/_align.scss
spec/dummy/client/stylesheets/app-dummy.scss

Add `k-u-align-right` class

---

CHANGELOG.md
app/assets/stylesheets/kitten/karl/_card.scss
app/views/kitten/components/grid/lego-grid.html.erb
app/views/kitten/groups/components/_grid.html.erb
assets/javascripts/kitten/components/grid/lego-grid.js
assets/javascripts/kitten/components/grid/lego-grid.test.js
assets/javascripts/kitten/karl/grid/lego-grid.js
assets/stylesheets/kitten/_components.scss
assets/stylesheets/kitten/components/dev/_dev-grid.scss
assets/stylesheets/kitten/components/grid/_lego-grid.scss
assets/stylesheets/kitten/helpers/grid/_col.scss
package.json
spec/dummy/client/entries/app-kitten.js
spec/dummy/client/stylesheets/kitten/_components.scss

Closes https://github.com/KissKissBankBank/kitten/issues/528.
Screenshot:
TODO:

Add `LegoGrid` component

---

CHANGELOG.md
app/views/kitten/components/notifications/badge.html.erb
assets/javascripts/kitten/components/notifications/badge.js
assets/javascripts/kitten/components/notifications/badge.test.js
spec/dummy/client/entries/app-kitten.js

Add `Badge` React component

---

CHANGELOG.md
app/views/kitten/components/notifications/icon-badge.html.erb
app/views/kitten/groups/components/_notifications.html.erb
assets/javascripts/kitten/components/notifications/icon-badge.js
assets/javascripts/kitten/components/notifications/icon-badge.test.js
assets/javascripts/kitten/karl/notifications/icon-badge.js
assets/stylesheets/kitten/_components.scss
assets/stylesheets/kitten/components/notifications/_icon-badge.scss
spec/dummy/client/entries/app-kitten.js
spec/dummy/client/stylesheets/kitten/_components.scss

Closes https://github.com/KissKissBankBank/kitten/issues/537.
Screenshot:
Après le fixe du line-height : 
TODO:

Add `IconBadge` component

---

CHANGELOG.md
assets/stylesheets/kitten/components/buttons/_button.scss
assets/stylesheets/kitten/helpers/_button.scss
assets/stylesheets/kitten/helpers/button/_big.scss
spec/dummy/client/javascripts/app/maker/who-am-i/components/container.js

Add `k-buttonBig` mixin and `k-Button--big@s-up` modifier

---

app/assets/stylesheets/kitten/karl/_layout.scss

New grid for new style

---

CHANGELOG.md
app/views/kitten/components/typography/sup-title.html.erb
app/views/kitten/components/typography/title.html.erb
assets/javascripts/kitten/components/typography/sup-title.js
assets/javascripts/kitten/components/typography/sup-title.test.js
assets/stylesheets/kitten/_components.scss
assets/stylesheets/kitten/components/typography/_sup-title.scss
spec/dummy/client/entries/app-kitten.js
spec/dummy/client/stylesheets/kitten/_components.scss

Create `SupTitle` component

---

CHANGELOG.md
assets/stylesheets/kitten/_utilities.scss
assets/stylesheets/kitten/utilities/text/_color.scss
spec/dummy/client/stylesheets/kitten/_utilities.scss

Closes https://github.com/KissKissBankBank/kitten/issues/506.
Screenshot:
TODO:

Add color utilities

---

CHANGELOG.md
assets/javascripts/kitten/components/typography/paragraph.js
assets/javascripts/kitten/components/typography/paragraph.test.js
assets/stylesheets/kitten/components/typography/_paragraph.scss

Add margin prop to Paragraph component

---

CHANGELOG.md
app/views/kitten/components/buttons/button-image.html.erb
assets/javascripts/kitten/components/buttons/button-image.js
assets/javascripts/kitten/components/buttons/button-image.test.js
spec/dummy/client/entries/app-kitten.js

Décline le `k-ButtonImage` en composant `ButtonImage`.
TODO:

Add ButtonImage component

---

CHANGELOG.md
app/views/kitten/components/form/text-input-with-limit.html.erb
assets/javascripts/kitten/components/form/text-input-with-limit.js
assets/javascripts/kitten/components/form/text-input-with-limit.test.js
assets/javascripts/kitten/components/form/text-input.js
assets/stylesheets/kitten/components/form/_text-area-wrapper.scss
assets/stylesheets/kitten/components/form/_text-input-with-limit.scss

Closes #570.
Screenshot:
**Before**:
**After**:
TODO:

Fix disabled text input with limit

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/marger.js
assets/javascripts/kitten/components/layout/marger.test.js

Composant qui permet de gérer les marges verticales.
Closes #565.
TODO:

Add Marger component

---

CHANGELOG.md
app/views/kitten/components/layout/separator.html.erb
app/views/kitten/groups/components/_layout.html.erb
assets/javascripts/kitten/components/layout/separator.js
assets/javascripts/kitten/components/layout/separator.test.js
assets/stylesheets/kitten/_components.scss
assets/stylesheets/kitten/components/layout/_separator.scss
spec/dummy/client/entries/app-kitten.js
spec/dummy/client/stylesheets/kitten/_components.scss

Add Separator component

---

CHANGELOG.md
assets/javascripts/kitten/karl/form/checkbox.js
assets/javascripts/kitten/karl/form/radio-button.js

Delete label on Checkbox and RadioButton error examples

---

CHANGELOG.md
app/views/kitten/components/buttons/button-with-icon-words.html.erb
app/views/kitten/groups/components/_buttons.html.erb
assets/javascripts/kitten/karl/buttons/button-with-icon-words.js
assets/stylesheets/kitten/components/buttons/_button.scss
spec/dummy/client/entries/app-kitten.js

Remove `button-heart-icon-words

---

assets/javascripts/kitten/karl/grid/lego-grid.js

Suppression de la hauteur aléatoire pour éviter le warning entre le rendu server et client.
Screenshot:

Fix warning with random height renderer

---

app/views/kitten/components/titles/title-with-actions.html.erb

Update english title

---

CHANGELOG.md
KARL_CHANGELOG.md
app/assets/stylesheets/kitten/karl/_layout.scss
app/views/kitten/components/headers/header.html.erb
app/views/kitten/components/navigation/tab-bar.html.erb

Add link class on Header and TabBar components.

---

CHANGELOG.md
assets/javascripts/kitten/hoc/card.js
assets/javascripts/kitten/hoc/card.test.js
assets/stylesheets/kitten/components/cards/_card.scss

PR qui permet d'utiliser un composant générique afin d'initialiser une `Card`.
Remplace https://github.com/KissKissBankBank/kitten/pull/585#issuecomment-292117646
TODO:

Add `card` high-order component

---

CHANGELOG.md
assets/javascripts/kitten/components/notifications/alert.js
assets/javascripts/kitten/components/notifications/alert.test.js
assets/stylesheets/kitten/components/notifications/_alert.scss

Fix background `Alert` width

---

CHANGELOG.md
app/views/kitten/components/simulators/loan-simulator.html.erb
assets/javascripts/kitten/components/simulators/loan-simulator.js
assets/javascripts/kitten/karl/organisms/loan-simulator.js
assets/stylesheets/kitten/components/simulators/_loan-simulator.scss
spec/dummy/client/entries/app-kitten.js

Closes https://github.com/KissKissBankBank/hellomerci/issues/394.
Screenshot:
TODO:

Add exemption to `LoanSimulator` component

---

assets/stylesheets/kitten/components/grid/_container.scss

Use k-container instead of container in Container component

---

spec/dummy/client/stylesheets/kitten/_theme-hellomerci.scss
spec/dummy/client/stylesheets/kitten/_theme-kisskissbankbank.scss
spec/dummy/client/stylesheets/kitten/_theme-lendopolis.scss

Update themes colors

---

KARL_CHANGELOG.md
assets/stylesheets/kitten/components/box/_information-box.scss

Update border-color `InformationBox` component.

---

KARL_CHANGELOG.md
app/views/kitten/components/form/slider.html.erb
app/views/kitten/components/form/text-input-with-unit.html.erb
app/views/kitten/components/lists/bullet-list.html.erb
app/views/kitten/components/meters/progress.html.erb

Add k-Grid class on Slider, Bullet-list, Progress, Text-input-with-unit components.

---

CHANGELOG.md
KARL_CHANGELOG.md
app/views/kitten/components/buttons/image-button.html.erb
assets/javascripts/kitten/components/buttons/button-image.js
assets/javascripts/kitten/components/buttons/button-image.test.js
assets/stylesheets/kitten/components/buttons/_button-image.scss

Add withBorder prop to ButtonImage

---

README.md
Rakefile

Dans la tâche rake `kitten_release`, j'ai ajouté le commit du fichier `KARL_CHANGELOG.md`.

Update release task with `KARL_CHANGELOG`

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/project-card.js

Add withBorder prop to ButtonImage in ProjectCard

---

KARL_CHANGELOG.md
app/views/kitten/components/teaser/teaser.html.erb
app/views/kitten/components/testimonies/testimony-list.html.erb
app/views/kitten/components/testimonies/testimony.html.erb

Remove size on empty images.

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/project-card.test.js
bin/test

Avant ce fix :
```
11 passing (182ms)
```
Après ce fix :
```
370 passing (594ms)
```

Fix test launch

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/project-card.js

Closes #630.
Screenshot:
TODO:

Fix `Title` tag in `ProjectCardComponent`

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/project-card.js
assets/javascripts/kitten/components/cards/project-card.test.js
assets/javascripts/kitten/karl/cards/project-card.js
assets/stylesheets/kitten/components/cards/_project-card.scss

Add `ProjectCard` status

---

CHANGELOG.md
assets/stylesheets/kitten/_utilities.scss
assets/stylesheets/kitten/utilities/image/_responsive.scss
spec/dummy/client/stylesheets/kitten/_utilities.scss

Add responsive image

---

spec/dummy/client/entries/app-kitten.js

PR qui supprime l'import d'un composant n'existant plus.

Remove missing component import

---

app/views/kitten/branding/colors/common.html.erb
app/views/kitten/branding/colors/hellomerci.html.erb
app/views/kitten/branding/colors/kisskissbankbank.html.erb
app/views/kitten/branding/colors/lendopolis.html.erb

Update color names

---

KARL_CHANGELOG.md
app/views/kitten/components/form/checkbox.html.erb
app/views/kitten/components/form/form-info.html.erb
app/views/kitten/components/form/search-input.html.erb
app/views/kitten/components/form/select.html.erb
app/views/kitten/components/popovers/popover.html.erb
app/views/kitten/components/testimonies/testimony-list.html.erb
app/views/kitten/components/testimonies/testimony.html.erb
app/views/kitten/components/titles/title-with-actions.html.erb
app/views/kitten/components/tours/tour.html.erb
app/views/kitten/components/typography/title.html.erb
assets/javascripts/kitten/components/simulators/loan-simulator.js
assets/javascripts/kitten/components/typography/title.js
assets/javascripts/kitten/karl/form/form-row.js
lib/kitten/configuration.rb

Update component example texts

---

CHANGELOG.md
KARL_CHANGELOG.md
app/views/kitten/components/cards/project-card.html.erb
assets/javascripts/kitten/components/cards/project-card.js
assets/javascripts/kitten/components/cards/project-card.test.js
assets/stylesheets/kitten/components/cards/_project-card.scss
spec/dummy/client/javascripts/app/browsing/browsing.js

Add tooltip in `ProjectCard`

---

KARL_CHANGELOG.md
app/views/kitten/components/grid/row.html.erb
app/views/kitten/components/grid/single-column.html.erb
app/views/kitten/components/popovers/popover.html.erb
assets/javascripts/kitten/components/simulators/loan-simulator.js
assets/javascripts/kitten/karl/buttons/payment-button.js
assets/javascripts/kitten/karl/grid/side-grid.js
assets/javascripts/kitten/karl/headers/header.js

Last update style guide v1

---

Rakefile
spec/dummy/client/yarn.lock

Il manquait une mise à jour du package.json dans les derniers trucs mergés.

Missing yarn lock update

---

bin/start

Requis pour s'en servir via le RUN de Docker, sinon :

Add shebang to bin/start

---

assets/stylesheets/kitten/_utilities.scss

Add import of background utilities

---

CHANGELOG.md
assets/javascripts/kitten/components/form/rich-text-input.js

This allow the component value to be saved with redux form.

Add missing onChange prop on `RichTextInput` component

---

assets/javascripts/kitten/components/cards/project-creator-card.js
assets/stylesheets/kitten/components/cards/_project-creator-card.scss

Little fix `ProjectCreatorCard` component

---

KARL_CHANGELOG.md
app/helpers/kitten/components_helper.rb
app/views/layouts/kitten/_component.html.erb
app/views/layouts/kitten/components.html.erb
lib/kitten/configuration.rb

Add class `k-u-hidden@s-down` on component hidden on s

---

CHANGELOG.md
assets/javascripts/kitten/components/form/text-input-with-unit.js
assets/stylesheets/kitten/components/form/_text-input.scss

Remove `k-TextInput` too and add `box-shadow: none` property

---

CHANGELOG.md
app/views/kitten/components/form/form-info.html.erb
assets/stylesheets/kitten/components/form/_checkbox.scss
assets/stylesheets/kitten/components/form/_radio-button.scss

Remove error-color label

---

CHANGELOG.md
assets/stylesheets/kitten/utilities/text/_color.scss

Add error-color utility

---

KARL_CHANGELOG.md
Rakefile

Merge the styleguide branch on release

---

CHANGELOG.md
KARL_CHANGELOG.md
assets/javascripts/kitten/components/form/location-input.js
assets/javascripts/kitten/karl/form/location-input.js
assets/stylesheets/kitten/components/form/_form-info.scss

Update label component on `FormInfo` and `LocationInput`.

---

CHANGELOG.md
assets/stylesheets/kitten/components/lines/_info-lines.scss

Handles small version of `InfoLines` component

---

README.md
bin/kitten

add `bin/kitten test`.
For now the function calls `bin/test`.
TODO:
Integrate `bin/test` to `bin/kitten`

Add `bin/kitten test`

---

CHANGELOG.md
assets/javascripts/kitten/components/images/image-cropper.js

Fix initial size of `cropper` in `ImageCropper` component.

---

CHANGELOG.md
KARL_CHANGELOG.md
app/views/kitten/components/typography/paragraph.html.erb
assets/javascripts/kitten/components/typography/paragraph.js
assets/javascripts/kitten/components/typography/paragraph.test.js
assets/javascripts/kitten/karl/typography/paragraph.js
assets/stylesheets/kitten/components/typography/_paragraph.scss

Add `italic` prop to `Paragraph` component

---

CHANGELOG.md
assets/stylesheets/kitten/utilities/text/_align.scss

Add `k-u-align-center-block` utility to center blocks

---

CHANGELOG.md
app/views/kitten/components/form/text-input-with-button.html.erb
assets/javascripts/kitten/components/form/text-input-with-button.js
assets/javascripts/kitten/components/form/text-input-with-button.test.js
assets/javascripts/kitten/components/form/text-input.js
spec/dummy/client/entries/app-kitten.js

Add `TextInputWithButton` component

---

CHANGELOG.md
assets/javascripts/kitten/components/steppers/stepper.js
assets/javascripts/kitten/components/steppers/stepper.test.js

Closes https://github.com/KissKissBankBank/kitten/issues/756.
TODO:

Add `other` props to `Stepper` component

---

CHANGELOG.md
assets/stylesheets/kitten/_utilities.scss
assets/stylesheets/kitten/utilities/border/_border.scss
spec/dummy/client/stylesheets/kitten/_utilities.scss

Add border utilities

---

CHANGELOG.md
KARL_CHANGELOG.md
app/views/kitten/components/buttons/icon-button.html.erb
assets/javascripts/kitten/components/buttons/social-button-icon.js
assets/javascripts/kitten/components/buttons/social-button-icon.test.js
assets/javascripts/kitten/components/buttons/tag-button.test.js
assets/javascripts/kitten/karl/buttons/button-icon.js
spec/dummy/client/entries/app-kitten.js

Add social button icon components

---

CHANGELOG.md
assets/javascripts/kitten/components/links/link-list.js
assets/javascripts/kitten/components/links/link-list.test.js
assets/stylesheets/kitten/components/links/_link-list.scss

Add `margin: 0` on LinkList component.

---

CHANGELOG.md
assets/stylesheets/kitten/components/links/_link-list.scss

Add responsive `LinkList` component.

---

CHANGELOG.md
KARL_CHANGELOG.md
app/views/kitten/components/lines/info-lines.html.erb
assets/javascripts/kitten/components/lines/info-lines.js
assets/javascripts/kitten/components/lines/info-lines.test.js
assets/stylesheets/kitten/components/lines/_info-lines.scss

Add props to `InfoLines` component

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/grid.js
assets/javascripts/kitten/components/grid/grid.test.js

Accept other props to `GridCol` component

---

CHANGELOG.md
app/views/kitten/components/modals/modal.html.erb
assets/javascripts/kitten/components/modals/modal.js
assets/javascripts/kitten/karl/modals/modal.js
spec/dummy/client/entries/app-kitten.js

Closes #785.
Screenshot:
TODO:

Add external trigger to modal component

---

CHANGELOG.md
KARL_CHANGELOG.md
app/views/kitten/components/meters/progress.html.erb
assets/javascripts/kitten/components/meters/progress.js
assets/javascripts/kitten/components/meters/progress.test.js

Add `color` prop to `Progress` component

---

CHANGELOG.md
KARL_CHANGELOG.md
app/views/kitten/components/lines/info-lines.html.erb
assets/javascripts/kitten/components/lines/info-lines.js
assets/javascripts/kitten/components/lines/info-lines.test.js
assets/stylesheets/kitten/components/lines/_info-lines.scss

Pour la page projet sur LENDO, j'ai besoin de la version sans changement de grille.
TODO:

Add `withoutResponsive` prop to `InfoLines` component

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/grid.js

Closes https://github.com/KissKissBankBank/kitten/issues/783.
TODO:

Remove unknown props in `others` prop to `GridCol` component

---

CHANGELOG.md
assets/stylesheets/kitten/utilities/background/_background-color.scss

Add `k-u-background-color-background1` utility

---

CHANGELOG.md
KARL_CHANGELOG.md
assets/stylesheets/kitten/components/buttons/_button-icon.scss

Closes https://github.com/KissKissBankBank/kisskissbankbank/issues/1445.
TODO:

Fix pointer event on button icon svg for analytics

---

CHANGELOG.md
assets/stylesheets/kitten/components/links/_link-list.scss

Align left `LinkList` component

---

CHANGELOG.md
assets/stylesheets/kitten/components/links/_link-list.scss

This reverts commit 306f668b0443afb3746eae73e8f4e34190bb10a0.

Revert "Align left `LinkList` component"

---

CHANGELOG.md
README.md
app/views/kitten/components/cards/project-card.html.erb
assets/javascripts/kitten/components/cards/project-card.js
assets/javascripts/kitten/components/cards/project-card.test.js

Allow to reverse the infos in project card

---

KARL_CHANGELOG.md
app/views/kitten/components/typography/text.html.erb

New organization text component

---

CHANGELOG.md
app/views/kitten/components/cards/project-card.html.erb
assets/javascripts/kitten/components/cards/project-card.js
assets/javascripts/kitten/components/cards/project-card.test.js
assets/javascripts/kitten/components/cards/project-similar-card.js
assets/javascripts/kitten/components/cards/project-similar-card.test.js
assets/javascripts/kitten/components/cards/similar-projects-card.test.js
assets/javascripts/kitten/components/icons/instrument-tag-icon.js
assets/javascripts/kitten/components/icons/tag-icon.js
assets/javascripts/kitten/components/icons/typology-tag-icon.js
assets/javascripts/kitten/components/lists/tag-list.js
assets/javascripts/kitten/components/lists/tag-list.test.js
assets/javascripts/kitten/karl/cards/similar-projects-card.js
assets/javascripts/kitten/karl/lists/tag-list.js
assets/stylesheets/kitten/_components.scss
assets/stylesheets/kitten/_helpers.scss
assets/stylesheets/kitten/components/cards/_project-card.scss
assets/stylesheets/kitten/components/layout/_separator.scss
assets/stylesheets/kitten/components/layout/_vertical-separator.scss
assets/stylesheets/kitten/components/lists/_tag-list.scss
assets/stylesheets/kitten/helpers/_separator.scss
assets/stylesheets/kitten/helpers/button/_base.scss
assets/stylesheets/kitten/helpers/separator/_base.scss
spec/dummy/client/stylesheets/kitten/_components.scss

Screenshot:
Before:
After:
TODO:

Change `ProjectCard` component to allow multiple `Taglist` with different first icon.

---

CHANGELOG.md
assets/stylesheets/kitten/components/modals/modal.scss

Closes https://github.com/KissKissBankBank/kisskissbankbank/issues/1495
TODO:

Fix scroll problem on opened modal

---

CHANGELOG.md
assets/javascripts/kitten/components/form/text-input-with-unit.js
assets/javascripts/kitten/components/form/text-input-with-unit.test.js
assets/stylesheets/kitten/components/form/_text-input.scss

Closes https://github.com/KissKissBankBank/kisskissbankbank/issues/1485.
TODO:

Fix text input with unit

---

CHANGELOG.md
assets/javascripts/kitten/components/form/search.js
assets/javascripts/kitten/components/icons/arrow-icon.js

Corrected height

---

CHANGELOG.md
assets/stylesheets/kitten/utilities/text/_weight.scss

Error deprecated weight.scss

---

CHANGELOG.md
assets/stylesheets/kitten/components/form/_checkbox.scss
assets/stylesheets/kitten/components/form/_radio-button.scss

Add property `flex-shrink`on `RadioButton` and `Checkbox`

---

CHANGELOG.md
assets/stylesheets/kitten/components/tooltips/_static-tooltip.scss
assets/stylesheets/kitten/components/tooltips/_tooltip-new.scss
assets/stylesheets/kitten/components/tooltips/_tooltip.scss

Replace `tooltip` font-size

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button-icon.js

Change syntax on `ButtonIcon` component

---

CHANGELOG.md
assets/stylesheets/kitten/utilities/align/_align.scss
assets/stylesheets/kitten/utilities/text/_align.scss

Handle breakpoints with `k-u-blockAlign`

---

CHANGELOG.md
assets/javascripts/kitten/components/box/link-box.js
assets/javascripts/kitten/components/box/link-box.test.js

Add className prop on `linkBox`

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/project-creator-card.js
assets/stylesheets/kitten/components/cards/_project-creator-card.scss

Update flexbox on projectCreatorCard

---

CHANGELOG.md
assets/javascripts/kitten/components/lines/info-lines.js
assets/stylesheets/kitten/components/lines/_info-lines.scss

Update alignment on `InfoLines`

---

CHANGELOG.md
app/views/kitten/components/typography/text.html.erb
assets/javascripts/kitten/components/typography/text.js
assets/stylesheets/kitten/helpers/typography/_font-size.scss
assets/stylesheets/kitten/utilities/text/_color.scss
assets/stylesheets/kitten/utilities/text/_size.scss

Closes https://github.com/KissKissBankBank/kitten/issues/865.

Update Text component

---

CHANGELOG.md
assets/javascripts/kitten/components/form/location-input.js
assets/javascripts/kitten/karl/form/location-input.js
assets/stylesheets/kitten/components/form/_location-input.scss

Fix border autocomplete location-input

---

CHANGELOG.md
assets/stylesheets/kitten/components/lists/_tag-list.scss

Kitten V2 - Update `TagList` component.

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button-question-mark-icon.js
assets/javascripts/kitten/components/tooltips/static-tooltip.js
assets/javascripts/kitten/components/tooltips/tooltip-new.js
assets/javascripts/kitten/components/tooltips/tooltip.js
assets/stylesheets/kitten/components/tooltips/_static-tooltip.scss
assets/stylesheets/kitten/components/tooltips/_tooltip-new.scss
assets/stylesheets/kitten/components/tooltips/_tooltip.scss

Kitten V2 - Update `Tooltip` and `StaticTooltip` components

---

CHANGELOG.md
assets/javascripts/kitten/components/images/image-cropper.js
assets/javascripts/kitten/components/images/image-cropper.test.js
assets/javascripts/kitten/components/uploaders/simple-uploader.js
assets/javascripts/kitten/components/uploaders/simple-uploader.test.js
assets/javascripts/kitten/components/uploaders/uploader.js
assets/javascripts/kitten/components/uploaders/uploader.test.js

Add `deletable` prop to display delete button in `SimpleUploader`

---

KARL_CHANGELOG.md
assets/stylesheets/kitten/components/typography/_body-copy.scss

Remove `font-weight` duplicate

---

CHANGELOG.md
assets/javascripts/kitten/components/uploaders/simple-uploader.js
assets/javascripts/kitten/components/uploaders/simple-uploader.test.js
assets/stylesheets/kitten/components/uploaders/_simple-uploader.scss

[Dépotoir] - Center btn Upload img

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/tab-bar.js
assets/stylesheets/kitten/components/navigation/_tab-bar.scss

Kitten V2 - Update `TabBar` component

---

CHANGELOG.md
app/views/kitten/components/form/select.html.erb
assets/stylesheets/kitten/components/form/_select.scss

Kitten V2 - Update select

---

CHANGELOG.md
assets/stylesheets/kitten/components/steppers/_stepper.scss

Kitten V2 - Update font `Stepper` component

---

CHANGELOG.md
KARL_CHANGELOG.md
assets/stylesheets/kitten/components/typography/_body-copy.scss

Kitten V2 - Update `body` font with Kitten V2

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button-question-mark-icon.js
assets/javascripts/kitten/components/buttons/button-question-mark-icon.test.js

Styleguide V2 - Update `modifier` on `ButtonQuestionMarkIcon`

---

CHANGELOG.md
assets/javascripts/kitten/components/notifications/alert.js
assets/javascripts/kitten/components/notifications/alert.test.js

Add `onClose` prop to `Alert` component

---

CHANGELOG.md
assets/stylesheets/kitten/components/form/_form-info.scss

Styleguide V2 - Update error `line-height` on `FormInfo` component.

---

CHANGELOG.md
KARL_CHANGELOG.md
assets/stylesheets/kitten/components/grid/_side-grid.scss

Fix responsive children in `SideGrid` component

---

CHANGELOG.md
assets/stylesheets/kitten/components/form/_form-composer.scss

Update marge on `FormComposer` component.

---

CHANGELOG.md
app/views/kitten/components/form/label.html.erb
assets/javascripts/kitten/components/form/label.js
assets/javascripts/kitten/components/form/label.test.js

Update `focusId` on `Label` component

---

CHANGELOG.md
Gemfile.lock
assets/javascripts/kitten/components/form/select-with-state.js
assets/javascripts/kitten/components/form/select-with-state.test.js
spec/dummy/client/yarn.lock

PR qui permet de ne pas envoyer un `[]` quand on supprime la sélection.
TODO:

Fix value when i remove selection in `SelectWithState` component

---

CHANGELOG.md
KARL_CHANGELOG.md
app/views/layouts/kitten/application.html.erb
assets/stylesheets/kitten/_utilities.scss
assets/stylesheets/kitten/utilities/text/_anti-aliasing.scss
spec/dummy/client/stylesheets/kitten/_utilities.scss

Add anti-aliasing

---

KARL_CHANGELOG.md
package.json
yarn.lock

Update react-select version

---

CHANGELOG.md
assets/javascripts/kitten/components/images/image-cropper.js

Update marge on `ImageCropper` component.

---

KARL_CHANGELOG.md
assets/javascripts/kitten/components/cards/project-creator-card.js
assets/javascripts/kitten/components/cards/project-similar-card.js
assets/javascripts/kitten/karl/cards/project-card.js

Update project-card colors example

---

CHANGELOG.md
KARL_CHANGELOG.md
app/views/kitten/components/typography/title.html.erb
assets/javascripts/kitten/components/cards/project-card.js
assets/javascripts/kitten/components/cards/project-card.test.js
assets/javascripts/kitten/components/cards/project-similar-card.js
assets/javascripts/kitten/karl/cards/project-card.js
assets/stylesheets/kitten/components/typography/_title.scss

Closes #944
Change également le title de `ProjectCard` et `ProjectSimilarCard`
TODO:

Add new size on `Title` component.

---

CHANGELOG.md
assets/stylesheets/kitten/_default-config.scss
assets/stylesheets/kitten/components/tours/_tour.scss
assets/stylesheets/kitten/helpers/button/_colors.scss

Add new colors error

---

CHANGELOG.md
assets/stylesheets/kitten/components/form/_text-input.scss

Styleguide V2 - Update hover border-color on `TextInput`

---

CHANGELOG.md
KARL_CHANGELOG.md
app/views/kitten/components/links/link-list.html.erb
assets/javascripts/kitten/components/links/link-list.js
assets/javascripts/kitten/components/links/link-list.test.js
assets/javascripts/kitten/karl/links/link-list.js
assets/stylesheets/kitten/components/links/_link-list.scss
spec/dummy/client/entries/app-kitten.js
spec/dummy/client/stylesheets/kitten/_components.scss

Styleguide V2 - Update `LinkList`

---

CHANGELOG.md
assets/javascripts/kitten/components/links/link-list.test.js

Styleguide V2 - Fix `LinkList` test

---

CHANGELOG.md
KARL_CHANGELOG.md
app/views/kitten/components/cards/simple-card.html.erb
assets/javascripts/kitten/components/cards/simple-card.js
assets/javascripts/kitten/components/cards/simple-card.test.js
assets/javascripts/kitten/hoc/card.js
assets/javascripts/kitten/hoc/card.test.js
assets/stylesheets/kitten/components/cards/_card.scss
lib/kitten/configuration.rb
spec/dummy/client/entries/app-kitten.js

Add SimpleCard component

---

assets/javascripts/kitten/components/heroes/hero.js

Permet de changer les couleurs de fond et du texte sur le bloc de contenu.
TODO:

Add color props to Hero component

---

CHANGELOG.md
assets/stylesheets/kitten/components/headers/_header.scss

Update header style

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/article-card.js
assets/javascripts/kitten/components/cards/article-card.test.js
assets/javascripts/kitten/components/cards/simple-card.js
assets/javascripts/kitten/components/cards/simple-card.test.js

Add `titleProps` prop to `ArticleCard` and `SimpleCard` components

---

CHANGELOG.md
assets/stylesheets/kitten/components/buttons/_button-icon.scss

Add `tiny` size on `k-ButtonIcon--signup` and `k-ButtonIcon--phone`.

---

CHANGELOG.md
assets/stylesheets/kitten/components/buttons/_button.scss

Change font-size big buttons

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/article-card.js

Fix prop warning to ArticleCard

---

KARL_CHANGELOG.md
app/views/kitten/branding/colors.html.erb

Closes #1030
Screenshot:
TODO:

Update `Blue Light MDC` color.

---

CHANGELOG.md
assets/javascripts/kitten/components/popovers/popover.js
assets/stylesheets/kitten/components/buttons/_button-icon.scss
assets/stylesheets/kitten/components/modals/modal.scss
assets/stylesheets/kitten/components/popovers/_popover.scss
assets/stylesheets/kitten/components/tours/_tour.scss

Update css `Tour`, `Popover` and `Modal` components.

---

assets/javascripts/kitten/components/cards/project-card.test.js
assets/javascripts/kitten/components/images/image-with-caption.test.js
assets/javascripts/kitten/components/navigation/horizontal-nav.test.js
bin/test

Corrige quelques warnings présent dans les tests.
TODO:

Fix some test warnings

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/carousel.js
assets/javascripts/kitten/karl/modals/modal.js

Fix viewport states update on `Carousel` and `Modal` components

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/container.js

Fix viewport states update on Container component

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/social-button-icon-words.test.js

Correct `SocialButtonIconWords` test.

---

CHANGELOG.md
assets/javascripts/kitten/components/links/link-list.js
assets/javascripts/kitten/components/links/link-list.test.js
assets/javascripts/kitten/karl/footer/footer-kisskiss.js
assets/stylesheets/kitten/components/links/_link-list.scss

Add `lineHeight` and `itemMargin` props on `LinkList` component

---

CHANGELOG.md
assets/javascripts/kitten/karl/footer/footer-kisskiss.js

Add underline on paragraph link

---

assets/javascripts/kitten/karl/footer/footer-kisskiss.js

Fix grid network footer

---

assets/javascripts/kitten/karl/footer/footer-kisskiss.js

Fix `max-width` on  `TextInputWIthButton`.
Screenshot:
TODO:

Little fix footer

---

CHANGELOG.md
app/views/kitten/components/buttons/tag-button.html.erb
assets/javascripts/kitten/components/buttons/tag-button.js
assets/javascripts/kitten/components/buttons/tag-button.test.js
assets/stylesheets/kitten/components/buttons/_tag-button.scss
assets/stylesheets/kitten/helpers/_button.scss
assets/stylesheets/kitten/helpers/button/_base.scss
assets/stylesheets/kitten/helpers/button/_border.scss
assets/stylesheets/kitten/helpers/button/_colors-tag-button.scss

Closes #1056 
Screenshot:
TODO:

Add props on tagButton

---

assets/stylesheets/kitten/helpers/button/_colors-tag-button.scss

Remove colors-tag-button comment

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/article-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card.js
package.json
spec/dummy/client/yarn.lock
yarn.lock

Mise à jour de Radium qui fixe un bug au niveau du composant `StyleRoot`.

Update Radium version

---

CHANGELOG.md
assets/stylesheets/kitten/components/buttons/_tag-button.scss

[Browsing] Fix font-size on TagButton component

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/pagination.js
assets/javascripts/kitten/components/navigation/pagination.test.js

Add event to onClick `Pagination`

---

CHANGELOG.md
KARL_CHANGELOG.md
app/views/kitten/branding/colors.html.erb
assets/javascripts/kitten/components/cards/project-card.js
assets/javascripts/kitten/components/navigation/__snapshots__/pagination.test.js.snap
assets/javascripts/kitten/constants/colors-config.js
assets/javascripts/kitten/karl/cards/project-card.js
assets/stylesheets/kitten/_default-config.scss
assets/stylesheets/kitten/helpers/button/_color-base.scss
assets/stylesheets/kitten/helpers/button/_colors-tag-button.scss
assets/stylesheets/kitten/helpers/button/_colors.scss

DONE
Mise à jour des couleurs `primary` et suppression d'une ancienne couleur.
TODO:

Update primary colors

---

CHANGELOG.md
KARL_CHANGELOG.md
app/views/kitten/components/buttons/button.html.erb
app/views/kitten/components/buttons/icon-button-with-words.html.erb
app/views/kitten/components/buttons/icon-button.html.erb
app/views/kitten/components/buttons/tag-button.html.erb
assets/stylesheets/kitten/components/buttons/_button-icon.scss
assets/stylesheets/kitten/components/buttons/_button.scss
assets/stylesheets/kitten/helpers/button/_colors.scss

Create `Azote` modifier for all buttons

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card.js

[Browsing] Add progress percentage in `CrowdfundingCard`

---

CHANGELOG.md
app/views/kitten/components/cards/crowdfunding-card.html.erb
assets/javascripts/kitten/components/cards/__snapshots__/article-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card.js

[Browsing] Fix CrowdfundingCard

---

CHANGELOG.md
app/views/kitten/components/form/checkbox.html.erb
app/views/kitten/components/form/form-actions.html.erb
app/views/kitten/components/form/form-amount-and-currency.html.erb
app/views/kitten/components/form/form-phone-number.html.erb
app/views/kitten/components/form/label.html.erb
app/views/kitten/components/form/location-input.html.erb
app/views/kitten/components/form/radio-button.html.erb
app/views/kitten/components/form/select.html.erb
app/views/kitten/components/form/switch.html.erb
assets/javascripts/kitten/components/form/checkbox.js
assets/stylesheets/kitten/components/form/_checkbox.scss

DONE
- Clean du HTML dans le dossier `Form`
- Nouvelle indentation sur `Checkbox`
- Place le checkbox en top et non centré sur son contenu.
Screenshot:
TODO:

[Connexion/Inscription] Update `Checkbox` component

---

CHANGELOG.md
assets/stylesheets/kitten/components/buttons/_tag-button.scss
assets/stylesheets/kitten/helpers/button/_colors-tag-button.scss

Fix `TagButton` colors.

---

CHANGELOG.md
app/views/kitten/components/meters/progress.html.erb
assets/javascripts/kitten/components/meters/progress.js
assets/javascripts/kitten/components/meters/progress.test.js

Corrige un bug d'affichage quand le montant atteint est supérieur à 100%.

[Browsing] Fix Progress value

---

KARL_CHANGELOG.md
app/assets/stylesheets/kitten/karl/_layout.scss

Update `background-color` on the styleguide.

---

CHANGELOG.md
assets/javascripts/kitten/components/notifications/badge.js
assets/stylesheets/kitten/components/notifications/_badge.scss

Manage padding on `k-Badge`.

---

CHANGELOG.md
app/views/kitten/components/cards/crowdfunding-card.html.erb
assets/javascripts/kitten/components/cards/__snapshots__/article-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
assets/javascripts/kitten/components/cards/article-card.test.js
assets/javascripts/kitten/components/cards/crowdfunding-card.js
assets/javascripts/kitten/components/cards/crowdfunding-card.test.js

DOING 
Ajoute les props `backgroundColor` et `color`. Pour permettre de personnaliser la couleur de fond de l'image et la color et positionnement du texte alternatif des images lors du chargement des images.
Closes #1130
TODO:

[Browsing] Add `backgroundColor` prop on `CrowdfundingCard` component.

---

CHANGELOG.md
app/views/kitten/components/cards/crowdfunding-card.html.erb
assets/javascripts/kitten/components/cards/__snapshots__/article-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card.js

Allow `CrowdfundingCard` to have truncated `cardSubTitle`

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/article-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card.js

CF: https://github.com/KissKissBankBank/kisskissbankbank/issues/3101

Fix `CrowdfundingCard` margins

---

CHANGELOG.md
app/views/kitten/components/form/form-info.html.erb
assets/stylesheets/kitten/components/form/_form-info.scss

Add `k-FormInfo__error__link` class and all states.

---

.storybook/preview-head.html

[Storybook] Add noindex meta to prevent robots parsing

---

CHANGELOG.md
assets/javascripts/kitten/karl/notifications/icon-badge.js
assets/stylesheets/kitten/components/notifications/_icon-badge.scss

[ProjectPage] Update IconBadge component

---

CHANGELOG.md
assets/stylesheets/kitten/components/notifications/_icon-badge.scss

Fixe la `min-width` et la `min-height` sur `IconBadge` 
TODO:

Fix size on `IconBadge` component

---

CHANGELOG.md
KARL_CHANGELOG.md
app/views/kitten/components/typography/title.html.erb
assets/javascripts/kitten/components/typography/paragraph.js
assets/javascripts/kitten/components/typography/title.js
assets/javascripts/kitten/components/typography/title.test.js
assets/stylesheets/kitten/components/typography/_title.scss

Add `Italic` props on `Title` component.

---

CHANGELOG.md
assets/javascripts/kitten/hoc/__snapshots__/media-queries.test.js.snap
assets/javascripts/kitten/hoc/media-queries.js
assets/javascripts/kitten/hoc/media-queries.test.js

Update test `media-queries.test.js`
TODO:

Corrige `viewportIsSOrLess` mediaQueries

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/reward-card.test.js.snap
assets/javascripts/kitten/components/cards/reward-card.js
assets/javascripts/kitten/karl/cards/reward-card.js

Add link variable and fix bug margin

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/reward-card.js

Fix reward card custom style

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/reward-card.test.js.snap
assets/javascripts/kitten/components/cards/reward-card.js
assets/javascripts/kitten/karl/cards/reward-card.stories.js

Fix font & missing prop in RewardCard component

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/reward-card.test.js.snap
assets/javascripts/kitten/components/cards/reward-card.js
assets/javascripts/kitten/karl/cards/reward-card.js
assets/javascripts/kitten/karl/cards/reward-card.stories.js

[RewardCard] Cleanup useless prop in `RewardCard` component + fix image height

---

CHANGELOG.md
assets/javascripts/kitten/components/form/comment.js

[Comment] Fix propType warning

---

CHANGELOG.md
app/views/kitten/components/lists/bullet-list.html.erb
assets/javascripts/kitten/components/lists/bullet-list.js
assets/javascripts/kitten/components/lists/bullet-list.test.js
assets/stylesheets/kitten/components/lists/_bullet-list.scss

Create `huge` props on `BulletList` component.

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/contribution-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/donation-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/reward-card.test.js.snap
assets/javascripts/kitten/components/cards/contribution-card.js

Update `renderImage` margin on `ContributionCard` component

---

CHANGELOG.md
assets/javascripts/kitten/components/links/link-list.js

Closes #1230
Screenshot:
TODO:

Add props `others` on `LinkList` component

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card.js

Closes #1234
Screenshot:
TODO:

Fix `title` `min-height` on `CrowdfundingCard` component.

---

CHANGELOG.md
Gemfile.lock

[Stability] Update Gemfile.lock for security vulnerabilities

---

CHANGELOG.md
KARL_CHANGELOG.md
assets/javascripts/kitten/components/form/__snapshots__/comment.test.js.snap
assets/javascripts/kitten/components/form/comment.js
assets/javascripts/kitten/components/form/comment.test.js
assets/javascripts/kitten/karl/form/comment.js

Maquette InVision : https://projects.invisionapp.com/d/main#/console/13789597/297213062/preview
Cette PR permet d'ajouter un petit texte en dessous de la bulle du commentaire. 
Elle permettra sur KissKiss de pouvoir y intégrer des liens pour les porteurs ou les admins (cf. https://github.com/KissKissBankBank/kisskissbankbank/issues/3587), et peut-être à terme indiquer des informations sur des commentaires supprimés (cf. RGPD)

 Add `bottomNotes` prop to `Comment` component

---

CHANGELOG.md
assets/stylesheets/kitten/components/form/_select.scss

Remove `hover` state on `Select-control` class.

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/cart-reward-card.test.js.snap
assets/javascripts/kitten/components/cards/cart-reward-card.js

Update margin on `CartRewardCard` component.

---

CHANGELOG.md
KARL_CHANGELOG.md
assets/javascripts/kitten/components/cards/cart-reward-card.js
assets/javascripts/kitten/components/cards/cart-reward-card.test.js
assets/javascripts/kitten/hoc/media-queries.js
assets/javascripts/kitten/karl/cards/cart-reward-card.js

PR pour désactiver l'animation de fermeture de la card.

[Cart] Add onCloseClick prop to CartRewardCard

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/social-button-icon-words.js
assets/javascripts/kitten/components/buttons/social-button-icon-words.test.js
assets/javascripts/kitten/components/icons/facebook-icon-with-background.js
assets/stylesheets/kitten/components/buttons/_button.scss

Closes #1255 
Screenshot:
TODO:

Create `FacebookIconWithBackground` component.

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/cart-reward-card.test.js.snap
assets/javascripts/kitten/components/cards/cart-reward-card.js
spec/dummy/client/yarn.lock

[Cart] Fix garbage button styles on `CartRewardCard`

---

CHANGELOG.md
assets/stylesheets/kitten/components/form/_text-input-with-button.scss

Ajout d'un padding `right` et `left` sur le button 
TODO:

Add `k-TextInputWithButton__button` padding

---

CHANGELOG.md
assets/javascripts/kitten/components/links/link-list.js
assets/stylesheets/kitten/components/links/_link-list.scss

Add `k-LinkList__item--tripleMargin` marginBottom

---

CHANGELOG.md
KARL_CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/donation-card.test.js.snap
assets/javascripts/kitten/components/cards/donation-card.js
assets/javascripts/kitten/components/form/__snapshots__/text-input-with-unit-form.test.js.snap
assets/javascripts/kitten/components/form/text-input-with-unit-form.js
assets/javascripts/kitten/karl/cards/donation-card.js

Ajout d'une prop `version` pour pouvoir forcer la version de la card.

[DonationCard][TextInputWithUnitForm] Add `version` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/donation-card.test.js.snap
assets/javascripts/kitten/components/cards/donation-card.js
assets/javascripts/kitten/components/form/__snapshots__/text-input-with-unit-form.test.js.snap
assets/javascripts/kitten/components/form/text-input-with-unit-form.js

[DonationCard] Fix `GridCol` size for `tiny` version

---

CHANGELOG.md
KARL_CHANGELOG.md
app/assets/javascripts/kitten/karl.js

Screenshot:
CF:
[KARL_CHANGELOG.md](https://github.com/KissKissBankBank/kitten/blob/master/KARL_CHANGELOG.md#2080---2018-04-27)

Remove undefined `displayShortcut` function

---

CHANGELOG.md
KARL_CHANGELOG.md
app/views/kitten/components/media/embed-player.html.erb
assets/javascripts/kitten/components/media/__snapshots__/embed-player.test.js.snap
assets/javascripts/kitten/components/media/embed-player.js
assets/javascripts/kitten/components/media/embed-player.stories.js
assets/javascripts/kitten/components/media/embed-player.test.js
lib/kitten/configuration.rb
spec/dummy/client/entries/app-kitten.js

[EmbedPlayer] Create `EmbedPlayer` component

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/triptych.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/vertical-card-with-action.test.js.snap
assets/javascripts/kitten/components/cards/vertical-card-with-action.js

[VerticalCardWithAction] Fix missing actions to vertical card with action

---

CHANGELOG.md
Gemfile.lock

Update `ffi` gem to fix CVE vulnerability.

Bump ffi gem version

---

CodeBuildDockerfile
Dockerfile
bin/install

https://bundler.io/v1.16/man/bundle-config.1.html
Sorry :D

[Devops] Do not use bundle --deployment in local

---

Gemfile.lock
spec/dummy/client/yarn.lock

Oups, j'ai oublié de mettre les lockfiles à jour sur #1329.

[Stability] Update lockfiles

---

CHANGELOG.md

Oubli dans le CHANGELOG dans #1335

[Cleaning] Update CHANGELOG

---

CHANGELOG.md
assets/javascripts/kitten/components/links/link-list.js

[LinkList] Corrige `propTypes` definition on `LinkList`.

---

CHANGELOG.md
assets/javascripts/kitten/components/meters/__snapshots__/counter-block.test.js.snap
assets/javascripts/kitten/components/meters/counter-block.js

[CounterBlock] Fix responsive font-size

---

CHANGELOG.md
assets/javascripts/kitten/components/box/__snapshots__/link-box.test.js.snap
assets/javascripts/kitten/components/box/link-box.js

CF: KissKissBankBank/kkbb-lendopolis#1599
Screenshot:
TODO:

[HowToBorrow] Fix animation LinkBox

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/triptych.test.js.snap
assets/javascripts/kitten/components/cards/triptych.js
yarn.lock

Supprime le padding du container du Triptych afin que celui-ci fasse exactement la taille de la grille dans laquelle il est inclus.

[Triptych] Fix triptych margin

---

CHANGELOG.md
assets/javascripts/kitten/helpers/utils/deprecated.js

Sur KissKiss, une erreur apparait au niveau du SSR car il ne trouve pas le type pour le `_owner`. Cette PR fixe ce problème.

[Deprecated] Fix rendering error

---

.circleci/config.yml
.gitignore
.npmignore
package-lock.json
package.json

Bump kitten version to 1.0.0-rc1

---

package-lock.json
package.json

bump kitten version to 1.0.0-rc3

---

CHANGELOG.md
assets/javascripts/kitten/components/box/__snapshots__/link-box.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/article-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/backer-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/cart-reward-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/contribution-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/donation-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/reward-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/simple-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/team-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/triptych.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/vertical-card-with-action.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/vertical-card.test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card.js
assets/javascripts/kitten/components/carousel/__snapshots__/carousel.test.js.snap
assets/javascripts/kitten/components/carousel/__snapshots__/simple-carousel.test.js.snap
assets/javascripts/kitten/components/form/__snapshots__/comment-form.test.js.snap
assets/javascripts/kitten/components/form/__snapshots__/comment.test.js.snap
assets/javascripts/kitten/components/form/__snapshots__/text-input-with-unit-form.test.js.snap
assets/javascripts/kitten/components/layout/marger.js
assets/javascripts/kitten/components/layout/marger.test.js
assets/javascripts/kitten/components/lists/__snapshots__/timeline.test.js.snap
assets/javascripts/kitten/components/meters/__snapshots__/counter-block.test.js.snap
spec/dummy/client/yarn.lock
yarn.lock

[Marger] Use `StyleRoot` only if `top` or `bottom` props are objects

---

README.md
bin/cleanup

Ajoute une commande pour supprimer les modules.

[Tech] Add cleanup file

---

bin/release

[Tech] Compare release with master

---

CHANGELOG.md
KARL_CHANGELOG.md
package.json
src/components/cards/team-card/button-with-tooltip.js
src/components/cards/team-card/phone-icon.js
src/components/cards/team-card/title.js

add built js files for 1.1.1

---

CHANGELOG.md
assets/javascripts/kitten/components/box/__snapshots__/link-box.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/article-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/backer-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/cart-reward-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/contribution-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/crowdfunding-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/donation-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/reward-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/simple-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/team-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/triptych.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/vertical-card-with-action.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/vertical-card.test.js.snap
assets/javascripts/kitten/components/cards/similar-projects-card.test.js
assets/javascripts/kitten/components/carousel/__snapshots__/carousel.test.js.snap
assets/javascripts/kitten/components/carousel/__snapshots__/simple-carousel.test.js.snap
assets/javascripts/kitten/components/form/__snapshots__/comment-form.test.js.snap
assets/javascripts/kitten/components/form/__snapshots__/comment.test.js.snap
assets/javascripts/kitten/components/form/__snapshots__/text-input-with-unit-form.test.js.snap
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/layout/marger.js
assets/javascripts/kitten/components/lists/__snapshots__/timeline.test.js.snap
assets/javascripts/kitten/components/meters/__snapshots__/counter-block.test.js.snap

L'utilisation du HOC de `styled-components` au sein du composant fait perdre le context/state du composant.

Fix Marger context

---

.storybook/preview-head.html

Afin d'être en phase avec nos apps, cette PR ajoute l'anti-aliasing sur StoryBook.

Add antialiasing in Storybook

---

README.md

PR qui retire `yarn` du README.

[Tech] Update README.md

---

CHANGELOG.md
assets/javascripts/kitten/components/accordeon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/accordeon/components/content.js
assets/javascripts/kitten/components/accordeon/components/context.js
assets/javascripts/kitten/components/accordeon/components/header.js
assets/javascripts/kitten/components/accordeon/components/item.js
assets/javascripts/kitten/components/accordeon/index.js
assets/javascripts/kitten/components/accordeon/stories.js
assets/javascripts/kitten/components/accordeon/test.js

New animation on the accordion. ~The animation uses `flex-basis` instead of `max-height`, it might have to be tested against older browsers.~
J'ai ajouté la prop `isAnimated`, qui est `true` par défaut.
Parmi les changements, j'ai modifié le tag du header : du `div` j'ai préféré mettre un `button`, qui est plus adapté au niveau accessibilité, avec l'ajout du rôle ARIA `tab` et de l'information `aria-expanded`. Pour le contenu, c'est un `aria-hidden` qui passe de `true` à `false` selon l'état du composant.
Closes #1475.
TODO:

[Accordeon] Animation

---

CHANGELOG.md
KARL_CHANGELOG.md
package.json
src/components/cards/triptych.js
src/components/carousel/simple-carousel.js
src/components/form/select-with-state.js
src/components/lists/bullet-list.js

[Release] V.1.7.0

---

CHANGELOG.md
assets/javascripts/kitten/components/form/select-with-state.js
package-lock.json
src/components/form/select-with-state.js

Sinon j'ai des problèmes avec Formik :-(

[Field.Select] Add onChange handler when autofill input change

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/simple-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/simple-card/index.js
assets/javascripts/kitten/components/cards/simple-card/stories.js
assets/javascripts/kitten/components/cards/simple-card/test.js
assets/javascripts/kitten/components/cards/team-card.stories.js
package-lock.json

Ajout d'une story pour ce composant avec quelques fixes de design.

[SimpleCard] Stories and fix some styles

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/simple-carousel.js
assets/javascripts/kitten/components/lists/bullet-list.js

Closes #5786
Screenshot:
TODO:

[Pre-Depot] Add some props on `SimpleCarousel` and `BulletList`

---

CHANGELOG.md
package-lock.json
package.json
src/components/carousel/simple-carousel.js
src/components/lists/bullet-list.js
src/components/tours/highlight-halo/index.js

[Release] Add built js files for 1.9.0

---

CHANGELOG.md
assets/javascripts/kitten/components/tours/highlight-halo/__snapshots__/test.js.snap
assets/javascripts/kitten/components/tours/highlight-halo/index.js
assets/javascripts/kitten/components/tours/highlight-halo/stories.js

La prop `onAnimationEnd` spécifie une fonction à exécuter lorsque l'animation se termine.

[HighlightHalo] add `onHaloAnimationEnd` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/__snapshots__/marger.test.js.snap
assets/javascripts/kitten/components/layout/marger.js
assets/javascripts/kitten/components/layout/marger.test.js

Corrige un bug qui ne rend pas de `margin-…: 0` alors qu'il est souhaité.
Closes https://github.com/KissKissBankBank/kitten/issues/1534

[Marger] Fix zero value

---

.circleci/config.yml
README.md
bin/install

Pour que toutes nos apps aient la même commande `bin/install`.

Add bin/install

---

CHANGELOG.md
assets/javascripts/kitten/components/steppers/vertical-stepper/components/status.js
src/components/steppers/vertical-stepper/components/status.js

Change la couleur de fond du statut `disabled` :

[VerticalStepper] Update `disabled` status colors

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/nav-tab-carousel/__snapshots__/nav-tab-carousel.test.js.snap
assets/javascripts/kitten/components/carousel/nav-tab-carousel/components/pagination.js
assets/javascripts/kitten/components/carousel/nav-tab-carousel/nav-tab-carousel.test.js
assets/javascripts/kitten/components/carousel/nav-tab-carousel/stories.js
package-lock.json

[NavTabCarousel] Add `links` prop to `NavTabCarousel` component

---

CHANGELOG.md
assets/javascripts/kitten/components/form/text-input-with-button.stories.js
assets/javascripts/kitten/components/form/text-input-with-button/index.js
assets/javascripts/kitten/components/form/text-input-with-button/stories.js
assets/javascripts/kitten/components/form/text-input-with-button/test.js
assets/stylesheets/kitten/components/form/_text-input-with-button.scss

[TextInputWithButton] Fix button positioning, from absolute to flex

---

CHANGELOG.md
package-lock.json
package.json
src/components/carousel/carousel.js
src/components/carousel/carousel/carousel.js
src/components/carousel/carousel/components/carousel-inner.js
src/components/carousel/carousel/components/carousel-page.js
src/components/date-picker/components/navbar.js
src/components/date-picker/index.js
src/components/form/select-with-state.js
src/components/form/text-input-with-button/index.js
src/components/pages/markdown/components/heading.js
src/components/pages/markdown/components/link.js
src/components/pages/markdown/components/list.js
src/components/pages/markdown/components/paragraph.js
src/components/pages/markdown/index.js
src/helpers/utils/range.js

add built js files for 1.18.0

---

CHANGELOG.md
package-lock.json
package.json
src/components/pages/markdown/components/heading.js
src/components/pages/markdown/components/link.js

add built js files for 1.18.1

---

.github/PULL_REQUEST_TEMPLATE.md

[Misc] Add Browserstack in PR template

---

CHANGELOG.md
package-lock.json
package.json
src/components/modals/modal/index.js

add built js files for 1.19.0

---

CHANGELOG.md
package-lock.json
package.json
src/components/cards/simple-card/components/image.js
src/components/cards/simple-card/components/paragraph.js
src/components/cards/simple-card/components/subtitle.js
src/components/cards/simple-card/components/title.js
src/components/cards/simple-card/index.js

add built js files for 1.20.0

---

CHANGELOG.md
package-lock.json
package.json
src/components/cards/simple-card/index.js
src/components/videos/video/index.js
src/helpers/react/react-elements.js

add built js files for 1.21.0

---

CHANGELOG.md
assets/javascripts/kitten/components/lists/icon-list/__snapshots__/test.js.snap
assets/javascripts/kitten/components/lists/icon-list/components/icon.js
assets/javascripts/kitten/components/lists/icon-list/components/item.js
assets/javascripts/kitten/components/lists/icon-list/index.js
assets/javascripts/kitten/components/lists/icon-list/stories.js
assets/javascripts/kitten/components/lists/icon-list/test.js
assets/javascripts/kitten/components/steppers/vertical-stepper/__snapshots__/test.js.snap
assets/javascripts/kitten/components/steppers/vertical-stepper/components/step.js

Création d'un nouveau composant de `List` ressemblant grandement à `VerticalStepper`. Pour l'instant il y a pas mal de duplication. À terme j'aimerai harmoniser les `List` de Kitten pour permettre de gérer la plupart de nos cas.

Add `IconList`

---

CHANGELOG.md
package-lock.json
package.json
src/components/form/field/components/label.js
src/components/form/field/components/password.js
src/components/form/field/field.examples.js
src/components/form/field/index.js

Screenshot:
J'ai ce message d'erreur lors de la création de la PR. Sachant que le fichier src `password.js` vient d'être créé, est-ce que je l'ignore?

add built js files for 1.24.0

---

CHANGELOG.md
assets/javascripts/kitten/constants/colors-config.js

J'en ai besoin pour le background du Petit Plus.
(cf https://share.goabstract.com/f1fc0b2e-3339-4a45-9b3f-fa9793bad8cd)

Add new background color backgroundLightRed

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/field/components/input.js
assets/javascripts/kitten/components/form/field/field.examples.js
assets/javascripts/kitten/components/form/field/field.stories.js
src/components/form/field/components/input.js
src/components/form/field/field.examples.js

Ajoute la possibilité de faire des input de type `unit` avec le `Field.Input`

Add unit system on Field.Input

---

CHANGELOG.md
assets/stylesheets/kitten/components/lists/_bullet-list.scss

[BulletList] Fix bullet vertical align

---

CHANGELOG.md
assets/javascripts/kitten/components/form/switch.js
assets/stylesheets/kitten/components/form/_switch.scss
src/components/form/switch.js

+ Quelques modifs sur le style (couleur et transitions)

[Switch] Add handling of others props

---

CHANGELOG.md
package-lock.json
package.json
src/components/form/switch.js

add built js files for v1.26.0

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button/button.js
assets/javascripts/kitten/components/buttons/button/stories.js
assets/javascripts/kitten/components/buttons/button/test.js

Add `Radius` props on Button component

---

bin/release

[Feature] Add `install` command to `bin/release` script

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/scrollable-container/__snapshots__/test.js.snap
assets/javascripts/kitten/components/grid/scrollable-container/index.js
assets/javascripts/kitten/components/grid/scrollable-container/stories.js
assets/javascripts/kitten/components/grid/scrollable-container/styled.js
assets/javascripts/kitten/components/grid/scrollable-container/test.js
package-lock.json
package.json

[ScrollableContainer] Refactor + new props `shadowColor`, `backgroundColor`

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/sticky-container/__snapshots__/test.js.snap
assets/javascripts/kitten/components/grid/sticky-container/index.js

[StickyContainer] Always run `setSticky` for `isSticky === 'always'`

---

CHANGELOG.md
assets/javascripts/kitten/components/videos/video/index.js

Fix le plein écran quand l'attribut `controls` est utilisé.

[Video] Fix `cover` with used `controls` on Video.

---

CHANGELOG.md
assets/javascripts/kitten/components/videos/video/index.js
assets/javascripts/kitten/components/videos/video/stories.js

[Video] Fix `cursor` for `poster` Video attribute.

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/scrollable-container/__snapshots__/test.js.snap
assets/javascripts/kitten/components/grid/scrollable-container/index.js
assets/javascripts/kitten/components/grid/scrollable-container/styled.js

[ScrollableContainer] Rework container shadow display

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/scrollable-container/__snapshots__/test.js.snap
assets/javascripts/kitten/components/grid/scrollable-container/styled.js

[Fix] `ScrollableContainer` style fixes

---

CHANGELOG.md
assets/javascripts/kitten/components/steppers/vertical-stepper/components/step.js
src/components/steppers/vertical-stepper/components/step.js

PR qui permet d'avoir les styles d'un lien quand il y a un `onClick` sur l'élément.

Add link styles when `VerticalStepper.Step` has `onClick` attribute

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/cart-reward-card.js
src/components/cards/cart-reward-card.js

- Ajout d'une prop pour changer le tag de la description.

[CartRewardCard] Add `descriptionTag` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/accessibility/visually-hidden/__snapshots__/test.js.snap
assets/javascripts/kitten/components/accessibility/visually-hidden/index.js
assets/javascripts/kitten/components/accessibility/visually-hidden/stories.js
assets/javascripts/kitten/components/accessibility/visually-hidden/test.js

More info at https://www.sarasoueidan.com/blog/accessible-icon-buttons/#technique-1-accessible-visually-hidden-text
TODO:

[A11y] New `VisuallyHidden` component for Accessibility.

---

assets/javascripts/kitten/index.js

[Fix] Add export for `VisuallyHidden`

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/reward-edition/stories.js

Update `rewardEdition` stories with new `ExpandBoard`

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button-group/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button/button.js
assets/javascripts/kitten/components/buttons/button/helpers/modifier-styles.js
assets/javascripts/kitten/components/buttons/button/stories.js
assets/javascripts/kitten/components/buttons/button/test.js
assets/javascripts/kitten/components/cards/reward-edition/__snapshots__/test.js.snap
assets/javascripts/kitten/components/expandable/expand-board/__snapshots__/test.js.snap
package-lock.json

[Button] Add checked icon

---

CHANGELOG.md
assets/javascripts/kitten/helpers/utils/lazy-hook.js
assets/javascripts/kitten/helpers/utils/lazy-observer.js
assets/javascripts/kitten/hoc/with-lazy.js
assets/javascripts/kitten/karl/lazy/img-with-lazy.js
assets/javascripts/kitten/karl/lazy/lazy-hoc.js
assets/javascripts/kitten/karl/lazy/lazy-hook.js
assets/javascripts/kitten/karl/lazy/stories.js
package-lock.json

[Lazy] Add Lazy utils

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/__snapshots__/simple-carousel.test.js.snap
assets/javascripts/kitten/components/carousel/simple-carousel.js
assets/javascripts/kitten/karl/carousel/simple-carousel.js
package-lock.json

[Fix] `SimpleCarousel` accessibility fixes

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/carousel/carousel.js
assets/javascripts/kitten/components/carousel/carousel/stories.js
assets/javascripts/kitten/components/carousel/carousel/test.js

[Fix] Remove `Carousel` warning

---

assets/javascripts/kitten/components/text-copy/index.js

[TextCopy] Import Text component from right path

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/donation-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/date-picker/__snapshots__/date-picker.test.js.snap
assets/javascripts/kitten/components/form/text-input-with-unit-form/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-unit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-unit/index.js
assets/javascripts/kitten/components/form/text-input-with-unit/test.js

[TextInput] Fix Regression `TextInputWithUnit` component

---

assets/javascripts/kitten/components/form/text-input-with-limit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-limit/index.js
src/components/form/text-input-with-limit/index.js

Petit clean du `TextInputWithLimit`

fix text-input-with-limit

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/team-card.test.js.snap
assets/javascripts/kitten/components/icons/email-icon.js
assets/javascripts/kitten/components/icons/email-icon/index.js
assets/javascripts/kitten/components/icons/export-icon/index.js
assets/javascripts/kitten/components/icons/icons.stories.js

[KissbankersPage] Update `EmailIcon` and  create `ExportIcon` components

---

assets/javascripts/kitten/components/icons/email-icon/index.js

[Fix] Fix warning `EmailIcon`

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/contribution-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/reward-card.test.js.snap
assets/javascripts/kitten/components/cards/reward-card.js
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/karl/cards/reward-card.stories.js

Parfois la `RewardCard` se monte dans un contexte qui nécessite l'absence de border. 
J'ai aussi passé le composant sous `styled-component`.

Add `withoutBorder` prop and passing `RewardCard` to `styled-component`

---

CHANGELOG.md
assets/javascripts/kitten/components/accordeon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/accordeon/components/content.js
assets/javascripts/kitten/components/accordeon/stories.js

[Accordeon] Refactor `isAnimated={false}` styles

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/adaptable-grid/__snapshots__/test.js.snap
assets/javascripts/kitten/components/grid/adaptable-grid/index.js

[AdaptableGrid] Fix negative container margins

---

CHANGELOG.md
assets/javascripts/kitten/components/icons/double-arrow-icon.js
assets/javascripts/kitten/components/icons/icons.stories.js

Closes #1715.
Screenshot:
TODO:

[Kissbankers] `DoubleArrowIcon` component

---

CHANGELOG.md
assets/javascripts/kitten/components/tables/list-table/__snapshots__/test.js.snap
assets/javascripts/kitten/components/tables/list-table/components/body.js
assets/javascripts/kitten/components/tables/list-table/components/col.js
assets/javascripts/kitten/components/tables/list-table/components/context.js
assets/javascripts/kitten/components/tables/list-table/components/header.js
assets/javascripts/kitten/components/tables/list-table/components/row.js
assets/javascripts/kitten/components/tables/list-table/index.js
assets/javascripts/kitten/components/tables/list-table/stories.js
assets/javascripts/kitten/components/tables/list-table/test.js

[ListTable] New `ListTable` component

---

CHANGELOG.md
assets/javascripts/kitten/components/tables/list-table/__snapshots__/test.js.snap
assets/javascripts/kitten/components/tables/list-table/components/col.js
assets/javascripts/kitten/components/tables/list-table/stories.js

[ListTable] Default col style to Flex.

---

assets/javascripts/kitten/components/cards/similar-projects-card.js
assets/javascripts/kitten/components/carousel/carousel-inner.js
assets/javascripts/kitten/components/carousel/carousel/components/carousel-inner.js
assets/javascripts/kitten/components/dropdowns/dropdown.js
assets/javascripts/kitten/helpers/utils/deprecated.js
package.json

Pour éviter les warnings dans kisskisshihihihi

React 16.9

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/pagination/__snapshots__/test.js.snap
assets/javascripts/kitten/components/navigation/pagination/index.js

[Pagination] - Update `Text` component styles.

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/adaptable-grid/__snapshots__/test.js.snap
assets/javascripts/kitten/components/grid/adaptable-grid/index.js

[AdaptableGrid] Fix `Grid` width

---

CHANGELOG.md
assets/javascripts/kitten/components/date-picker/standalone-range/__snapshots__/test.js.snap
assets/javascripts/kitten/components/date-picker/standalone-range/components/navbar.js
assets/javascripts/kitten/components/date-picker/standalone-range/index.js
assets/javascripts/kitten/components/date-picker/standalone-range/stories.js

Les `defaultProps` du composant nous empêchaient de le custom.
Screenshot:
TODO:

[StandaloneRangeDatePicker] Clean defaultProps

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button/button.js
assets/javascripts/kitten/components/buttons/button/test.js
assets/javascripts/kitten/components/date-picker/standalone-range/__snapshots__/test.js.snap
assets/javascripts/kitten/components/expandable/expand-board/__snapshots__/test.js.snap

[Button] Export `ICON`, `ICON_TINY` and `ICON_BIG` css from `Button`.

---

CHANGELOG.md
assets/javascripts/kitten/components/form/text-input-with-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-icon/index.js
assets/javascripts/kitten/components/form/text-input-with-icon/stories.js
assets/javascripts/kitten/components/form/text-input-with-icon/test.js

[TextInput] Update `TextInputWithIcon`

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/tag-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/tag-button/index.js

[TagButton] Update `active` pseudo-class

---

CHANGELOG.md
assets/javascripts/kitten/components/tables/list-table/__snapshots__/test.js.snap
assets/javascripts/kitten/components/tables/list-table/components/row.js

[ListTable] Fix weird bottom margin bug on KissKiss

---

CHANGELOG.md
assets/stylesheets/kitten/_utilities.scss
assets/stylesheets/kitten/utilities/cursor/_cursor.scss

[Feature] New `Cursor` CSS utility

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/field/components/label.js

[Field] Remove default `font-size` on `Field.Label`.

---

assets/javascripts/kitten/components/loaders/loaders.stories.js

Ajout de stories pour les composants Loader

Add loader stories

---

CHANGELOG.md
assets/javascripts/kitten/components/form/autocomplete/index.js
assets/javascripts/kitten/components/form/autocomplete/stories.js

Permet de customiser la mise à jour des données affichées dans l'`<Autocomplete />`

Add updateStrategy to <Autocomplete />

---

CHANGELOG.md
assets/javascripts/kitten/components/form/autocomplete/index.js

Petit fix qui met à jour la liste des items lorsque la prop change.

[Autocomplete] Update suggestions when items prop changes

---

CHANGELOG.md
assets/images/icons/checked-indeterminate.svg
assets/javascripts/kitten/components/form/checkbox.js
assets/javascripts/kitten/components/form/checkbox.stories.js
assets/stylesheets/kitten/components/form/_checkbox.scss

[Checkbox] Add `indeterminate` props and style

---

CHANGELOG.md
assets/javascripts/kitten/components/images/image-cropper.js
assets/javascripts/kitten/karl/form/location-input.js
assets/javascripts/kitten/karl/layout/line.js
assets/javascripts/kitten/karl/layout/side-layout.js

- Passe la size de `Label`  de `tiny` à `micro`
Screenshot:
TODO:

[Label] Update `Label` styles

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/components/title.js
assets/javascripts/kitten/components/cards/crowdfunding-card/stories.js

[CrowdfundingCardWidget] Update truncated title.

---

CHANGELOG.md
assets/stylesheets/kitten/utilities/background/_background-color.scss

- Ajout de l'utilitaire `.k-u-background-color-primary6`

[Utility] Add `.k-u-background-color-primary6` utility

---

assets/javascripts/kitten/components/cards/crowdfunding-card/components/progress.js

[CrowdfundingCard] Update defaultProps

---

CHANGELOG.md
package-lock.json
package.json
src/components/cards/article-card.js
src/components/cards/crowdfunding-card/components/button.js
src/components/cards/crowdfunding-card/components/progress.js
src/components/cards/crowdfunding-card/components/state.js
src/components/cards/crowdfunding-card/components/subtitle.js
src/components/cards/crowdfunding-card/components/title.js
src/components/cards/crowdfunding-card/index.js
src/components/cards/crowdfunding-card/widget/index.js
src/components/icons/copy-icon/index.js
src/components/icons/embed-icon/index.js

[Release] Kitten V2.36.0

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/backer-card.test.js.snap
assets/javascripts/kitten/components/cards/backer-card.js

[BackerCard] Style fixes

---

CHANGELOG.md
assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-button/index.js
assets/javascripts/kitten/components/form/text-input-with-button/test.js

[TextInputWithButton] Add `buttonProps` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/form/toggle-switch/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/toggle-switch/index.js
assets/javascripts/kitten/components/form/toggle-switch/stories.js
assets/javascripts/kitten/components/form/toggle-switch/test.js

[ToggleSwitch] Add `activecolor` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/donation-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/date-picker/__snapshots__/date-picker.test.js.snap
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/password-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-button/index.js
assets/javascripts/kitten/components/form/text-input-with-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-limit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-unit-form/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-unit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input/index.js

[TextInput] Invalid attribute style fix

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/crowdfunding-card/components/title.js

[CrowdfundingCard] Update `stateDay` propTypes.

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/components/title.js

[CrowdfundingCardWidget] Update PropTypes

---

src/components/cards/crowdfunding-card/components/title.js

[CrowdfundingCardWidget] Update title.js

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/components/title.js
assets/javascripts/kitten/components/cards/crowdfunding-card/stories.js
assets/javascripts/kitten/components/cards/crowdfunding-card/test.js
assets/javascripts/kitten/components/cards/crowdfunding-card/widget/index.js
assets/javascripts/kitten/karl/widget/components/widget-card.js

[CrowdfundingCardWidget] Delete `stateDay` and update `dayCounter` 

---

CHANGELOG.md
package-lock.json
package.json
src/components/cards/crowdfunding-card/components/image.js
src/components/cards/crowdfunding-card/components/informations.js
src/components/cards/crowdfunding-card/components/progress.js
src/components/cards/crowdfunding-card/components/state.js
src/components/cards/crowdfunding-card/components/subtitle.js
src/components/cards/crowdfunding-card/components/title.js
src/components/cards/crowdfunding-card/index.js
src/components/cards/crowdfunding-card/widget/index.js

add built js files for 2.39.0

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/components/title.js

[CrowdfundingCardWidget] Update styles on component.

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/components/informations.js
assets/javascripts/kitten/components/cards/crowdfunding-card/components/progress.js
assets/javascripts/kitten/components/cards/crowdfunding-card/components/title.js

[CrowdfundingCard] Littles styles fixes. 

---

CHANGELOG.md
package-lock.json
package.json
src/components/cards/crowdfunding-card/components/informations.js
src/components/cards/crowdfunding-card/components/progress.js
src/components/cards/crowdfunding-card/components/title.js

add built js files for 2.40.1

---

CHANGELOG.md
assets/javascripts/kitten/components/meters/progress/index.js
package-lock.json
src/components/meters/progress/index.js

- Force la mise à jour du state quand la prop `value` change à la place de le faire seulement 1 fois au mount
- Corrige un bug en cas de valeur négative

[Progress] Re-render when value is updated

---

assets/javascripts/kitten/components/form/field/components/select.js
package-lock.json

J'ai lancé la commande `npm audit fix` pour corriger des failles de sécu potentielles.
J'ai aussi fait un mini refacto du Select.

Fix security issues

---

CHANGELOG.md
assets/javascripts/kitten/components/icons/gift-icon/index.js
assets/javascripts/kitten/components/icons/icons.stories.js

[Icon] Create `GiftIcon`

---

CHANGELOG.md
assets/javascripts/kitten/helpers/utils/intersection-hook.js
assets/javascripts/kitten/helpers/utils/intersection-observer.js
assets/javascripts/kitten/helpers/utils/lazy-observer.js
assets/javascripts/kitten/karl/intersection-observer/stories.js
assets/javascripts/kitten/karl/lazy/img-with-lazy.js
assets/javascripts/kitten/karl/lazy/lazy-hook.js
assets/javascripts/kitten/karl/lazy/stories.js

[Helpers] Add new `IntersectionObserverClass`

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/components/subtitle.js

- Retire le style du composant `Truncate` sur le subtitle.
- Ajoute la possibilité de passer sur 3 lignes le subtitle.

[CrowdfundingCardWidget] Update subtitle's truncate

---

CHANGELOG.md
package-lock.json
package.json
src/components/cards/crowdfunding-card/components/subtitle.js
src/components/dropdowns/user-menu.js

add built js files for 2.41.1

---

CHANGELOG.md
assets/javascripts/kitten/components/heroes/hero.js
assets/javascripts/kitten/components/heroes/hero.stories.js

[Hero] Fix `StyleRoot` place

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button/button.js
assets/javascripts/kitten/components/buttons/button/stories.js
assets/javascripts/kitten/components/buttons/button/test.js
assets/javascripts/kitten/components/date-picker/standalone-range/__snapshots__/test.js.snap

[Button] fluidity on icon buttons 🔁

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button-group/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button/button.js
assets/javascripts/kitten/components/buttons/checkable-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/reward-edition/__snapshots__/test.js.snap
assets/javascripts/kitten/components/date-picker/standalone-range/__snapshots__/test.js.snap
assets/javascripts/kitten/components/expandable/expand-board/__snapshots__/test.js.snap
assets/javascripts/kitten/components/popovers/simple-popover/__snapshots__/test.js.snap

[Button] Remove underline on `:hover` 🖋

---

CHANGELOG.md
assets/javascripts/kitten/components/icons/edit-icon/index.js
assets/javascripts/kitten/components/icons/icons.stories.js

[Icon] Create `EditIcon`

---

CHANGELOG.md
package-lock.json
package.json
src/components/icons/edit-icon/index.js

add built js files for 2.44.0

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/reward-edition/components/header.js
assets/javascripts/kitten/components/cards/reward-edition/stories.js

[RewardEdition] Add boolean on `garbageButton`

---

CHANGELOG.md
package-lock.json
package.json
src/components/cards/reward-edition/components/header.js

add built js files for 2.45.0

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/__snapshots__/button-image-with-text-and-badge.test.js.snap
assets/javascripts/kitten/components/buttons/button-image-with-text-and-badge.js
assets/javascripts/kitten/components/buttons/button-image-with-text-and-badge.test.js

Closes #.
Screenshot:
spécial pour @Morgan-jarry 
TODO:

[ButtonImageWithTextAndBadge] Add `badgeColor` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/modals/modal/index.js
assets/javascripts/kitten/karl/pages/mobile-modal/index.js

[Modal] Add open/close animations to Modal

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/crowdfunding-card/components/informations.js
assets/javascripts/kitten/components/cards/crowdfunding-card/components/loading.js
assets/javascripts/kitten/components/form/autocomplete/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/autocomplete/index.js

[Fix] Remove (some) console warnings

---

CHANGELOG.md
assets/javascripts/kitten/components/pages/markdown/__snapshots__/test.js.snap
assets/javascripts/kitten/components/pages/markdown/components/list.js

[Markdown] Transmit sizes modifiers to lists

---

CHANGELOG.md
assets/javascripts/kitten/components/text-copy/__snapshots__/test.js.snap
assets/javascripts/kitten/components/text-copy/index.js
assets/javascripts/kitten/components/text-copy/stories.js
assets/javascripts/kitten/components/text-copy/test.js

[TextCopy] Create `buttonText` props

---

CHANGELOG.md
package-lock.json
package.json
src/components/text-copy/index.js

add built js files for 2.48.0

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/components/informations.js

[CrowdfundingCard] Update margin on Project Informations

---

CHANGELOG.md
assets/javascripts/kitten/components/headers/header.js
assets/javascripts/kitten/components/headers/header.test.js

[Header] Add `HEADER_HEIGHT` export to `Header` component

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/scrollable-container/styled.js
assets/javascripts/kitten/helpers/utils/hex-to-rgba.js
assets/javascripts/kitten/helpers/utils/hex-to-rgba.test.js
package-lock.json
package.json

Closes #.
https://bundlephobia.com/result?p=@kisskissbankbank/kitten@2.49.0
Screenshot:
TODO:

[Utils] Add `hexToRgba` helper, remove `polished` dependency

---

CHANGELOG.md
assets/stylesheets/kitten/utilities/text/_line-height.scss

Closes #1902.
Screenshot:
TODO:

[Utilities] Add `.k-u-line-height-*` utilities

---

CHANGELOG.md
assets/javascripts/kitten/components/text-copy/index.js

Cacher le message qui dit que le texte est copié après 3sec.

`<CopyText/>` fadeout copy text message after 3s

---

CHANGELOG.md
assets/javascripts/kitten/components/text-copy/__snapshots__/test.js.snap
assets/javascripts/kitten/components/text-copy/index.js

Je réduis la taille de la font du texte à copier qui est un poil gros.

[CopyText] Update font size

---

CHANGELOG.md
assets/javascripts/kitten/components/tables/list-table/stories.js
package-lock.json

[ListTable] Add `toggleable` `ListTable` story example

---

.storybook/stylesheets/kitten/_utilities.scss
CHANGELOG.md
assets/stylesheets/kitten/_utilities.scss
assets/stylesheets/kitten/utilities/image/_responsive.scss
assets/stylesheets/kitten/utilities/link/_link.scss
styleguide/style/karl/_utilities.scss

[Utilities] Add `k-u-link--$color` utilities

---

CHANGELOG.md
assets/javascripts/kitten/components/tables/double-entry-table/__snapshots__/test.js.snap
assets/javascripts/kitten/components/tables/double-entry-table/components/col.js

[DoubleEntryTable] Style fixes 🖌

---

CHANGELOG.md
assets/stylesheets/kitten/utilities/background/_background-color.scss

[Utilities] Add `.k-u-background-color-background3` utility

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/components/informations.js
src/components/cards/crowdfunding-card/components/informations.js

- Remaniement des marges pour mieux anticiper le multi-ligne

[CrowdfundingCard] Fix infos styles

---

bin/start

- Ajout de la commande `start` qui permet de démarrer Storybook (comme sur nos autres apps).

[Tech] Add start command

---

CHANGELOG.md
assets/javascripts/kitten/components/icons/doc-icon.js
assets/javascripts/kitten/components/icons/icons.stories.js
assets/javascripts/kitten/components/icons/save-icon.js

Add save and doc icons

---

.nvmrc
CHANGELOG.md
package-lock.json
package.json

Passage à node 12 avec petit fix de sécu.

Update node to 12

---

CHANGELOG.md
package-lock.json
package.json
src/components/cards/engagement-card/index.js
src/components/icons/doc-icon.js
src/components/icons/save-icon.js

add built js files for 2.56.0

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/engagement-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/engagement-card/index.js
assets/javascripts/kitten/components/cards/engagement-card/stories.js

[Engagement ] Update carousel styles

---

CHANGELOG.md
package-lock.json
package.json
src/components/cards/engagement-card/index.js

add built js files for 2.57.0

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/engagement-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/engagement-card/index.js
assets/javascripts/kitten/components/cards/engagement-card/stories.js
assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
assets/javascripts/kitten/components/carousel/carousel/carousel.js
assets/javascripts/kitten/components/carousel/carousel/components/carousel-inner.js
assets/javascripts/kitten/components/carousel/carousel/stories.js
assets/javascripts/kitten/components/carousel/carousel/test.js

- Ajout de la prop `showOtherPages` qui permet de voir un petit bout des pages avant/après et de gérer l'ancrage des pages
- Retire les styles du `isActive` sur le composant `EngagementCard`

[Carousel] Add prop to show other pages

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/engagement-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/engagement-card/index.js

[EngagementCard] Fix padding

---

CHANGELOG.md
package-lock.json
package.json
src/components/cards/engagement-card/index.js
src/components/carousel/carousel/carousel.js

add built js files for 2.59.0

---

CHANGELOG.md
package-lock.json
package.json
src/components/carousel/carousel/carousel.js
src/components/icons/camera-icon/index.js

add built js files for 2.60.0

---

package-lock.json
package.json

https://www.npmjs.com/package/@storybook/addon-docs

[StoryBook] Add addon-docs

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/sticky-container/index.js

- Correction d'un problème d'unmount car la fonction entre le mount et l'unmount n'était pas la même

[StickyContainer] Fix memory leak

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/carousel/carousel.js

[Carousel] Fix prev / next buttons

---

assets/javascripts/kitten/karl/pages/homepage/news/components/news-block.js
assets/javascripts/kitten/karl/pages/homepage/news/index.js

[HomePage] News block tablet fixes

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/carousel.js

[Carousel] Fix prev / next buttons on the other carousel I just discovered was the right one

---

.github/PULL_REQUEST_TEMPLATE.md

Update PR description

---

assets/javascripts/kitten/components/meters/progress-ring/stories.js

[ProgressRing] Fix component name error in stories

---

assets/javascripts/kitten/karl/pages/homepage/index.js
assets/javascripts/kitten/karl/pages/homepage/stories.js

[HomePage] Add `Title`

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/engagement-card/withImage/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/engagement-card/withImage/index.js
assets/javascripts/kitten/components/cards/engagement-card/withImage/stories.js
assets/javascripts/kitten/components/cards/engagement-card/withImage/test.js

[Engagement] Create `EngagementCardWithImage` component

---

assets/javascripts/kitten/karl/pages/homepage/dialog-with-picture-border/index.js
assets/javascripts/kitten/karl/pages/homepage/dialog-with-picture-border/stories.js

[Homepage] Last part

---

assets/javascripts/kitten/karl/pages/homepage/video/index.js
assets/javascripts/kitten/karl/pages/homepage/video/stories.js

[Homepage] Video section

---

package.json

[CodeQuality] Add `eslint` pre-commit hook

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
assets/javascripts/kitten/components/carousel/carousel/carousel.js
assets/javascripts/kitten/components/carousel/carousel/stories.js
assets/javascripts/kitten/components/carousel/carousel/test.js

[Carousel] Add `loop` prop on Carousel

---

CHANGELOG.md
assets/javascripts/kitten/components/meters/progress-ring/__snapshots__/test.js.snap
assets/javascripts/kitten/components/meters/progress-ring/index.js

[ProgressRing] Fix ios bug

---

CHANGELOG.md
assets/javascripts/kitten/components/icons/export-icon-alternate/index.js
assets/javascripts/kitten/components/icons/icons.stories.js

[Icons] Add `ExportIconAlternate`

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/pagination/__snapshots__/test.js.snap
assets/javascripts/kitten/components/navigation/pagination/index.js
assets/javascripts/kitten/components/navigation/pagination/stories.js

[Pagination] Add `margin` and `align` props

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/pagination/__snapshots__/test.js.snap
assets/javascripts/kitten/components/navigation/pagination/index.js

[Pagination] Fix `isActive` warning

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/article-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/contribution-card.test.js.snap
assets/javascripts/kitten/components/cards/__snapshots__/reward-card.test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/components/subtitle.js
assets/javascripts/kitten/components/cards/donation-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/reward-card/title.js
assets/javascripts/kitten/components/layout/horizontal-stroke/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/horizontal-stroke/index.js
assets/javascripts/kitten/components/meters/counter-block/__snapshots__/test.js.snap
assets/javascripts/kitten/components/pages/markdown/__snapshots__/test.js.snap

[HorizontalStroke] Add `color` prop and fix bug

---

CHANGELOG.md
assets/javascripts/kitten/components/meters/progress-ring/__snapshots__/test.js.snap
assets/javascripts/kitten/components/meters/progress-ring/index.js

[ProgressRing] Fix bug on Chrome

---

CHANGELOG.md
assets/javascripts/kitten/components/videos/embed-player/__snapshots__/test.js.snap
assets/javascripts/kitten/components/videos/embed-player/index.js

Ajout d'un hover sur le bouton

Add hover on embed-player button

---

CHANGELOG.md
doc/utilities/align.stories.mdx

[Utilities] Add align doc

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button-group/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button-group/index.js
assets/javascripts/kitten/components/buttons/button-group/stories.js
assets/javascripts/kitten/components/buttons/button-group/test.js

[ButtonGroup] Add `active` prop to `Button` subcomponent

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/reward-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/lists/list/__snapshots__/test.js.snap
assets/javascripts/kitten/components/lists/list/components/button-item.js
assets/javascripts/kitten/components/lists/list/index.js
assets/javascripts/kitten/components/lists/list/info.js
assets/javascripts/kitten/components/lists/list/stories.js
assets/javascripts/kitten/components/lists/list/test.js

[List] Add `hasArrow` and `active` props to `List.ButtonItem`

---

CHANGELOG.md
assets/javascripts/kitten/components/box/link-box/__snapshots__/test.js.snap
assets/javascripts/kitten/components/box/link-box/deprecated.js
assets/javascripts/kitten/components/box/link-box/index.js
assets/javascripts/kitten/components/box/link-box/stories.js
assets/javascripts/kitten/components/box/link-box/styles.js
assets/javascripts/kitten/components/box/link-box/test.js
assets/javascripts/kitten/helpers/utils/deprecated.js
assets/stylesheets/kitten/components/box/_link-box.scss

**Screenshot**:
Une fois que tous les `<LinkBox />` utilisés sur Lendo et KissKiss seront mis à jour, toutes les parties contenant `deprecated` pourront être supprimées.

Update `LinkBox` component

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
assets/javascripts/kitten/components/carousel/carousel/components/carousel-inner.js
assets/javascripts/kitten/components/carousel/carousel/components/carousel-page.js
assets/javascripts/kitten/components/carousel/carousel/index.js
assets/javascripts/kitten/components/carousel/carousel/project-carousel.stories.js

[Carousel] Pass props to children relating to visibility

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button-group/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button/helpers/modifier-styles.js
assets/javascripts/kitten/components/buttons/checkable-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/reward-edition/__snapshots__/test.js.snap
assets/javascripts/kitten/components/date-picker/standalone-range/__snapshots__/test.js.snap
assets/javascripts/kitten/components/expandable/expand-board/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/icons/icons.stories.js
assets/javascripts/kitten/components/icons/upload-icon/index.js
assets/javascripts/kitten/components/popovers/simple-popover/__snapshots__/test.js.snap
assets/javascripts/kitten/components/text-copy/__snapshots__/test.js.snap
assets/javascripts/kitten/components/uploaders/basic-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/uploaders/basic-uploader/index.js
assets/javascripts/kitten/components/uploaders/basic-uploader/stories.js
assets/javascripts/kitten/components/uploaders/basic-uploader/test.js

[Uploaders] Add `BasicUploader` component.

---

CHANGELOG.md
assets/javascripts/kitten/components/uploaders/basic-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/uploaders/basic-uploader/index.js
assets/javascripts/kitten/components/uploaders/document-manager/__snapshots__/test.js.snap
assets/javascripts/kitten/components/uploaders/document-manager/index.js
assets/javascripts/kitten/components/uploaders/document-manager/stories.js
assets/javascripts/kitten/helpers/utils/use-previous-hook.js

[Uploaders] Fix mobile `DocumentManager`

---

CHANGELOG.md
assets/javascripts/kitten/components/dropdowns/v2/dropdown.js
assets/javascripts/kitten/components/navigation/header-nav/components/user-menu.js
assets/javascripts/kitten/components/navigation/header-nav/index.js
assets/javascripts/kitten/components/navigation/header-nav/stories/kisskissbankbank.js
assets/javascripts/kitten/helpers/utils/use-deep-compare-effect-hook.js
assets/javascripts/kitten/helpers/utils/use-window-width-hook.js

[HeaderNav] Add `stickyProps` prop to component

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/header-nav/index.js

[HeaderNav] Fix shadow on unscrolled `HeaderNav`

---

CHANGELOG.md
assets/javascripts/kitten/components/dropdowns/v2/dropdown.js
assets/javascripts/kitten/components/navigation/header-nav/stories/kisskissbankbank.js
assets/stylesheets/kitten/components/dropdowns/_dropdown.scss
assets/stylesheets/kitten/components/navigation/_header-nav.scss

[HeaderNav] Fix UserMenu min-width

---

CHANGELOG.md
assets/javascripts/kitten/components/uploaders/basic-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/uploaders/basic-uploader/index.js
assets/javascripts/kitten/components/uploaders/document-manager/__snapshots__/test.js.snap
assets/javascripts/kitten/components/uploaders/document-manager/index.js

[Uploaders] Replace `for` with `htmlFor` in `BasicUploader` and `DocumentManager`

---

CHANGELOG.md
assets/stylesheets/kitten/components/dropdowns/_dropdown.scss

[Dropdown] Fix drop shadow

---

CHANGELOG.md
assets/javascripts/kitten/components/meters/progress-ring/__snapshots__/test.js.snap
assets/javascripts/kitten/components/meters/progress-ring/index.js

[ProgressRing] Fix console warning

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/clickable-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/clickable-card/index.js
assets/javascripts/kitten/components/cards/clickable-card/stories.js
assets/javascripts/kitten/components/cards/clickable-card/test.js
assets/javascripts/kitten/components/uploaders/document-manager/index.js
assets/stylesheets/kitten/_utilities.scss
assets/stylesheets/kitten/utilities/reset/_button.scss

[ClickableCard] Add new component

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/clickable-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/clickable-card/index.js

[ClickableCard] Opacity transition

---

bin/release
package.json

- Ajout de la création du fichier des utilitaires dans la commande de release

[Release] Build utilities

---

assets/javascripts/kitten/components/notifications/__snapshots__/alert.test.js.snap
assets/javascripts/kitten/components/notifications/alert.js

[Notifications] Better display on mobile

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/__snapshots__/article-card.test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/components/image.js
assets/javascripts/kitten/components/cards/crowdfunding-card/test.js

[CrowdfundingCard] Add `key` to video sources

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
assets/javascripts/kitten/components/carousel/carousel/components/carousel-page.js
assets/javascripts/kitten/components/carousel/carousel/test.js

[Carousel] Fix bug with Passed Props

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button/button.js
assets/javascripts/kitten/components/buttons/button/helpers/modifier-styles.js
assets/javascripts/kitten/components/buttons/social-button-icon-words/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/social-button-icon-words/index.js
assets/javascripts/kitten/components/buttons/social-button-icon-words/social-button-icon-words.stories.js
assets/javascripts/kitten/components/buttons/social-button-icon-words/test.js
assets/javascripts/kitten/components/buttons/social-button-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/social-button-icon/index.js
assets/javascripts/kitten/components/buttons/social-button-icon/social-button-icon.stories.js
assets/javascripts/kitten/components/buttons/social-button-icon/test.js
assets/javascripts/kitten/components/date-picker/standalone-range/__snapshots__/test.js.snap
assets/javascripts/kitten/components/expandable/expand-board/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/text-copy/__snapshots__/test.js.snap
assets/javascripts/kitten/components/uploaders/basic-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/uploaders/document-manager/__snapshots__/test.js.snap
assets/javascripts/kitten/index.js

[Button] Add Instagram button with icon and words

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
assets/javascripts/kitten/components/carousel/carousel/project-carousel.stories.js
assets/javascripts/kitten/components/carousel/carousel/styles.js

[Carousel] Fix width on small screen in Legacy mode

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/clickable-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/clickable-card/index.js

[ClickableCard] Fix image dimensions on Safari

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/article-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/reward-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/videos/gif-video/__snapshots__/test.js.snap
assets/javascripts/kitten/components/videos/gif-video/index.js

[GifVideo] Fix controls issue

---

CHANGELOG.md
assets/javascripts/kitten/components/icons/download-icon/index.js
assets/javascripts/kitten/components/icons/icons.stories.js

[DownloadIcon] Add `DownloadIcon`

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button-group/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button/helpers/modifier-styles.js
assets/javascripts/kitten/components/buttons/checkable-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/checkable-button/checkable-button.stories.js
assets/javascripts/kitten/components/buttons/social-button-icon-words/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/social-button-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/reward-edition/__snapshots__/test.js.snap
assets/javascripts/kitten/components/date-picker/standalone-range/__snapshots__/test.js.snap
assets/javascripts/kitten/components/expandable/expand-board/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/images/image-cropper/__snapshots__/test.js.snap
assets/javascripts/kitten/components/popovers/simple-popover/__snapshots__/test.js.snap
assets/javascripts/kitten/components/text-copy/__snapshots__/test.js.snap
assets/javascripts/kitten/components/uploaders/basic-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/uploaders/basic-uploader/stories.js
assets/javascripts/kitten/components/uploaders/document-manager/__snapshots__/test.js.snap

[Button] Fix svg hover delay

---

CHANGELOG.md
assets/javascripts/kitten/components/box/doc-link-box/__snapshots__/test.js.snap
assets/javascripts/kitten/components/box/link-box/__snapshots__/test.js.snap
assets/javascripts/kitten/components/carousel/nav-tab-carousel/__snapshots__/test.js.snap
assets/javascripts/kitten/components/date-picker/standalone-range/__snapshots__/test.js.snap
assets/javascripts/kitten/components/expandable/expand-board/__snapshots__/test.js.snap
assets/javascripts/kitten/components/icons/arrow-icon/__snapshots__/arrow-icon.test.js.snap
assets/javascripts/kitten/components/icons/arrow-icon/index.js
assets/javascripts/kitten/components/menus/header-menu/__snapshots__/test.js.snap
assets/javascripts/kitten/components/navigation/pagination/__snapshots__/test.js.snap

[Icons] Fix Safari bug with `ArrowIcon`

---

CHANGELOG.md
assets/javascripts/kitten/components/tables/single-entry-table/__snapshots__/test.js.snap
assets/javascripts/kitten/components/tables/single-entry-table/index.js
assets/javascripts/kitten/components/tables/single-entry-table/single-entry-table.stories.js
assets/javascripts/kitten/components/tables/single-entry-table/styles.js
assets/javascripts/kitten/components/tables/single-entry-table/test.js

[SingleEntryTable] Add `isSliding` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button/button.js
assets/javascripts/kitten/components/buttons/button/button.stories.js
assets/javascripts/kitten/components/buttons/button/test.js
assets/javascripts/kitten/components/cards/cart-reward-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/cart-reward-card/index.js
assets/javascripts/kitten/components/cards/reward-edition/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/reward-edition/components/header.js
assets/javascripts/kitten/components/date-picker/standalone-range/__snapshots__/test.js.snap
assets/javascripts/kitten/components/expandable/expand-board/__snapshots__/test.js.snap
assets/javascripts/kitten/components/images/image-cropper/__snapshots__/test.js.snap
assets/javascripts/kitten/components/modals/modal/index.js
assets/javascripts/kitten/components/modals/next/index.js
assets/javascripts/kitten/components/popovers/popover.js
assets/javascripts/kitten/components/popovers/simple-popover/__snapshots__/test.js.snap
assets/javascripts/kitten/components/popovers/simple-popover/index.js
assets/javascripts/kitten/components/uploaders/basic-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/uploaders/document-manager/__snapshots__/test.js.snap
assets/stylesheets/kitten/components/buttons/_button-icon.scss
assets/stylesheets/kitten/components/modals/modal.scss

- Ajout de la size `micro` sur le `<Button icon>`
- Remplace les `CloseButton` sur les `Modal`,  `RewardCard`, `Popover`, ...

[ButtonIcon] Update micro size on the button icon

---

CHANGELOG.md
assets/javascripts/kitten/components/images/image-cropper/index.js

Utilisation du `useEffect` pour gérer le `onChange` car ça fixe un problème de ref sur le `File`

Fix image cropper

---

CHANGELOG.md
package-lock.json
package.json
src/components/icons/dot-icon/index.js
src/components/images/image-cropper/index.js
src/components/steppers/vertical-stepper/components/link.js
src/components/steppers/vertical-stepper/components/list.js
src/components/steppers/vertical-stepper/components/status.js
src/components/steppers/vertical-stepper/components/step.js
src/components/steppers/vertical-stepper/components/title.js
src/components/steppers/vertical-stepper/index.js
src/esm/components/icons/dot-icon/index.js
src/esm/components/images/image-cropper/index.js
src/esm/components/steppers/vertical-stepper/components/link.js
src/esm/components/steppers/vertical-stepper/components/list.js
src/esm/components/steppers/vertical-stepper/components/status.js
src/esm/components/steppers/vertical-stepper/components/step.js
src/esm/components/steppers/vertical-stepper/components/title.js
src/esm/components/steppers/vertical-stepper/index.js

[Release] add built js files for 2.98.0

---

CHANGELOG.md
assets/javascripts/kitten/components/accordeon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/accordeon/components/content.js
assets/javascripts/kitten/components/accordeon/components/header.js
assets/javascripts/kitten/components/accordeon/index.js
assets/javascripts/kitten/helpers/utils/debounce.js

[Accordeon] Fix height update frequency

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/index.js

[RadioButton] Fix min height and optional content margin

---

CHANGELOG.md
assets/javascripts/kitten/components/form/dropdown-phone-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select-with-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select-with-input/dropdown-select.stories.js
assets/javascripts/kitten/components/form/dropdown-select-with-input/index.js

[DropdownSelectWithInput] Add `deactivateDropdown` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/index.js

[RadioButton] Style fixes.

---

CHANGELOG.md
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/combobox.test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/styles.js

[DropdownSelect] Fix Z index

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/index.js
assets/javascripts/kitten/components/form/radio-button/test.js

[RadioButton] Fix styles (2)

---

.storybook/preview.js
package-lock.json
package.json

[Storybook] Use native sorting options

---

CHANGELOG.md
assets/javascripts/kitten/components/lists/check-list/__snapshots__/test.js.snap
assets/javascripts/kitten/components/lists/check-list/index.js

[CheckList] Update styles

---

CHANGELOG.md
package-lock.json
package.json
src/components/form/password-input/index.js
src/components/lists/check-list/index.js
src/components/meters/progress/index.js
src/esm/components/form/password-input/index.js
src/esm/components/lists/check-list/index.js
src/esm/components/meters/progress/index.js

[Release] add built js files for 2.104.0

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/tag-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/tag-button/index.js

[TagButton] Rollback refacto

---

CHANGELOG.md
package-lock.json
package.json
src/components/buttons/tag-button/index.js
src/esm/components/buttons/tag-button/index.js

[Release] add built js files for 2.104.1

---

assets/javascripts/kitten/components/buttons/tag-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/tag-button/index.js

[TagButton] Fix className and refacto

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/article-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/meters/progress/__snapshots__/test.js.snap
assets/javascripts/kitten/components/meters/progress/index.js

[ProgressBar] Fix className (and refactor)

---

CHANGELOG.md
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/combobox.test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/styles.js

[DropdownSelect] Fix item line height

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/password-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/password-input/index.js

[PasswordInput] Fix button type

---

CHANGELOG.md
assets/javascripts/kitten/components/form/radio-button/index.js

[RadioButton] Fix text prop PropType

---

CHANGELOG.md
assets/javascripts/kitten/components/steppers/vertical-stepper/__snapshots__/test.js.snap
assets/javascripts/kitten/components/steppers/vertical-stepper/components/status.js
assets/javascripts/kitten/components/steppers/vertical-stepper/components/title.js
assets/javascripts/kitten/components/steppers/vertical-stepper/index.js
assets/javascripts/kitten/components/steppers/vertical-stepper/stories.js

- Update style sur le `title` 
- Centre comme il faut le trait horizontal
- Retire la marge de -5px sur le parent à gauche
- Passe le status de 15px à 16px
TODO:

[VerticalStepper] Update styles

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/tag-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/tag-button/index.js
assets/javascripts/kitten/components/buttons/tag-button/tag-button.stories.js

[TagButton] Add variant

---

CHANGELOG.md
assets/javascripts/kitten/components/form/checkbox-set/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/checkbox-set/checkbox-set.stories.js
assets/javascripts/kitten/components/form/checkbox-set/index.js
assets/javascripts/kitten/components/form/checkbox/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/checkbox/checkbox.stories.js
assets/javascripts/kitten/components/form/checkbox/index.js

- Ajoute variant sur `Checkbox` et `CheckboxSet`
TODO:

[Checkbox] Update styles

---

CHANGELOG.md
assets/stylesheets/kitten/_utilities.scss
assets/stylesheets/kitten/utilities/flex/_align-self.scss
assets/stylesheets/utilities.scss
doc/utilities/flex/align-self.stories.mdx

[Utility] Add align-self

---

CHANGELOG.md
assets/javascripts/kitten/components/form/dropdown-phone-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select-with-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select-with-input/index.js
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/combobox.test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/styles.js

Closes #.
Ajoute une couleur par défaut sur les items du `DropdownSelect`
Screenshot:
TODO:

[DropdownSelect] Set default color

---

CHANGELOG.md
assets/javascripts/kitten/components/form/dropdown-phone-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select-with-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select-with-input/dropdown-select.stories.js
assets/javascripts/kitten/components/form/dropdown-select-with-input/index.js
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/combobox.test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/combobox.js
assets/javascripts/kitten/components/form/dropdown-select/dropdown-select.stories.js
assets/javascripts/kitten/components/form/dropdown-select/index.js
assets/javascripts/kitten/components/form/dropdown-select/styles.js

[DropdownSelect] Add `menuZIndex` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/reward-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/reward-card/components/image.js
assets/javascripts/kitten/components/cards/reward-card/components/video.js
assets/javascripts/kitten/components/cards/reward-card/stories.js
assets/javascripts/kitten/components/cards/reward-card/styles.js

[RewardCard] Set image ratio to 16/10

---

CHANGELOG.md
assets/javascripts/kitten/components/form/range-slider/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/range-slider/test.js

Range slider/fix test warning

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/scrollable-container/__snapshots__/test.js.snap
assets/javascripts/kitten/components/grid/scrollable-container/stories.js
assets/javascripts/kitten/components/grid/scrollable-container/styled.js

[ScrollableContainer] Fix overflow style

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/article-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/components/button.js
assets/javascripts/kitten/components/cards/crowdfunding-card/index.js
assets/javascripts/kitten/components/cards/crowdfunding-card/stories.js
assets/javascripts/kitten/components/cards/crowdfunding-card/test.js

- Ajout de la prop `buttonText` pour afficher un bouton sous la card

[CrowdfundingCard] Add buttonText prop

---

CHANGELOG.md
assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
assets/javascripts/kitten/components/carousel/carousel/index.js
assets/javascripts/kitten/components/carousel/carousel/styles.js

[Carousel] A11y & Design fixes

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/article-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/components/progress.js
assets/javascripts/kitten/components/cards/crowdfunding-card/components/state.js
assets/javascripts/kitten/components/cards/crowdfunding-card/index.js
assets/javascripts/kitten/components/cards/crowdfunding-card/stories.js
assets/javascripts/kitten/components/cards/crowdfunding-card/styles.js
assets/javascripts/kitten/components/cards/crowdfunding-card/test.js

- Ajout d'une prop non-obligatoire qui permet de forcer les styles d'une version responsive.

[CrowdfundingCard] Add forceVersion prop

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/index.js

Closes #.
https://kitten-git-radio-button-fix-mobile-styles.kisskissbankbank.vercel.app/?path=/story/form-radiobutton--default
Screenshot:
TODO:

[RadioButton] Mobile style fixes

---

CHANGELOG.md
assets/javascripts/kitten/components/form/range-slider/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/range-slider/index.js

Closes #.
- https://kitten-git-range-slider-fix-mobile-styles.kisskissbankbank.vercel.app/?path=/story/form-rangeslider--default
- https://kitten-git-range-slider-fix-mobile-styles.kisskissbankbank.vercel.app/?path=/story/form-rangeslider--with-range-thumb-text
Screenshot:
TODO:

[RangeSlider] Mobile style fixes

---

CHANGELOG.md
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/combobox.test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/styles.js

Closes #.
- https://kitten-git-dropdown-select-fix-mobile-styles.kisskissbankbank.vercel.app/?path=/story/form-dropdownselect--default
Screenshot:
TODO:

[DropdownSelect] Mobile style fixes

---

CHANGELOG.md
assets/javascripts/kitten/components/steppers/vertical-stepper/__snapshots__/test.js.snap
assets/javascripts/kitten/components/steppers/vertical-stepper/components/status.js
assets/javascripts/kitten/components/steppers/vertical-stepper/components/title.js
assets/javascripts/kitten/components/steppers/vertical-stepper/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[VerticalStepper] Update mobile version

---

CHANGELOG.md
assets/javascripts/kitten/components/steppers/vertical-stepper/__snapshots__/test.js.snap
assets/javascripts/kitten/components/steppers/vertical-stepper/components/link.js
assets/javascripts/kitten/components/steppers/vertical-stepper/components/status.js
assets/javascripts/kitten/components/steppers/vertical-stepper/components/title.js

Closes #.
Vercel link:
Screenshot:
TODO:

[VerticalStepper] Littles mobile style fixes

---

CHANGELOG.md
assets/javascripts/kitten/components/uploaders/document-manager/__snapshots__/test.js.snap
assets/javascripts/kitten/components/uploaders/document-manager/index.js

https://trello.com/c/608ItlEy/390-kyc-kitten-le-composant-documentmanager-a-la-bonne-apparence
https://kitten-git-restyling-document-manager.kisskissbankbank.vercel.app/?path=/story/box-documentmanager--status-ready
Deux choses : 
- Modifier le border-radius pour qu'il colle au variant `orion`
- cacher l'icône en mobile

[DocumentManager] Restyling

---

README.md
bin/publish

- Ajout d'un paramètre `with-storybook` au script `publish`

[Scripts] Add with-storybook parameter

---

CHANGELOG.md
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/combobox.test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DropdownSelect] Add size prop in Orion variant

---

CHANGELOG.md
assets/javascripts/kitten/components/tooltips/toggletip/index.js
src/components/tooltips/toggletip/index.js
src/esm/components/tooltips/toggletip/index.js

J'avais deux petits soucis sur le composant sur je décris dans le code :

[Toggletip] Fix init and resize coords calculation

---

CHANGELOG.md
assets/javascripts/kitten/components/form/toggle-switch/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/toggle-switch/index.js
assets/javascripts/kitten/components/form/toggle-switch/stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ToggleSwitch] Add `onChange` to API

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/flow/index.js
assets/javascripts/kitten/components/layout/dashboard-layout/flow/side-modal.js
assets/javascripts/kitten/components/layout/dashboard-layout/index.js
assets/javascripts/kitten/components/layout/dashboard-layout/stories.js
assets/javascripts/kitten/components/menus/dashboard-menu/__snapshots__/test.js.snap
assets/javascripts/kitten/components/menus/dashboard-menu/index.js
assets/javascripts/kitten/helpers/react/react-elements.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DashboardLayout] Fix display bugs

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/header-nav/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HeaderNav] Fix header width on Windows

---

CHANGELOG.md
assets/javascripts/kitten/components/atoms/loader-with-paragraph/__snapshots__/test.js.snap
assets/javascripts/kitten/components/atoms/loader-with-paragraph/index.js
assets/javascripts/kitten/components/atoms/loader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/atoms/loader/index.js
assets/javascripts/kitten/components/cards/backing-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/backing-card/index.js
assets/javascripts/kitten/components/cards/backing-card/styles.js
assets/javascripts/kitten/components/form/autocomplete/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/images/image-cropper/__snapshots__/test.js.snap
assets/javascripts/kitten/components/images/image-cropper/index.js
assets/javascripts/kitten/components/images/image-cropper/styles.js
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/flow/index.js
assets/javascripts/kitten/components/layout/dashboard-layout/index.js
assets/javascripts/kitten/components/menus/dashboard-menu/__snapshots__/test.js.snap
assets/javascripts/kitten/components/menus/dashboard-menu/index.js
assets/javascripts/kitten/components/videos/video/__snapshots__/test.js.snap

Closes #.
Vercel link:
Screenshot:
TODO:

[Fix] Fix missing `gap` in Flexbox for Safari

---

CHANGELOG.md
assets/javascripts/kitten/helpers/dom/use-flex-gap-check/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[useFlexGapCheck] Add DOM check

---

CHANGELOG.md
assets/javascripts/kitten/components/pages/markdown/__snapshots__/test.js.snap
assets/javascripts/kitten/components/typography/title/__snapshots__/test.js.snap
assets/javascripts/kitten/components/typography/title/index.js
assets/javascripts/kitten/components/typography/title/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Title] Fix default value for `noMargin`

---

CHANGELOG.md
assets/javascripts/kitten/components/lists/horizontal-timeline/__snapshots__/test.js.snap
assets/javascripts/kitten/components/lists/horizontal-timeline/index.js
assets/javascripts/kitten/components/lists/horizontal-timeline/stories.js
assets/javascripts/kitten/components/lists/horizontal-timeline/test.js
assets/javascripts/kitten/index.js

Closes #.
Vercel link:
- https://kitten-git-horizontal-timeline-create-component-14d1bd.vercel.app/?path=/story/list-horizontaltimeline--default
- 
Screenshot:
TODO:

[HorizontalTimeline] Add component

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/grid/__snapshots__/test.js.snap
assets/javascripts/kitten/components/grid/grid/index.js
assets/javascripts/kitten/components/grid/grid/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Grid] Fix `GridCol` offset class for `0` value.

---

CHANGELOG.md
assets/javascripts/kitten/components/accordeon/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Accordion] Fix error on fold

---

CHANGELOG.md
package-lock.json
package.json
src/esm/index.js
src/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

v3.0.0-beta.18

---

assets/javascripts/kitten/components/navigation/header-nav/components/dropdown.js
assets/javascripts/kitten/components/navigation/header-nav/index.js
assets/javascripts/kitten/helpers/utils/emitter.js
package-lock.json
package.json

Utilisation du `CustomEvent` au lieu de la lib `event-emitter`

Use CustomEvent instead of event-emitter

---

package-lock.json
package.json

La version `2.1.7` entraine un bug de cropping.
Je revert en `2.1.6` en attendant d'en apprendre plus

improve dependencies installation

---

CHANGELOG.md
assets/javascripts/kitten/components/lists/bullet-list/__snapshots__/test.js.snap
assets/javascripts/kitten/components/lists/bullet-list/index.js
assets/javascripts/kitten/components/lists/bullet-list/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[BulletList] Fix item classes transmission

---

CHANGELOG.md
assets/javascripts/kitten/components/form/location-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/location-input/index.js
assets/javascripts/kitten/components/form/location-input/stories.js
assets/javascripts/kitten/components/form/location-input/test.js

- Ajout de la prop `variant`
Vercel link:
Screenshot:
TODO:

[LocationInput] Add variant prop

---

CHANGELOG.md
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/combobox.test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/styles.js

Closes #.
Vercel link:
- https://kitten-git-dropdown-select-fix-styles-kisskissbankbank.vercel.app/?path=/story/form-dropdownselect--default
Screenshot:
TODO:

[DropdownSelect] Size styles

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/tag-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/tag-button/index.js

Corrige les styles `disabled`
Vercel link:
Screenshot:
TODO:

[TagButton] Update styles

---

assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/field/field.test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[FieldInput] Add tests

---

CHANGELOG.md
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/combobox.test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DropdownSelect] Fix outline styles

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button-group/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button-question-mark-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button/index.js
assets/javascripts/kitten/components/buttons/checkable-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/checkable-button/checkable-button.stories.js
assets/javascripts/kitten/components/buttons/checkable-button/index.js
assets/javascripts/kitten/components/buttons/close-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/social-button-icon-words/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/social-button-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/backing-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/cart-reward-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/reward-edition/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/team-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/triptych/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/vertical-card-with-action/__snapshots__/test.js.snap
assets/javascripts/kitten/components/date-picker/standalone-range/__snapshots__/test.js.snap
assets/javascripts/kitten/components/expandable/expand-board/__snapshots__/test.js.snap
assets/javascripts/kitten/components/images/image-cropper/__snapshots__/test.js.snap
assets/javascripts/kitten/components/notifications/alert/__snapshots__/test.js.snap
assets/javascripts/kitten/components/popovers/simple-popover/__snapshots__/test.js.snap
assets/javascripts/kitten/components/uploaders/basic-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/uploaders/document-manager/__snapshots__/test.js.snap

Closes #.
Vercel link:
Screenshot:
TODO:

[CheckableButton] Style fixes

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/header-nav/components/burger-menu.js
assets/javascripts/kitten/components/navigation/header-nav/components/dropdown-button.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HeaderNav] Fix button default style reset

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/flow/index.js
assets/javascripts/kitten/components/layout/dashboard-layout/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DashboardLayout] Fix column widths

---

CHANGELOG.md
assets/javascripts/kitten/components/modals/next/index.js

Je rajoute la prop `zIndex` sur le style du `header`.
Comme il est en position `sticky`, j'ai l'impression qu'il passe en dessous d'éléments qui ont une `position` définie dans le body de la `Modal` comme ici : 
Mon diagnostique est bon ?

Add zIndex to header

---

CHANGELOG.md
assets/javascripts/kitten/components/modals/next/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ModalNext] Fix condition for `customContentCols` className

---

CHANGELOG.md
assets/javascripts/kitten/components/lists/bullet-list/__snapshots__/test.js.snap
assets/javascripts/kitten/components/lists/bullet-list/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[BulletList] Fix class errors

---

.storybook/stylesheets/app-kitten.scss
CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/stories.js
assets/javascripts/kitten/components/navigation/header-nav/index.js
assets/javascripts/kitten/components/navigation/header-nav/stories.js
assets/javascripts/kitten/components/navigation/header-nav/stories/kisskissbankbank-new.js
assets/javascripts/kitten/components/navigation/header-nav/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HeaderNav] Add Border styles

---

CHANGELOG.md
assets/javascripts/kitten/components/modals/next/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Modal/Next] Fix Button style when alone in fullSize Action.

---

assets/javascripts/kitten/components/steppers/vertical-progress/vertical-progress.stories.mdx
doc/introduction/component-status.stories.mdx

Closes #.
Vercel link:
Screenshot:
TODO:

[Doc] VerticalProgress

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/flow/index.js
assets/javascripts/kitten/components/layout/dashboard-layout/stories.js

Ça règle de manière peu satisfaisante le problème de taille de `DropdownSelectWithInput` qui ne prend pas la bonne largeur au sein du Flow en taille L.
Closes #.
Vercel link:
Screenshot:
TODO:

[DashboardLayout] Specify size for `DashboardLayout.Flow` content column.

---

assets/javascripts/kitten/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[VerticalProgress] export

---

CHANGELOG.md
assets/javascripts/kitten/components/steppers/vertical-progress/__snapshots__/test.js.snap
assets/javascripts/kitten/components/steppers/vertical-progress/components/status.js
assets/javascripts/kitten/components/steppers/vertical-progress/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[VerticalProgress] Fix z-index value

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button/helpers/modifier-styles.js
assets/javascripts/kitten/constants/colors-config.js
doc/design/colors.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Colors] Add orange2 and orange3 colors

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/separator/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/separator/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Separator] Reduce style specificity

---

doc/introduction/component-status.stories.mdx

Closes #.
Vercel link:
Screenshot:
TODO:

[Doc] Update components status

---

assets/javascripts/kitten/components/box/link-box/link-box.stories.js
assets/javascripts/kitten/components/links/link-list/link-list.stories.js
assets/javascripts/kitten/components/steppers/vertical-progress/vertical-progress.stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Error] Fix console warning

---

CHANGELOG.md
assets/javascripts/kitten/components/form/dropdown-phone-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-phone-select/dropdown-phone-select.stories.js
assets/javascripts/kitten/components/form/dropdown-select-with-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select-with-input/dropdown-select.stories.js
assets/javascripts/kitten/components/form/dropdown-select-with-input/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DropdownSelectWithInput] Add `size` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button/helpers/modifier-styles.js
assets/javascripts/kitten/constants/colors-config.js
assets/stylesheets/kitten/_default-config.scss
doc/design/colors.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Button] Fix boron modifier

---

CHANGELOG.md
assets/stylesheets/kitten/_default-config.scss

Closes #.
Vercel link:
Screenshot:
TODO:

[Colors] Fix sass colors

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/crowdfunding-card/index.js
assets/javascripts/kitten/components/cards/crowdfunding-card/stories.js
assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap

Closes #.
Vercel link:
Screenshot:
TODO:

[CrowdfundingCard] Remove console warning when no Progress

---

CHANGELOG.md
assets/javascripts/kitten/components/form/range-slider/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/range-slider/index.js
assets/javascripts/kitten/components/form/range-slider/stories.js
assets/javascripts/kitten/components/form/range-slider/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[RangeSlider] Add disabled prop

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[RadioButton] Fix status style

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/button-icon/index.js
assets/javascripts/kitten/components/cards/team-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/team-card/components/button-with-tooltip.js
assets/javascripts/kitten/components/cards/team-card/components/icons.js
assets/javascripts/kitten/components/cards/team-card/components/phone-icon.js

Closes #.
Vercel link:
Screenshot:
TODO:

[TeamCard] Fix button subcomponents

---

CHANGELOG.md
assets/javascripts/kitten/components/form/checkbox-set/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-phone-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select-with-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/combobox.test.js.snap
assets/javascripts/kitten/components/form/dropdown-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/field/components/label.js
assets/javascripts/kitten/components/form/label/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/label/index.js
assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
assets/javascripts/kitten/components/images/image-cropper/__snapshots__/test.js.snap

Closes #.
Vercel link:
Screenshot:
TODO:

[Label] Update mobile styles

---

CHANGELOG.md
assets/javascripts/kitten/components/form/dropdown-phone-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select-with-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/dropdown-select-with-input/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DropdownSelectWithInput] Fix margin on deactivatedDropdown

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/crowdfunding-card/components/progress.js
assets/javascripts/kitten/components/cards/crowdfunding-card/index.js
assets/javascripts/kitten/components/cards/crowdfunding-card/stories.js

Closes #.
Vercel link:
- https://kitten-git-crowdfunding-card-fix-progress-value-fddc74.vercel.app/?path=/story/cards-crowdfundingcard--crowdfunding-card
Screenshot:
TODO:

[CrowdfundingCard] Fix Progress display when value === 0

---

CHANGELOG.md
assets/javascripts/kitten/components/images/image-cropper/__snapshots__/test.js.snap
assets/javascripts/kitten/components/images/image-cropper/image-cropper.stories.js
assets/javascripts/kitten/components/images/image-cropper/index.js
assets/javascripts/kitten/components/images/image-cropper/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ImageCropper] Add `buttonProps` prop to be passed on to `BasicUploader`

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DashboardLayout] Fix horizontal scroll

---

CHANGELOG.md
assets/javascripts/kitten/components/box/doc-link-box/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/backer-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/backing-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/cart-reward-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/contribution-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/engagement-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/engagement-card/withImage/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/reward-edition/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/simple-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/team-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/carousel/carousel/__snapshots__/test.js.snap
assets/javascripts/kitten/components/comments/comment-form/__snapshots__/test.js.snap
assets/javascripts/kitten/components/comments/comment/__snapshots__/test.js.snap
assets/javascripts/kitten/components/date-picker/standalone-range/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/checkbox-set/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/checkbox/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/images/image-cropper/__snapshots__/test.js.snap
assets/javascripts/kitten/components/lists/timeline/__snapshots__/test.js.snap
assets/javascripts/kitten/components/meters/counter-block/__snapshots__/test.js.snap
assets/javascripts/kitten/components/navigation/pagination/__snapshots__/test.js.snap
assets/javascripts/kitten/components/steppers/stepper/__snapshots__/test.js.snap
assets/javascripts/kitten/components/text-copy/__snapshots__/test.js.snap
assets/javascripts/kitten/components/typography/sup-title/__snapshots__/test.js.snap
assets/javascripts/kitten/components/typography/text/__snapshots__/test.js.snap
assets/javascripts/kitten/components/typography/text/index.js
assets/javascripts/kitten/components/typography/text/test.js
assets/javascripts/kitten/components/uploaders/basic-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/uploaders/document-manager/__snapshots__/test.js.snap

Closes #.
Vercel link:
Screenshot:
TODO:

[Text] Fix cssColor prop

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/button/button.stories.js
assets/javascripts/kitten/components/buttons/button/button.stories.mdx
assets/javascripts/kitten/components/buttons/button/helpers/modifier-styles.js
assets/javascripts/kitten/components/buttons/button/index.js
assets/javascripts/kitten/components/cards/vertical-card-with-action/vertical-card-with-action.stories.js
assets/javascripts/kitten/components/menus/header-menu/components/item.js
assets/javascripts/kitten/constants/colors-config.js
assets/stylesheets/kitten/_default-config.scss
doc/design/colors.js

Closes #.
Vercel link:
- https://kitten-git-button-add-iron-modifier-kisskissbankbank.vercel.app/iframe.html?id=buttons-button--with-text&args=&knob-Size=regular&knob-Modifier=iron&knob-Variant=orion&knob-Border%20radius=0&knob-Text=MyButton&viewMode=story
Screenshot:
TODO:

[Button] Add iron modifier

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/tooltips/toggletip/__snapshots__/test.js.snap
assets/javascripts/kitten/components/tooltips/toggletip/index.js
assets/javascripts/kitten/components/tooltips/toggletip/stories.js
assets/javascripts/kitten/components/tooltips/toggletip/test.js

Ajout de la prop targetElement

[ToggleTip] Add triggerElement prop

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/header-nav/components/burger-menu-next.js
assets/javascripts/kitten/components/navigation/header-nav/components/button.js
assets/javascripts/kitten/components/navigation/header-nav/components/dropdown-button.js
assets/javascripts/kitten/components/navigation/header-nav/components/user-menu-next.js
assets/javascripts/kitten/components/navigation/header-nav/components/user-menu.js
assets/javascripts/kitten/components/navigation/header-nav/hooks/use-dropdown.js
assets/javascripts/kitten/components/navigation/header-nav/index.js
assets/javascripts/kitten/components/navigation/header-nav/stories/kisskissbankbank-new.js
assets/javascripts/kitten/components/navigation/header-nav/styles.js

These subcomponents use a new, refactored Dropdown system.
Closes #.
Vercel link:
Screenshot:
TODO:
- [?] A11Y

[HeaderMenu] Add `BurgerMenuNext` and `UserMenuNext` subcomponents

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/sticky-container/__snapshots__/test.js.snap
assets/javascripts/kitten/components/grid/sticky-container/index.js
assets/javascripts/kitten/components/grid/sticky-container/sticky-container.stories.js
assets/javascripts/kitten/components/grid/sticky-container/sticky-container.stories.mdx
assets/javascripts/kitten/components/grid/sticky-container/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[StickyContainer] Add value `"never"` to `isSticky` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/grid/sticky-container/index.js
src/components/grid/sticky-container/index.js
src/esm/components/grid/sticky-container/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[StickyContainer] Fix spacer height

---

CHANGELOG.md
assets/javascripts/kitten/components/steppers/vertical-progress/__snapshots__/test.js.snap
assets/javascripts/kitten/components/steppers/vertical-progress/index.js
assets/javascripts/kitten/components/steppers/vertical-progress/vertical-progress.stories.js
assets/javascripts/kitten/components/steppers/vertical-progress/vertical-progress.stories.mdx

Closes #.
Vercel link:
Screenshot:
TODO:

[VerticalProgress] Add withoutBorder prop.

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/contribution-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/contribution-card/index.js

Déporte la responsabilité de l'action du clique sur la croix au niveau de la prop `onClose` pour pouvoir avoir plus de liberté. #freedom

[ContributionCard] Add onClose feature

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/index.js

Modification des styles hover, active, checked et focus en mode orion

[RadioButton] Update hover active states

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/contribution-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/contribution-card/contribution-card.stories.js
assets/javascripts/kitten/components/cards/contribution-card/styles.js

- Modification de la structure de la card en mobile
Vercel link:
Screenshot:
TODO:

[ContributionCard] Update mobile styles

---

CHANGELOG.md
package-lock.json
package.json
src/esm/helpers/utils/parser.js
src/helpers/utils/parser.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Release] add built js files for 3.25.0

---

CHANGELOG.md
assets/javascripts/kitten/components/steppers/vertical-progress/__snapshots__/test.js.snap
assets/javascripts/kitten/components/steppers/vertical-progress/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[VerticalProgress] Remove max-width

---

CHANGELOG.md
package-lock.json
package.json
src/components/steppers/vertical-progress/index.js
src/components/typography/title/index.js
src/esm/components/steppers/vertical-progress/index.js
src/esm/components/typography/title/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Release] add built js files for 3.25.1

---

CHANGELOG.md
assets/javascripts/kitten/helpers/utils/parser.js

Pour éviter des erreurs de SSR sur KissKiss
Je retourne un string vide pour prévenir tout risque de XSS

Escape sanitize if we cant use dom

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/header-nav/components/burger-menu-next.js
assets/javascripts/kitten/components/navigation/header-nav/components/button.js
assets/javascripts/kitten/components/navigation/header-nav/components/logged-out.js
assets/javascripts/kitten/components/navigation/header-nav/components/logged.js
assets/javascripts/kitten/components/navigation/header-nav/components/quick-access-link.js
assets/javascripts/kitten/components/navigation/header-nav/components/user-menu-next.js
assets/javascripts/kitten/components/navigation/header-nav/components/user-menu.js
assets/javascripts/kitten/components/navigation/header-nav/hooks/use-dropdown.js
assets/javascripts/kitten/components/navigation/header-nav/index.js
assets/javascripts/kitten/components/navigation/header-nav/stories/kisskissbankbank-new.js
assets/javascripts/kitten/components/navigation/header-nav/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HeaderNav] Fix user menu position on mobile

---

CHANGELOG.md
assets/javascripts/kitten/components/buttons/tag-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/buttons/tag-button/index.js

Mise à jour du style de la prop `selected`  quand `variant="orion"` et modifier="hydrogen"  sont utilisés.
Vercel link:
Screenshot:
TODO:

[TagButton] Fix style on selected prop

---

CHANGELOG.md
assets/javascripts/kitten/components/uploaders/image-drop-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/uploaders/image-drop-uploader/index.js

[ImageDropUploader] Center vertically manage text

---

CHANGELOG.md
assets/javascripts/kitten/components/cards/backing-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/cards/backing-card/components/button.js
assets/javascripts/kitten/components/cards/backing-card/components/image.js
assets/javascripts/kitten/components/cards/backing-card/index.js
assets/javascripts/kitten/components/cards/backing-card/test.js
assets/javascripts/kitten/components/cards/contribution-card/components/image.js
assets/javascripts/kitten/components/cards/contribution-card/index.js
assets/javascripts/kitten/components/cards/contribution-card/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[KittenV4] Use `getReactElements` utils on `BakingCard` and `ContributionCard`

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/toggletip/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ToggleTip] Remove console warning in tests

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/flow/index.js

Closes #.
Vercel link:
- https://kitten-git-dashboard-layout-flow-fix-na-184e90-kisskissbankbank.vercel.app/?path=/story/layout-dashboardlayout--flow
Screenshot:
TODO:

[DashboardLayout/Flow] Fix Navigation styles

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/modal/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Modal] Remove deprecation console.warn

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button-set/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[RadioButtonSet] Fix dimensions

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/flex-wrapper/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/flex-wrapper/index.js
assets/javascripts/kitten/components/layout/flex-wrapper/stories.js
assets/javascripts/kitten/components/layout/flex-wrapper/test.js
assets/javascripts/kitten/components/molecules/cards/horizontal-crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/horizontal-crowdfunding-card/index.js
assets/javascripts/kitten/components/molecules/cards/horizontal-crowdfunding-card/stories.js
assets/javascripts/kitten/components/molecules/cards/horizontal-crowdfunding-card/test.js
assets/javascripts/kitten/index.js

Closes #.
Vercel link:
- `FlexWrapper`: https://kitten-git-horizontal-crowdfunding-card-e0d28c-kisskissbankbank.vercel.app/?path=/story/layout-flexwrapper--default
- `HorizontalCrowdfundingCard`: https://kitten-git-horizontal-crowdfunding-card-e0d28c-kisskissbankbank.vercel.app/?path=/story/molecules-cards-horizontalcrowdfundingcard--default
Screenshot:
TODO:

[HorizontalCrowdfundingCard] New component

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/cards/contribution-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/contribution-card/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ContributionCard] Fix close button visibility on mobile

---

CHANGELOG.md
assets/javascripts/kitten/components/dev/dev-grid/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/grid/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/marger/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/marger/test.js
assets/javascripts/kitten/components/layout/side-grid/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/side-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/horizontal-crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/horizontal-crowdfunding-card/index.js
assets/javascripts/kitten/components/molecules/cards/triptych/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/carousels/carousel/__snapshots__/test.js.snap
assets/javascripts/kitten/components/organisms/counter-block/__snapshots__/test.js.snap
assets/javascripts/kitten/components/organisms/hero/__snapshots__/test.js.snap
assets/javascripts/kitten/constants/screen-config.js
assets/stylesheets/kitten/_default-config.scss

Closes #.
Vercel link:
Screenshot:
TODO:

[HorizontalCrowdfundingCard] Fix mobile progress styles

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/upload/documents-status-box/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/upload/documents-status-box/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DocumentsStatusBox] Fix style

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/flow/index.js
assets/javascripts/kitten/components/layout/dashboard-layout/stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DashboardLayout] Fix Flow Nav style for single button

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/cards/horizontal-crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/horizontal-crowdfunding-card/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HorizonalCrowdfundingCard] Fix hover styles

---

CHANGELOG.md
assets/javascripts/kitten/components/organisms/hero/__snapshots__/test.js.snap
assets/javascripts/kitten/components/organisms/hero/index.js
assets/javascripts/kitten/constants/screen-config.js
assets/javascripts/kitten/index.js
doc/design/screen-sizes.stories.mdx

Closes #.
Vercel link:
Screenshot:
TODO:

[Constants] Add `mq` Media Query object

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/cards/reward-summary-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/reward-summary-card/components/title-tag.js
assets/javascripts/kitten/components/molecules/cards/reward-summary-card/hooks/use-resize-observer.js
assets/javascripts/kitten/components/molecules/cards/reward-summary-card/stories.js
assets/javascripts/kitten/components/molecules/cards/reward-summary-card/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[RewardSummaryCard] Various fixes

---

assets/javascripts/kitten/components/molecules/cards/reward-summary-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/reward-summary-card/styles.js

Suite au retour de Simon, j'ai fait en sorte que l'image soit clickable.

[RewardImage] Make the image clickable

---

CHANGELOG.md
package-lock.json
package.json
src/components/molecules/cards/reward-summary-card/hooks/use-resize-observer.js
src/components/molecules/expand/dropdown-menu/index.js
src/esm/components/molecules/cards/reward-summary-card/hooks/use-resize-observer.js
src/esm/components/molecules/expand/dropdown-menu/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Release] add built js files for 4.6.1

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/upload/image-drop-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/upload/image-drop-uploader/index.js
assets/javascripts/kitten/components/molecules/upload/image-drop-uploader/stories.js
package-lock.json

Closes #.
Vercel link:
- https://kitten-git-image-drop-uploader-fix-crop-4234e7-kisskissbankbank.vercel.app/?path=/story/molecules-upload-imagedropuploader--status-manage
Screenshot:
TODO:

[ImageDropUploader] Fix cropper sizing

---

CHANGELOG.md
assets/javascripts/kitten/components/form/location-input/index.js

Ajout d'une virgule entre la ville et la pays, dans la liste déroulante

[LocationInput ] Add comma in location input

---

.storybook/includes/file-url.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Storybook] Use a new target on File Urls

---

CHANGELOG.md
assets/javascripts/kitten/components/form/standalone-range-date-picker/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/alert/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/button-group/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/button-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/button-question-mark-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/button/helpers/modifier-styles.js
assets/javascripts/kitten/components/molecules/buttons/button/index.js
assets/javascripts/kitten/components/molecules/buttons/checkable-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/close-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/social-button-icon-words/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/social-button-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/backing-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/cart-reward-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/contribution-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/reward-edition/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/team-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/triptych/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/vertical-card-with-action/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/expand/expand-board/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/simple-popover/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/text-copy/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/upload/basic-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/upload/document-manager/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/upload/image-cropper/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/upload/image-drop-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/organisms/header-menu/__snapshots__/test.js.snap

Closes #.
Vercel link:
- https://kitten-git-button-apply-disabled-styles-2bcac9-kisskissbankbank.vercel.app/?path=/story/molecules-buttons-button--default&args=disabled:true;tag:a
Screenshot:
TODO:

[Button] Apply `disabled` styles to any HTML element type

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/buttons/button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/button/index.js
assets/javascripts/kitten/components/molecules/buttons/button/test.js
assets/javascripts/kitten/components/molecules/text-copy/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/upload/basic-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/upload/document-manager/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/upload/image-cropper/__snapshots__/test.js.snap

Closes #.
Vercel link:
Screenshot:
TODO:

[Button] Fix tag propagation

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/upload/image-drop-uploader/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ImageDropUploader] Fix `onChange` sequence

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/cards/engagement-card-with-image/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/engagement-card-with-image/index.js
assets/javascripts/kitten/components/molecules/cards/engagement-card-with-image/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[EngagementCardWithImage] Add imgProps and textProps props

---

assets/javascripts/kitten/components/molecules/buttons/arrow-container-button/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ButtonWithTooltip] Fixes

---

CHANGELOG.md
assets/javascripts/kitten/components/organisms/header-nav/config.js
assets/javascripts/kitten/components/organisms/header-nav/styles.js

Corrige le 2ème item :
https://trello.com/c/QKDkmLeg/900-int%C3%A9grer-le-header-dans-kisskiss
Vercel link:
Screenshot:
TODO:

[HeaderNav] Fix styles

---

CHANGELOG.md
assets/javascripts/kitten/components/graphics/icons/burger-icon/__snapshots__/burger-icon.test.js.snap
assets/javascripts/kitten/components/graphics/icons/burger-icon/index.js
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/organisms/header-nav/components/burger-menu-next.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HeaderNav] Fix burger menu button

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/buttons/button-with-tooltip/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/button-with-tooltip/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HeaderNav] ButtonWithTooltp fix

---

CHANGELOG.md
assets/javascripts/kitten/components/organisms/header-nav/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HeaderNav] Fix border style

---

CHANGELOG.md
assets/javascripts/kitten/components/organisms/header-nav/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HeaderNav] Fixes margin

---

CHANGELOG.md
assets/javascripts/kitten/components/atoms/avatar-with-text-and-badge/__snapshots__/test.js.snap
assets/javascripts/kitten/components/atoms/avatar-with-text-and-badge/index.js
assets/javascripts/kitten/components/organisms/header-menu/__snapshots__/test.js.snap
assets/javascripts/kitten/components/organisms/header-menu/styles.js
assets/javascripts/kitten/components/organisms/header-nav/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HeaderNav] Improve styles.

---

CHANGELOG.md
assets/javascripts/kitten/components/form/text-input-with-button/text-input-with-button.stories.js
assets/javascripts/kitten/components/molecules/buttons/button/button.stories.js
assets/javascripts/kitten/components/molecules/buttons/button/helpers/modifier-styles.js
assets/javascripts/kitten/components/molecules/buttons/button/index.js
assets/javascripts/kitten/components/molecules/cards/vertical-card-with-action/vertical-card-with-action.stories.js
assets/javascripts/kitten/components/molecules/text-copy/stories.js
assets/javascripts/kitten/components/organisms/header-menu/components/item.js

Vercel link:
Screenshot:
TODO:

[Button] Add calcium modifier prop

---

CHANGELOG.md
assets/javascripts/kitten/components/form/toggle-switch/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ToggleSwitch] Fix controlled switch

---

CHANGELOG.md
assets/javascripts/kitten/components/atoms/lendo-loading-animation/__snapshots__/test.js.snap
assets/javascripts/kitten/components/atoms/lendo-loading-animation/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[LendoLoadingAnimation] Fix console error

---

CHANGELOG.md
assets/javascripts/kitten/components/form/standalone-range-date-picker/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/button-group/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/button-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/button-question-mark-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/button-with-tooltip/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/button/helpers/modifier-styles.js
assets/javascripts/kitten/components/molecules/buttons/checkable-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/close-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/social-button-icon-words/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/social-button-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/backing-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/contribution-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/team-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/triptych/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/vertical-card-with-action/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/drag-and-drop-list/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/expand/expand-board/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/text-copy/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/upload/basic-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/upload/document-manager/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/upload/image-drop-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/organisms/header-menu/__snapshots__/test.js.snap

Closes #.
Vercel link:
Screenshot:
TODO:

[Button] Use new `disabled` style

---

CHANGELOG.md
assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/date-picker/__snapshots__/date-picker.test.js.snap
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/password-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-limit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-unit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input/index.js
assets/javascripts/kitten/components/form/text-input/test.js
assets/javascripts/kitten/components/form/text-input/text-input.stories.js
assets/javascripts/kitten/components/form/text-input/text-input.stories.mdx
assets/javascripts/kitten/components/molecules/cards/contribution-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/text-copy/__snapshots__/test.js.snap

Vercel link:
Screenshot:
TODO:

[TextInput]  Add `darkBackground` prop.

---

CHANGELOG.md
assets/javascripts/kitten/components/atoms/lendo-loading-animation/__snapshots__/test.js.snap
assets/javascripts/kitten/components/atoms/lendo-loading-animation/index.js
assets/javascripts/kitten/components/atoms/lendo-loading-animation/stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[LendoLoadingAnimation] Fix style bug

---

assets/javascripts/kitten/components/form/range-slider/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/range-slider/index.js
assets/javascripts/kitten/components/form/toggle-switch/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/toggle-switch/index.js
assets/javascripts/kitten/components/graphics/icons/rocket-circle-icon/index.js
assets/javascripts/kitten/components/molecules/cards/crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/crowdfunding-card/styles.js
assets/javascripts/kitten/components/molecules/carousels/carousel/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/drag-and-drop-list/index.js
assets/stylesheets/kitten/tokens/_border-radius.scss

Closes #.
Vercel link:
Screenshot:
TODO:

[Token] Fix `--border-radius-xl` token

---

CHANGELOG.md
assets/javascripts/kitten/components/form/tag-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/tag-input/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[TagInput] Fix focus styles

---

CHANGELOG.md
assets/javascripts/kitten/components/atoms/icon-badge/__snapshots__/test.js.snap
assets/javascripts/kitten/components/atoms/icon-badge/index.js
assets/javascripts/kitten/components/atoms/icon-badge/test.js
assets/javascripts/kitten/components/atoms/stepper-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/alert-box/__snapshots__/test.js.snap
assets/javascripts/kitten/components/organisms/stepper/__snapshots__/test.js.snap

Closes #.
Vercel link:
Screenshot:
TODO:

[IconBadge] Remove text capacity

---

CHANGELOG.md
assets/javascripts/kitten/components/organisms/header-nav/styles.js

Closes #.
Vercel link:
- https://kitten-git-header-nav-fix-active-item-border-kisskissbankbank.vercel.app/?path=/story/organisms-headernav--lendopolis
Screenshot:
TODO:

[HeaderNav] Fix border bottom on active nav link

---

CHANGELOG.md
assets/javascripts/kitten/components/organisms/header-menu/__snapshots__/test.js.snap
assets/javascripts/kitten/components/organisms/header-menu/styles.js
assets/javascripts/kitten/components/organisms/header-nav/stories/lendopolis.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HeaderMenu] Fix external items paddings

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/desk-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/desk-layout/stories.js
assets/javascripts/kitten/components/layout/desk-layout/styles.js
assets/javascripts/kitten/components/layout/sticky-container/index.js
assets/javascripts/kitten/components/organisms/header-nav/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DeskLayout] Fixe position style

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/comment-block/comment-form/comment-form.stories.js
assets/javascripts/kitten/components/molecules/comment-block/comment-form/index.js

Ajout d'un bouton close sur le composant CommentForm pour permettre de fermer/cacher le formulaire.

[CommentForm] Add close button

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/expand/accordeon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/expand/accordeon/components/content.js
assets/javascripts/kitten/components/molecules/expand/accordeon/components/header.js
assets/javascripts/kitten/components/molecules/expand/accordeon/index.js
assets/javascripts/kitten/components/molecules/expand/accordeon/stories.js

[Accordeon] Can have multiple opened items

---

CHANGELOG.md
package-lock.json
package.json

Closes #.
Vercel link:
Screenshot:
TODO:

[Release] Add built js files for 6.10.0

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/stories/with-dashboard.js
assets/javascripts/kitten/components/molecules/cards/backing-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/backing-card/components/button.js
assets/javascripts/kitten/components/molecules/cards/contribution-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/contribution-card/components/action.js
assets/javascripts/kitten/components/molecules/upload/document-manager/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/upload/document-manager/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Cards] Improve `borderRadius` of buttons on all cards.

---

CHANGELOG.md
assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/date-picker/__snapshots__/date-picker.test.js.snap
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/password-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-button/index.js
assets/javascripts/kitten/components/form/text-input-with-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-icon/index.js
assets/javascripts/kitten/components/form/text-input-with-limit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-limit/index.js
assets/javascripts/kitten/components/form/text-input-with-unit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-unit/index.js
assets/javascripts/kitten/components/form/text-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input/index.js
assets/javascripts/kitten/components/molecules/cards/contribution-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/text-copy/__snapshots__/test.js.snap

Closes #.
Vercel link:
Screenshot:
TODO:

[Input] New UI

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/desk-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/desk-layout/stories/with-contributions.js
assets/javascripts/kitten/components/layout/desk-layout/styles.js

Closes #.
Vercel link:
- https://kitten-git-desk-layout-style-fixes-kisskissbankbank.vercel.app/?path=/story/layout-desklayout--default
Screenshot:
TODO:

[DeskLayout] Style adjustments

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/desk-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/desk-layout/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DeskLayout] Add width limit

---

CHANGELOG.md
assets/javascripts/kitten/components/form/tag-input/index.js
assets/javascripts/kitten/components/form/tag-input/stories.js
src/components/form/tag-input/index.js
src/esm/components/form/tag-input/index.js

Permet de contrôler les valeurs de la liste

Add itemsList to `TagInput`

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/cards/project-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/project-card/index.js
assets/javascripts/kitten/components/molecules/cards/project-card/stories.js
assets/javascripts/kitten/components/molecules/cards/project-card/styles.js
assets/javascripts/kitten/components/molecules/cards/project-card/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ProjectCard] Fix link props

---

assets/javascripts/kitten/components/molecules/cards/project-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/project-card/index.js
assets/javascripts/kitten/components/molecules/cards/project-card/stories.js
assets/javascripts/kitten/components/molecules/cards/project-card/styles.js
assets/javascripts/kitten/components/molecules/carousels/carousel/project-carousel.stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ProjectCard] Block fixes

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/cards/summary-card/components/title-bar.js
assets/javascripts/kitten/components/molecules/cards/summary-card/stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[SummaryCard] Fix title-bar styles

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/cards/project-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/project-card/index.js
assets/javascripts/kitten/components/molecules/cards/project-card/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ProjectCard] Add mobile styles

---

CHANGELOG.md
assets/javascripts/kitten/components/form/date-picker/__snapshots__/date-picker.test.js.snap
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/text-input-with-unit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-unit/index.js
assets/javascripts/kitten/components/molecules/cards/contribution-card/__snapshots__/test.js.snap

Closes #.
Vercel link:
Screenshot:
TODO:

[TextInputWithUnit] Improve styles.

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/cards/project-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/project-card/index.js
assets/javascripts/kitten/components/molecules/cards/project-card/stories.js
assets/javascripts/kitten/components/molecules/cards/project-card/styles.js

Closes #.
Vercel link:
- https://kitten-git-project-card-add-loading-prop-kisskissbankbank.vercel.app/?path=/story/molecules-cards-projectcard--loading
Screenshot:
TODO:

[ProjectCard] Add `loading` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/cards/project-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/project-card/index.js
assets/javascripts/kitten/components/molecules/cards/project-card/stories.js
assets/javascripts/kitten/components/molecules/cards/project-card/test.js
assets/stylesheets/kitten/utilities/text/_transform.scss

Closes #.
Vercel link:
Screenshot:
TODO:

[ProjectCard] Add `Sticker` subcomponent

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/cards/project-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/project-card/index.js
assets/javascripts/kitten/components/molecules/cards/project-card/stories.js
assets/javascripts/kitten/components/molecules/cards/project-card/styles.js
assets/javascripts/kitten/components/molecules/cards/project-card/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ProjectCard] Style fixes

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/upload/image-drop-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/upload/image-drop-uploader/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ImageUploader] Fix styles

---

CHANGELOG.md
assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/date-picker/__snapshots__/date-picker.test.js.snap
assets/javascripts/kitten/components/form/field/__snapshots__/field.test.js.snap
assets/javascripts/kitten/components/form/password-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-limit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input-with-unit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/text-input/index.js
assets/javascripts/kitten/components/molecules/cards/contribution-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/text-copy/__snapshots__/test.js.snap

Closes #.
Vercel link:
Screenshot:
TODO:

[TextInput] Improve placeholder style.

---

assets/javascripts/kitten/components/graphics/icons-next/icons-next.stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Icons] Add `Icônes bicolores` group

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/buttons/tag-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/buttons/tag-button/index.js
assets/javascripts/kitten/components/molecules/buttons/tag-button/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[TagButton] Fix test to remove deprecation warning

---

CHANGELOG.md
assets/javascripts/kitten/components/graphics/icons-next/icons-next.stories.js
assets/javascripts/kitten/components/graphics/icons-next/star-icon-next/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[StarIconNext] Add `bgColor` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/comment-block/comment/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/comment-block/comment/comment.stories.js
assets/javascripts/kitten/components/molecules/comment-block/comment/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Comment] Deprecate ownerUrl prop

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/cards/project-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/project-card/styles.js

…
Closes #.
Vercel link:
Screenshot:
TODO:

[ProjectCard] Safari-related fixes on image proportions and sticker alignment

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/cards/horizontal-crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/cards/horizontal-crowdfunding-card/index.js
assets/javascripts/kitten/components/molecules/cards/horizontal-crowdfunding-card/stories.js
assets/javascripts/kitten/components/molecules/cards/horizontal-crowdfunding-card/test.js
assets/javascripts/kitten/components/molecules/cards/project-card/stories.js

Closes #.
Vercel link:
- https://kitten-git-horizontal-crowdfunding-card-91317a-kisskissbankbank.vercel.app/?path=/story/molecules-cards-horizontalcrowdfundingcard--permanent-project
- https://kitten-git-horizontal-crowdfunding-card-91317a-kisskissbankbank.vercel.app/?path=/story/molecules-cards-projectcard--permanent-project
Screenshot:
TODO:

[HorizontalCrowdfundingCard] Add `noProgress` prop

---

.storybook/main.js
assets/javascripts/kitten/components/molecules/alert/stories.js
package-lock.json
package.json

Closes #.
Vercel link:
Screenshot:
TODO:

[Storybook] Add `design` addon

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/text-copy/index.js
assets/javascripts/kitten/components/molecules/text-copy/stories.js

[TextCopy] Add size props for input and button

---

CHANGELOG.md
assets/javascripts/kitten/components/organisms/nav-bar/__snapshots__/test.js.snap
assets/javascripts/kitten/components/organisms/nav-bar/index.js
assets/javascripts/kitten/components/organisms/nav-bar/nav-bar.stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[NavBar] Add `small` value on `modifier` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/form/location-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/location-input/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[LocationInput] Improve styles.

---

CHANGELOG.md
assets/javascripts/kitten/components/molecules/alert-box/__snapshots__/test.js.snap
assets/javascripts/kitten/components/molecules/alert-box/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[AlertBox] Improve styles

---

CHANGELOG.md
assets/javascripts/kitten/tokens/border.stories.mdx

Closes #.
Vercel link:
Screenshot:
TODO:

[Tokens] Corrige border bug and add border-radius

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/backing-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/backing-card/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[BackingCard] Add gradient on truncated description

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/backing-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/backing-card/components/heading-tag.js
assets/javascripts/kitten/components/structure/cards/backing-card/stories.js
assets/javascripts/kitten/components/structure/cards/backing-card/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[BackingCard] Update styles & disabled state

---

CHANGELOG.md
assets/javascripts/kitten/components/graphics/icons-next/icons-next.stories.js
assets/javascripts/kitten/components/graphics/icons-next/people-icon-next/index.js
assets/javascripts/kitten/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Icons] Add `PeopleIconNext` component.

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/backing-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/backing-card/components/description.js
assets/javascripts/kitten/components/structure/cards/backing-card/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[BackingCard] Fix gradient display

---

CHANGELOG.md
assets/javascripts/kitten/components/form/select/dropdown-phone-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/select/dropdown-phone-select/index.js
assets/javascripts/kitten/components/form/select/dropdown-phone-select/stories.js

[DropdownPhoneSelect] Add normalizer to modify phone value

---

CHANGELOG.md
assets/javascripts/kitten/components/action/text-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/action/text-button/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[TextButton] Improve styles.

---

.storybook/main.js
assets/javascripts/kitten/components/information/alert/stories.js
package-lock.json
package.json

Vercel link:
Screenshot:
TODO:

[Storybook] Removed design addon

---

CHANGELOG.md
assets/javascripts/kitten/components/interaction/upload/document-manager/__snapshots__/test.js.snap
assets/javascripts/kitten/components/interaction/upload/document-manager/index.js
assets/javascripts/kitten/components/interaction/upload/document-manager/stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DocumentsManager] Markup fixes

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/backing-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/backing-card/stories.js
assets/javascripts/kitten/components/structure/cards/backing-card/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[BackingCard] Fix `BackingCard.Title` untruncated style

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/hero-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/hero-layout/styles.js

Suppression du padding spécifique aux grands écrans
Vercel link:
Screenshot:
TODO:

[HeroLayout] Keep same padding for all screens sizes

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/header-nav/components/search-input.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HeaderNav] Add accessibility props to SearchInput

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/expand/dropdown-menu/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DropdownMenu] Fix button argument

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/dashboard-menu/index.js

https://trello.com/c/oitJoPpt/1452-nav-bar-onglet-admin

[Expandable] Use query selector and aria-current to get active element

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/pagination/__snapshots__/test.js.snap
assets/javascripts/kitten/components/navigation/pagination/index.js
assets/javascripts/kitten/components/navigation/pagination/stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Pagination] Modernize styles

---

CHANGELOG.md
assets/javascripts/kitten/components/action/text-copy/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/autocomplete/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/autocomplete/index.js
assets/javascripts/kitten/components/form/autocomplete/stories.js
assets/javascripts/kitten/components/form/color-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/date-picker/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/location-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/location-input/index.js
assets/javascripts/kitten/components/form/input/password-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/text-input-with-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/text-input-with-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/text-input-with-limit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/text-input-with-unit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/text-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/text-input/index.js
assets/javascripts/kitten/components/form/select/dropdown-phone-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/select/dropdown-select-with-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/select/dropdown-select-with-input/index.js
assets/javascripts/kitten/components/form/select/dropdown-select-with-input/stories.js
assets/javascripts/kitten/components/form/select/dropdown-select/__snapshots__/combobox.test.js.snap
assets/javascripts/kitten/components/form/select/dropdown-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/select/dropdown-select/styles.js
assets/javascripts/kitten/components/structure/cards/contribution-card/__snapshots__/test.js.snap

Closes #.
Vercel link:
Screenshot:
TODO:

[Style] Change disabled styles on input components

---

CHANGELOG.md
assets/javascripts/kitten/components/action/button/helpers/modifier-styles.js
assets/javascripts/kitten/components/action/button/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Button] Add krypton modifier

---

CHANGELOG.md
assets/javascripts/kitten/components/action/button/index.js
assets/javascripts/kitten/karl/pages/homepage/dialog-with-picture-border/index.js
assets/javascripts/kitten/karl/pages/login/components/login.js
assets/javascripts/kitten/karl/pages/partner/components/text-with-images.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Button] Remove old size props.

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/text-input-with-limit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/text-input-with-limit/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[TextInputWithLimit] Improve styles.

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/stories/with-table.js
assets/javascripts/kitten/components/layout/scrollable-container/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/scrollable-container/index.js
assets/javascripts/kitten/components/layout/scrollable-container/styled.js
assets/javascripts/kitten/components/structure/tables/grid-table/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/tables/grid-table/index.js
assets/javascripts/kitten/components/structure/tables/grid-table/stories.js
assets/javascripts/kitten/components/structure/tables/grid-table/styles.js
assets/javascripts/kitten/components/structure/tables/grid-table/test.js
assets/javascripts/kitten/index.js

Closes #.
Vercel link:
- https://kitten-git-grid-table-new-kisskissbankbank.vercel.app/?path=/story/structure-tables-gridtable--default
- https://kitten-git-grid-table-new-kisskissbankbank.vercel.app/?path=/story/layout-dashboardlayout--with-table-content
Screenshot:
TODO:

[GridTable] Add component

---

CHANGELOG.md
assets/javascripts/kitten/components/information/tag/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/tag/index.js
assets/javascripts/kitten/components/interaction/upload/documents-drop-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/backing-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/project-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/project-card/index.js
assets/javascripts/kitten/components/structure/cards/project-card/stories.js
assets/javascripts/kitten/components/structure/cards/project-card/styles.js
assets/javascripts/kitten/components/structure/cards/project-card/test.js

Closes #.
Vercel link:
- https://kitten-git-project-card-lendo-version-kisskissbankbank.vercel.app/?path=/story/structure-cards-projectcard--lendopolis
Screenshot:
TODO:

[ProjectCard] Add Lendopolis particulars

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/content-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/content-card/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ContentCard] Update padding for mobile view

---

CHANGELOG.md
assets/javascripts/kitten/components/action/checkable-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/action/checkable-button/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[CheckableButton] Improve style.

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/summary-card/stories.js
assets/javascripts/kitten/components/structure/cards/summary-card/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[SummaryCard] Improve contributorSubscription columns

---

CHANGELOG.md
assets/javascripts/kitten/components/action/button/index.js
assets/javascripts/kitten/components/navigation/header-menu/__snapshots__/test.js.snap

Closes #.
Vercel link:
Screenshot:
TODO:

[Button] Force default value for props

---

CHANGELOG.md
assets/javascripts/kitten/components/information/alert/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/alert/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

Fix: Alert: Improve styles

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DashboardLayout] Fix alerts fade on mobile menu open

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/header-nav/stories/kisskissbankbank.js
assets/javascripts/kitten/components/navigation/header-nav/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HeaderNav] Fix overflow bug with ButtonWithTooltip

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/field/components/radio-set.js
assets/javascripts/kitten/components/form/field/stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Field] Fix  Field.RadioSet import error

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/field/test.js
assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button-set/index.js
assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[RadioButton] Hardcode default variant value

---

CHANGELOG.md
assets/javascripts/kitten/components/information/alert/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/alert/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Alert] Close button accessibility fixes

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/horizontal-crowdfunding-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/horizontal-crowdfunding-card/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HorizontalCrowdfundingCard] Add progressLabel prop

---

CHANGELOG.md
assets/javascripts/kitten/components/information/avatar-with-text-and-badge/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/badge/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/badge/index.js
assets/javascripts/kitten/components/navigation/header-menu/__snapshots__/test.js.snap
assets/javascripts/kitten/components/navigation/header-menu/components/item.js
assets/javascripts/kitten/components/navigation/header-nav/stories.js
assets/javascripts/kitten/components/navigation/header-nav/stories/kisskissbankbank.js
assets/javascripts/kitten/components/navigation/header-nav/stories/lendopolis.js
assets/javascripts/kitten/components/navigation/header-nav/stories/minimalist.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HeaderNav] Accessibility fixes

---

CHANGELOG.md
assets/javascripts/kitten/components/form/select/dropdown-select-with-input/index.js
assets/javascripts/kitten/components/form/select/dropdown-select/combobox.js
assets/javascripts/kitten/components/form/select/dropdown-select/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Accessibility] Revert Fix a11y warning related to roles on components

---

CHANGELOG.md
assets/javascripts/kitten/components/navigation/dashboard-menu/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DashboardMenuSelector] Handle case if no active item

---

CHANGELOG.md
assets/javascripts/kitten/components/form/toggle-switch/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/toggle-switch/index.js
assets/javascripts/kitten/components/form/toggle-switch/stories.js
assets/javascripts/kitten/components/form/toggle-switch/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ToggleSwitch] Remove `big` prop.

---

CHANGELOG.md
assets/javascripts/kitten/components/graphics/icons-next/icons-next.stories.js
assets/javascripts/kitten/components/graphics/icons-next/status-icon-next/index.js
assets/javascripts/kitten/components/information/alert-box/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/alert-box/index.js
assets/javascripts/kitten/components/information/alert-box/stories.js
assets/javascripts/kitten/components/information/icon-badge/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/icon-badge/index.js
assets/javascripts/kitten/components/information/icon-badge/stories.js
assets/javascripts/kitten/components/interaction/stepper-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/interaction/stepper/__snapshots__/test.js.snap

Closes #.
Vercel link:
-https://kitten-git-feature-new-variant-alert-box-kisskissbankbank.vercel.app/?path=/story/information-alertbox--default&args=status:pending;size:!undefined;fit:!undefined;iconPosition:!undefined
Screenshot:
TODO:

[AlertBox] Add `pending` new status.

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/manager-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/manager-card/index.js
assets/javascripts/kitten/components/structure/cards/manager-card/stories.js
assets/javascripts/kitten/components/structure/cards/manager-card/test.js
assets/javascripts/kitten/components/structure/cards/project-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/summary-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/summary-card/stories.js
assets/javascripts/kitten/components/structure/cards/summary-card/test.js
assets/javascripts/kitten/components/typography/text/index.js
assets/javascripts/kitten/components/typography/text/stories.js
assets/javascripts/kitten/components/typography/text/test.js
assets/javascripts/kitten/index.js
assets/stylesheets/kitten/utilities/text/_color.scss
assets/stylesheets/kitten/utilities/text/_line.scss

Closes #.
Vercel link:
- https://kitten-git-manager-card-add-component-kisskissbankbank.vercel.app/?path=/story/structure-cards-managercard--default
Screenshot:
TODO:

[ManagerCard] Add component

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[RadioButton] Improve style.

---

CHANGELOG.md
assets/javascripts/kitten/components/interaction/upload/image-drop-uploader/index.js

Ne met pas le async au niveau de la fonction du useEffect afin d'éviter des warning/erreur avec React 18

Fix async function on use effect

---

CHANGELOG.md
assets/javascripts/kitten/components/form/autocomplete/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/autocomplete/index.js
assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap

Closes #.
Vercel link:
Screenshot:
TODO:

[Autocomplete] Improve style

---

CHANGELOG.md
assets/javascripts/kitten/components/form/select/dropdown-select/__snapshots__/combobox.test.js.snap
assets/javascripts/kitten/components/form/select/dropdown-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/select/dropdown-select/index.js
assets/javascripts/kitten/components/form/select/dropdown-select/stories.js
assets/javascripts/kitten/components/form/select/dropdown-select/styles.js
assets/javascripts/kitten/components/form/select/dropdown-select/test.js

Closes #.
Vercel link:
- https://kitten-git-dropdown-select-cut-if-scrollable-kisskissbankbank.vercel.app/?path=/story/form-select-dropdownselect--default
Screenshot:
TODO:

[DropdownSelect] Change list style to cut last item if scrollable

---

CHANGELOG.md
assets/javascripts/kitten/components/interaction/upload/image-drop-uploader/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ImageDropUploader] Fix async function

---

CHANGELOG.md
assets/javascripts/kitten/index.js

Expose les deux composants dans la lib

Add CheckboxButton and CheckButtonSet export

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/hero-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/hero-layout/stories.js
assets/javascripts/kitten/components/layout/hero-layout/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HeroLayout] Fix Hero z-index

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/hero-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/hero-layout/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HeroLayout] Fix background position in Simple mode

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/field/components/autocomplete.js
assets/javascripts/kitten/components/form/input/autocomplete/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/autocomplete/index.js
assets/javascripts/kitten/components/form/input/autocomplete/stories.js
assets/javascripts/kitten/components/form/input/autocomplete/test.js
assets/javascripts/kitten/components/form/input/tag-input-autocomplete/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/tag-input-autocomplete/index.js
assets/javascripts/kitten/components/form/input/tag-input-autocomplete/stories.js
assets/javascripts/kitten/components/form/input/tag-input-autocomplete/test.js
assets/javascripts/kitten/components/form/input/tag-input/index.js
assets/javascripts/kitten/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[TagInputAutocomplete] Add component

---

CHANGELOG.md
assets/javascripts/kitten/components/information/avatar-with-text-and-badge/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/avatar-with-text-and-badge/index.js
assets/javascripts/kitten/components/information/avatar-with-text-and-badge/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[AvatarWithTextAndBadge] Better prop propagation on `Image` subcomponent

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/manager-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/manager-card/index.js
assets/javascripts/kitten/components/structure/cards/manager-card/stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ManagerCard] Fix multiline content

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/expand/dropdown-menu/index.js
assets/javascripts/kitten/components/structure/expand/dropdown-menu/stories.js
assets/javascripts/kitten/helpers/hooks/use-focus-trap/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DropdownMenu] Add onOpen and onClose props

---

assets/javascripts/kitten/components/form/select/dropdown-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/select/dropdown-select/test.js
assets/javascripts/kitten/components/information/toggletip/test.js
assets/javascripts/kitten/components/structure/cards/editorial-card/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Tests] Remove warnings and errors

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/project-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/project-card/styles.js
assets/javascripts/kitten/components/structure/carousels/carousel/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/carousels/carousel/index.js
assets/javascripts/kitten/components/structure/carousels/carousel/stories.js
assets/javascripts/kitten/components/structure/carousels/carousel/styles.js
assets/javascripts/kitten/components/structure/carousels/carousel/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Carousel] Add shadowSize prop

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/content-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/content-card/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ContentCard] Improve style.

---

CHANGELOG.md
assets/stylesheets/kitten/tokens/_borders.scss
assets/stylesheets/kitten/utilities/border/_border.scss

Closes #.
Vercel link:
Screenshot:
TODO:

[Utilities] Add border utility classes

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/content-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/content-card/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ContentCard] Add `box-shadow` variable.

---

CHANGELOG.md
assets/javascripts/kitten/components/graphics/icons-next/status-icon-next/index.js
assets/javascripts/kitten/components/information/alert/__snapshots__/test.js.snap

Closes #.
Vercel link:
Screenshot:
TODO:

[AlertBox] Improve `IconBadge` style.

---

CHANGELOG.md
assets/javascripts/kitten/components/action/button-group/__snapshots__/test.js.snap
assets/javascripts/kitten/components/action/button-question-mark-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/action/button-with-tooltip/__snapshots__/test.js.snap
assets/javascripts/kitten/components/action/button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/action/button/index.js
assets/javascripts/kitten/components/action/button/stories.js
assets/javascripts/kitten/components/action/checkable-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/action/close-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/action/social-button-icon-words/__snapshots__/test.js.snap
assets/javascripts/kitten/components/action/social-button-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/action/text-copy/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/color-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/modal-footer-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/text-input-with-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/standalone-range-date-picker/__snapshots__/test.js.snap
assets/javascripts/kitten/components/interaction/discussion/__snapshots__/test.js.snap
assets/javascripts/kitten/components/interaction/drag-and-drop-list/__snapshots__/test.js.snap
assets/javascripts/kitten/components/interaction/upload/basic-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/interaction/upload/document-manager/__snapshots__/test.js.snap
assets/javascripts/kitten/components/interaction/upload/image-drop-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layer/modal/__snapshots__/test.js.snap
assets/javascripts/kitten/components/navigation/header-menu/__snapshots__/test.js.snap
assets/javascripts/kitten/components/navigation/pagination/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/contribution-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/reward-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/team-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/triptych/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/vertical-card-with-action/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/expand/expand-board/__snapshots__/test.js.snap

Closes #.
Vercel link:
- https://kitten-git-button-add-hasbullet-prop-kisskissbankbank.vercel.app/?path=/story/action-button--with-bullet
Screenshot:
TODO:

[Bullet] Add hasBullet prop

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/horizontal-project-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/horizontal-project-card/index.js
assets/javascripts/kitten/components/structure/cards/horizontal-project-card/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[HorizontalProjectCard] Remove last line if no info

---

assets/javascripts/kitten/karl/pages/footer/index.js
assets/javascripts/kitten/karl/pages/footer/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Footer] Little fixe

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/field/examples.js
assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button-set/index.js
assets/javascripts/kitten/components/form/radio-button-set/stories.js
assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/index.js
assets/javascripts/kitten/components/form/radio-button/stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[V11] Remove andromeda variant

---

CHANGELOG.md
assets/javascripts/kitten/components/form/input/text-input-with-button/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[V11] Remove deprecated value prop 

---

CHANGELOG.md
assets/javascripts/kitten/components/information/alert/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/alert/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[V11] Remove deprecated Alert props

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/reward-card/components/index.js
assets/javascripts/kitten/components/structure/cards/reward-card/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[V11] Put it back `RewardCard.Info`.

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/backer-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/backer-card/index.js
assets/javascripts/kitten/components/structure/cards/backer-card/stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[BackerCard] Modernize component

---

CHANGELOG.md
assets/javascripts/kitten/components/form/select/dropdown-select/__snapshots__/combobox.test.js.snap
assets/javascripts/kitten/components/form/select/dropdown-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/select/dropdown-select/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DropdownSelect] Change outline style on `combobox` input

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[RadioButton] Better font weight styles

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/chat-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/chat-layout/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ChatLayout] Fix main error

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/chat-layout/stories.js
assets/javascripts/kitten/components/navigation/messages-menu/__snapshots__/test.js.snap
assets/javascripts/kitten/components/navigation/messages-menu/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[MessagesMenu] Fix message height

---

assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DashboardLayout] Fix side column width

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/people-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/people-card/index.js
assets/javascripts/kitten/components/structure/cards/people-card/stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[PeopleCard] Add `disabled` prop.

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/reward-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/reward-card/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[RewardCard] Fix background color

---

CHANGELOG.md
assets/javascripts/kitten/components/action/text-copy/__snapshots__/test.js.snap
assets/javascripts/kitten/components/action/text-copy/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[TextCopy] Fix resize bug on Webkit

---

CHANGELOG.md
assets/javascripts/kitten/components/embed/embed-player/__snapshots__/test.js.snap
assets/javascripts/kitten/components/embed/embed-player/index.js
assets/javascripts/kitten/components/embed/video/__snapshots__/test.js.snap
assets/javascripts/kitten/components/embed/video/index.js
assets/javascripts/kitten/components/graphics/icons-next/icons-next.stories.js
assets/javascripts/kitten/components/graphics/icons-next/player-icon-next/index.js
assets/javascripts/kitten/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Video] Update player icon

---

CHANGELOG.md
assets/javascripts/kitten/components/graphics/animations/loader-with-paragraph/__snapshots__/test.js.snap
assets/javascripts/kitten/components/graphics/animations/loader-with-paragraph/index.js
assets/javascripts/kitten/components/graphics/animations/loader-with-paragraph/stories.js
assets/javascripts/kitten/components/graphics/animations/loader-with-paragraph/test.js

Closes #.
Vercel link:
- https://kitten-git-loader-with-paragraph-custom-dbe41b-kisskissbankbank.vercel.app/?path=/story/graphics-animations-loaderwithparagraph--with-custom-component&args=loaderPosition:top
Screenshot:
TODO:

[LoaderWithParagraph] Add loaderComponent prop

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DashboardLayout] Add position style to main

---

CHANGELOG.md
assets/javascripts/kitten/components/layout/dashboard-layout/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layout/dashboard-layout/styles.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DashboardLayout] Fix main section positionning

---

CHANGELOG.md
assets/javascripts/kitten/components/embed/embed-player/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[EmbedPlayer] Disable embed code sanitization

---

CHANGELOG.md
assets/javascripts/kitten/components/form/input/autocomplete/index.js
assets/javascripts/kitten/components/form/input/autocomplete/stories.js
assets/javascripts/kitten/components/graphics/animations/loader-with-paragraph/__snapshots__/test.js.snap
assets/javascripts/kitten/components/graphics/animations/loader-with-paragraph/stories.js
assets/javascripts/kitten/components/graphics/animations/loader-with-paragraph/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Autocomplete] Accept items objects

---

assets/javascripts/kitten/components/form/input/autocomplete/index.js

- Passage à une fonction asynchrone pour `updateSuggestionsStrategy` 
Vercel link:
Screenshot:
TODO:

[Autocomplete] Update updateSuggestionsStrategy function

---

CHANGELOG.md
assets/javascripts/kitten/components/graphics/icons-next/garbage-icon-next/index.js
assets/javascripts/kitten/components/graphics/icons-next/icons-next.stories.js
assets/javascripts/kitten/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Icons] Add GarbageIconNext

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/expand/dropdown-menu/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/expand/dropdown-menu/index.js
assets/javascripts/kitten/components/structure/expand/dropdown-menu/stories.js
assets/javascripts/kitten/components/structure/expand/dropdown-menu/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DropdownMenu] Add textProps class

---

CHANGELOG.md
assets/javascripts/kitten/components/action/close-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/action/close-button/index.js
assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/field/examples.js
assets/javascripts/kitten/components/form/field/index.js
assets/javascripts/kitten/components/form/field/stories.js
assets/javascripts/kitten/components/form/field/test.js
assets/javascripts/kitten/components/interaction/upload/image-drop-uploader/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layer/modal/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layer/modal/stories.js
assets/javascripts/kitten/components/layer/slide-modal/__snapshots__/test.js.snap
assets/javascripts/kitten/components/layer/slide-modal/index.js
assets/javascripts/kitten/components/layer/slide-modal/stories.js
assets/javascripts/kitten/components/layer/slide-modal/styles.js
assets/javascripts/kitten/components/layer/slide-modal/test.js
assets/javascripts/kitten/index.js

Closes #.
Vercel link:
- https://kitten-git-slide-modal-new-component-kisskissbankbank.vercel.app/?path=/story/layer-slide-modal--with-action
Screenshot:
TODO:

[SlideModal] Add component

---

CHANGELOG.md
assets/javascripts/kitten/components/action/button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/action/button/index.js
assets/javascripts/kitten/components/action/button/test.js
assets/javascripts/kitten/components/structure/carousels/carousel/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/carousels/carousel/index.js
assets/javascripts/kitten/components/structure/carousels/carousel/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Button] Set valid default size

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/reward-card/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[RewardCard] Fix Info import

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/reward-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/reward-card/components/index.js
assets/javascripts/kitten/components/structure/cards/reward-card/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Front] Refix RewarCard info

---

CHANGELOG.md
assets/javascripts/kitten/components/action/text-copy/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/color-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/credit-card-form/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/autocomplete/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/location-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/password-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/text-input-with-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/text-input-with-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/text-input-with-limit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/text-input-with-unit/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/text-input/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/input/text-input/index.js
assets/javascripts/kitten/components/form/input/text-input/test.js
assets/javascripts/kitten/components/interaction/discussion/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/contribution-card/__snapshots__/test.js.snap

L'idée c'est de : 
- Quand on a un `value` le composant est contrôlé
- Quand on a un `defaultValue` le composant n'est pas contrôlé

Fix text input defautvalue/value

---

CHANGELOG.md
assets/javascripts/kitten/components/typography/title-with-stroke/__snapshots__/test.js.snap
assets/javascripts/kitten/components/typography/title-with-stroke/index.js
assets/javascripts/kitten/components/typography/title-with-stroke/stories.js
assets/javascripts/kitten/components/typography/title-with-stroke/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[TitleWithStroke] Add `noMargin` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/interaction/editor-bar/__snapshots__/test.js.snap
assets/javascripts/kitten/components/interaction/editor-bar/index.js
assets/javascripts/kitten/components/interaction/editor-bar/stories.js
assets/javascripts/kitten/components/interaction/editor-bar/test.js
assets/javascripts/kitten/index.js

Closes #.
Vercel link:
- https://kitten-git-editor-bar-add-component-kisskissbankbank.vercel.app/?path=/story/interaction-editorbar--default
Screenshot:
TODO:

[EditorBar] Add component

---

CHANGELOG.md
assets/javascripts/kitten/components/form/checkbox-button-set/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/checkbox-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/checkbox-button/index.js
assets/javascripts/kitten/components/form/checkbox-button/stories.js
assets/javascripts/kitten/components/form/checkbox-set/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/checkbox/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/checkbox/index.js
assets/javascripts/kitten/components/form/checkbox/stories.js
assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button-set/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/radio-button/index.js
assets/javascripts/kitten/components/form/radio-button/stories.js
assets/javascripts/kitten/components/form/radio/stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Radio*+Checkbox*] Update disabled styles

---

CHANGELOG.md
assets/javascripts/kitten/components/graphics/icons/download-icon/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[DownloadIcon] Fix colour propagation

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/project-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/project-card/index.js
assets/javascripts/kitten/components/structure/cards/project-card/stories.js
assets/javascripts/kitten/components/structure/cards/project-card/styles.js
assets/javascripts/kitten/components/structure/carousels/carousel/__snapshots__/test.js.snap

Closes #.
Vercel link:
Screenshot:
TODO:

[ProjectCard] Add dark mode support

---

assets/javascripts/kitten/components/structure/carousels/carousel-next/components/carousel-inner.js

Closes #.
Vercel link:
Screenshot:
TODO:

[CarouselNext] Fix scroll

---

CHANGELOG.md
assets/javascripts/kitten/components/form/input/autocomplete/index.js
assets/javascripts/kitten/components/form/input/autocomplete/stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

Controlled autcomplete

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/reward-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/reward-card/index.js
assets/javascripts/kitten/components/structure/cards/reward-card/stories.js
assets/javascripts/kitten/components/structure/cards/reward-card/styles.js
assets/javascripts/kitten/components/structure/cards/reward-card/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[RewardCard] Add `hasShadow` prop

---

CHANGELOG.md
assets/javascripts/kitten/components/action/tag-button/__snapshots__/test.js.snap
assets/javascripts/kitten/components/action/tag-button/index.js
assets/javascripts/kitten/components/action/tag-button/stories.js
assets/javascripts/kitten/components/action/tag-button/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[TagButton] Add rounded prop

---

CHANGELOG.md
assets/javascripts/kitten/components/form/color-select/__snapshots__/test.js.snap
assets/javascripts/kitten/components/form/color-select/index.js
assets/javascripts/kitten/components/form/color-select/stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ColorSelect] Disabled prop

---

assets/javascripts/kitten/components/information/toggletip/stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

Story: use disabled button in Toggletip

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/alert-box/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/alert/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/icon-badge/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/icon-badge/index.js
assets/javascripts/kitten/components/information/icon-badge/stories.js
assets/javascripts/kitten/components/information/icon-badge/test.js
assets/javascripts/kitten/components/information/toggletip/__snapshots__/test.js.snap
assets/javascripts/kitten/components/interaction/stepper-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/interaction/stepper/__snapshots__/test.js.snap

Closes #.
Vercel link:
Screenshot:
TODO:

[IconBadge] Add `state` prop, default to `circle`

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/toggletip/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/toggletip/index.js
assets/javascripts/kitten/components/information/toggletip/stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[ToggleTip] Add checks for page bottom limit

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/alert-box/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/alert/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/icon-badge/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/icon-badge/index.js
assets/javascripts/kitten/components/information/icon-badge/stories.js
assets/javascripts/kitten/components/information/toggletip/__snapshots__/test.js.snap
assets/javascripts/kitten/components/interaction/stepper-icon/__snapshots__/test.js.snap
assets/javascripts/kitten/components/interaction/stepper/__snapshots__/test.js.snap

Closes #.
Vercel link:
Screenshot:
TODO:

[IconBadge] Update styles.

---

CHANGELOG.md
assets/javascripts/kitten/components/feedback/vertical-progress/__snapshots__/test.js.snap
assets/javascripts/kitten/components/feedback/vertical-progress/components/step.js
assets/javascripts/kitten/components/feedback/vertical-progress/stories.js
assets/javascripts/kitten/components/information/boxes/doc-link-box/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/boxes/link-box/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/boxes/link-box/index.js
assets/javascripts/kitten/components/information/boxes/link-box/stories.js
assets/javascripts/kitten/components/information/boxes/link-box/styles.js

- J'ai réduis l'espacement entre les étapes (composant `VerticalProgress`)
- J'ai créé une prop ` isSmall` pour le composant `LinkBox`
Pour coller à cette maquette :

[HomeManager] Update style for new home

---

CHANGELOG.md
assets/javascripts/kitten/components/form/field/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/toggletip/__snapshots__/test.js.snap
assets/javascripts/kitten/components/information/toggletip/index.js
assets/javascripts/kitten/components/information/toggletip/stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Toggletip] Add `bubbleColorText` props and update style.

---

assets/javascripts/kitten/components/structure/cards/project-card/stories.js

Création d'une story du composant `ProjectCard` pour ajouter la card "Sélection de l'équipe"

[ProjectCard] Add TeamSelection storie

---

CHANGELOG.md
assets/javascripts/kitten/components/feedback/vertical-progress/__snapshots__/test.js.snap
assets/javascripts/kitten/components/feedback/vertical-progress/components/step.js

-Suppression du padding spécifique desktop sur le composant `Step` de `VerticalProgress`

[VerticalProgress] Delete big padding on Step component

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/carousels/carousel-next/components/carousel-inner.js
assets/javascripts/kitten/components/structure/carousels/carousel-next/index.js
assets/javascripts/kitten/karl/pages/homepage-2022/components/partner-carousel.js

Fixes item 2 on https://trello.com/c/fM40iS42/2546-home-retours.
Vercel link: https://kitten-git-carousel-next-math-kisskissbankbank.vercel.app/?path=/story/pages-homepage-2022--homepage
TODO:

[CarouselNext] Attempt to fix empty slots when cycling

---

CHANGELOG.md
assets/javascripts/kitten/components/structure/cards/partner-card/__snapshots__/test.js.snap
assets/javascripts/kitten/components/structure/cards/partner-card/index.js
assets/javascripts/kitten/components/structure/cards/partner-card/stories.js
assets/javascripts/kitten/components/structure/cards/partner-card/test.js

Closes #.
Vercel link:
Screenshot:
TODO:

[PartnerCard] Add `stretch` prop.

---

CHANGELOG.md
package-lock.json
package.json
src/components/structure/cards/partner-card/index.js
src/esm/components/structure/cards/partner-card/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Release] Add built js files for 13.3.0

---

CHANGELOG.md

Closes #.
Vercel link:
Screenshot:
TODO:

[CHANGELOG] Clean and add icons

---

CHANGELOG.md
assets/javascripts/kitten/components/typography/text/index.js
assets/javascripts/kitten/components/typography/text/stories.js
assets/javascripts/kitten/components/typography/title-with-stroke/index.js
assets/javascripts/kitten/components/typography/title-with-stroke/stories.js
assets/javascripts/kitten/components/typography/title/index.js
assets/javascripts/kitten/components/typography/title/stories.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Font-family] Update `family` prop, default to `generalsans`

---

CHANGELOG.md
assets/javascripts/kitten/components/interaction/comment-block/comment/__snapshots__/test.js.snap
assets/javascripts/kitten/components/interaction/comment-block/comment/index.js

Closes #.
Vercel link:
Screenshot:
TODO:

[Comment] Update styles.
